# (PART) 生存分析 survival analysis {-}

# 入門 

## 什麼是生存分析 

生存分析，研究的是隨訪中研究對象發生我們關心的事件與否，以及比較發生該事件之前時間的長短 (生存時間) 的一種分析方法。生存數據的常見例子如下: 

- 死亡 (all cause); 
- 診斷/治療後直至死亡發生的時間; 
- 孕婦的懷孕時間 (孕期長短);
- 對象以健康狀態進入研究時開始，直至其診斷爲患有某種疾病的時間。

生存分析中的常見術語: 

- 生存時間 survival time = 失敗時間 failure time = 事件時間 event time。
- 生存分析本身常被叫做事件史分析 time-to-event analysis。


生存分析的結果，可以用來回答很多我們關心的問題:

1. 研究特定人羣中，在某段時間內人口生存 (或死亡) 的模式 (平均壽命): 在英國，某年 (例如 1970 年) 出生的人，能夠生存到 5 歲，40 歲，100 歲的概率是多大？ (關心的是死亡在某人身上發生的概率)
2. 比較兩組或多組人羣之間，不同的特徵導致的死亡時間的差異大小的估計: 某種新療法對於同時被診斷爲相同程度肺癌的患者，和標準療法相比是否能有效延長其生存時間？
3. 研究多種變量 (例如體重，年齡，性別，吸煙，飲食等) 和事件發生時間長短之間的關系: 例如收集健康對象，研究其體質指數 (BMI) 和最終發生二型糖尿病幾率之間的關系，同時要調整其他已知的混雜因素。
4. 預測特定患者的存活幾率: 肝癌患者診斷後的 5 年生存率，10 年生存率的推算。


## 生存數據在哪裏

生存數據其實很常見，下面是幾個例子: 

1. 特定國家特定時間內對人口出生死亡的登記數據; 
2. 在隨機雙盲對照臨牀試驗中，治療組和安慰劑組相比，治療組的生存時間是否真的較長？
3. 前瞻性隊列研究;
4. 非醫學的例子也有很多，例如分析暴風雪降臨之前的時間，或者推測地震可能發生的幾率。



## 生存數據分析之前要裏清楚的問題

1. 對於結果/事件的定義; 
2. 研究的時間起點; 
3. 研究的時間單位是用的月份，周，還是年，是觀察時間，還是患者的實際年齡 (實際年齡就是實際生存時間); 
4. 事件發生時的時間，是否被精確定義了？

## 生存數據的左右截尾

沒有哪個研究能保證觀察隨訪到所有的研究對象最終是否發生了事件 (死亡)，有些對象在研究中途就會退出實驗。所以這些沒有觀察到事件發生，但是在研究的過程中貢獻了生存時間數據的對象，被稱爲刪失數據 (censored)。刪失數據又根據其發生原因的不同被分爲下面幾種: 

1. **行政刪失 (administrative censoring)**: 如果最終事件，被定義爲死亡的話，研究者不大可能等到所有的觀察對象都死亡 (可能耗時幾十年) 之後再分析數據，而是認爲地定義某個時間點作爲研究結束，不再隨訪的時間。
2. **隨訪失敗 (loss to follow-up)**: 無論是幹預型實驗，還是觀察性實驗，有些觀察對象中途無法聯系上，或者改變主義推出實驗的人並不少見。這些對象的出現都意味着研究者無法再對他們進行事件發生與否的觀察了。
3. **死於其他原因 (death from other causes)**: 可能某些研究只關心患者吸煙習慣與死於肺癌的時間長短的關系，當某些觀察對象確實發生了死亡事件，但是死因並不是肺癌時 (肝癌，或者自殺，車禍等)，這些人也被認爲是刪失數據。

上述幾種可能發生的刪失數據，這幾種類型的刪失數據，被叫做**右側刪失數據 (right censoring)，在分析中不能被刪除，因爲他們在未離開研究之前，我們確定他們是沒有發生事件的，他們的觀察時間也應當被放入統計模型中加以考慮。**

### 左側截尾數據 left-truncation

左側截尾現象，又被叫做**延時進入 (delayed entry)**: 由於觀察對象實際進入研究時的年齡各不相同，對所有人的觀察時間，都從出生日開始算起的研究，實施難度極大。此時，應當注意把進入研究之前的生存時間 (進入實驗時的年齡)，考慮進來，因爲這些人至少活到了進入研究的年齡。這也是一種生存偏倚現象，因爲人羣中被觀察到的人，只是一小部分樣本，所以把所有人都當作相同概率進入研究是不恰當的，有許多對象沒有活到進入研究的時間。



## 初步分析生存數據

生存數據，比較的是生存時間。由於時間本身是連續型變量，我們可能會想到利用處理連續型變量時的方法來進行初步的比較: 

1. 每個人生存時間的柱狀圖 (histogram); 
2. 計算生存時間的簡單統計量: 中位數 (median)。

即使是拿穩健統計學方法比較治療組和對照組的中位數是否不同，也無法解決刪失數據的問題。我們需要新的方法來處理生存數據。

## 初步描述生存數據

描述生存數據的統計學正式方案是:

1. 生存方程 the survival function
2. 危險度方程和累積危險度 the hazard function and the cumulative hazard
3. 概率密度方程 the probability density function

### 生存方程

生存方程的定義是，觀測生存時間 $T$，大於某個時間 $t$ 的概率: 

$$
S(t) = Pr(T > t)
$$

累計概率方程是 

$$
F(t) = \text{Pr}(T \leqslant t) = 1 - S(t)
$$


### 危險度方程 

危險度有時候就只叫做危險 (hazard)，時間 $t$ 時的危險度爲 $h(t)$。危險度方程被定義爲: 

$$
h(t) = \lim_{\delta\rightarrow0}\frac{1}{\delta}\text{Pr}(t\leqslant T < t + \delta | T\geqslant t)
$$


危險度利用的是數學中的極限理論，表示在時間 $t$ 和時間 $t+\delta$ (其中$\delta \rightarrow 0$) 之間，觀察對象沒有發生事件的概率。危險度的概念明白了以後，危險度在時間軸上的積分，就被叫做**累積危險度**: 

$$
H(t) = \int_0^th(u)\text{d}u
$$

### 概率密度方程

和其他的方程類似，常用 $f(t)$ 標記生存時間的概率密度方程: 

$$
f(t) = \frac{\text{d}}{\text{d}t}F(t) = \lim_{\delta\rightarrow0}\frac{1}{\delta}\text{Pr}(t\leqslant T < t + \delta)
$$

### 各方程之間的關系 

$$
\begin{aligned}
f(t) & = \frac{\text{d}}{\text{d}t}F(t)  = \frac{\text{d}}{\text{d}t}\{ 1-S(t) \} = - \frac{\text{d}}{\text{d}t}S(t) \\ 
S(t) & = 1 - F(t)  = 1 - \int_0^t f(u)\text{d}u = \int_t^\infty f(u)\text{d}u \\
h(t) & = \lim_{\delta\rightarrow0}\frac{1}{\delta}\text{Pr}(t \leqslant T < t+ \delta | T \geqslant t) \\ 
     & = \lim_{\delta\rightarrow0}\frac{1}{\delta}\frac{\text{Pr}(t \leqslant T < t+ \delta, T \geqslant t)}{\text{Pr}(T \geqslant t)} (\text{Bayes' Theroem}) \\ 
     & = \lim_{\delta\rightarrow0}\frac{1}{\delta}\frac{\text{Pr}(t \leqslant T < t+ \delta)}{\text{Pr}(T \geqslant t)} \\ 
     & = \frac{f(t)}{S(t)} \\
h(t) & = \frac{f(t)}{S(t)} = \frac{\frac{\text{d}}{\text{d}t}F(t)}{S(t)} = \frac{- \frac{\text{d}}{\text{d}t}S(t)}{S(t)} = - \frac{\text{d}}{\text{d}t}\text{log}[S(t)] \\
\end{aligned}
$$

**推導** $S(t), H(t)$ 之間的關系: 

$$
\begin{aligned}
\because h(t) & = - \frac{\text{d}}{\text{d}t}\text{log}[S(t)] \\
\text{intergrate both} & \text{ sides over the range from 0 to }t: \\
\int_0^th(u)\text{d}u & = - \int_0^t\frac{\text{d}}{\text{d}u}\text{log}[S(t)]\text{d}u \\
                      & = -[\text{log } S(u)]_{u = 0}^{u = t} \\ 
                      & = -[\text{log } S(t) - \text{log } S(0)] \\ 
                      & = -\text{log }S(t) \\ 
\Rightarrow S(t)      & = \exp\{ - \int_0^th(u)\text{d}u\} = \exp\{ -H(t) \}
\end{aligned}
$$


## 生存時間的參數分布

### 指數分布 

適用於生存時間最簡單的分布是指數分布 (exponentiential distribution)。指數分布默認危險率 (hazard rate，$\lambda$) 不隨時間變化。在指數分布中，危險度方程，生存方程和概率密度方程分別是:

$$
\begin{aligned}
h(t) & = \lambda, \\ 
S(t) & = e^{-\lambda t} \\
f(t) & = h(t)S(t) \\
     & = \lambda e^{-\lambda t}
\end{aligned}
(\#eq:survival01-11)
$$

### Weibull 分布

指數分布的前提 -- 事件發生率相同的假設過於強硬，許多真實數據，都不能滿足這個前提條件。另一個比指數分布靈活的分布是 Weibull 分布。它包含兩個參數，其危險度方程，生存方程和概率密度方程分別是: 

$$
\begin{aligned}
h(t) & = \kappa\lambda t^{\kappa - 1}  \\ 
S(t) & = \exp(-\lambda t^\kappa) \\
f(t) & = \kappa \lambda t^{\kappa - 1} \exp(-\lambda t^\kappa)
\end{aligned}
(\#eq:survival01-12)
$$



## 極大似然法估計



# 非參數法分析生存數據

# 生存數據中的回歸模型

# Cox 比例風險模型 

# 模型檢查

# 競爭危險度 competing risk

# 其他手段

# 時間依賴變量 

# 時間事件數據的高級分析法