
推斷是十分具有挑戰性的一個章節，我們在此做個簡單的複習和總結，用一些常見的問題來結束本章。

### 快速複習

對於收集到的**樣本數據 data**，我們需要提出一個所謂的“科學問題 scientific question”。

爲了回答這個“科學問題”，我們會設想，並提出一個合適的 **統計學模型 statistical model**，確認提出的統計學模型中的**參數 parameters**。通過樣本數據的信息對參數進行**估計 estimation**，或者進行**假設檢驗 hypothesis tests**。

統計學模型具有自己的概率分佈，通過相應的參數，和模型的分佈可以解釋觀察數據的分佈，並且利用這些信息進行我們需要的推斷。同時，我們還需要利用觀察數據對我們提出的模型是否擬合數據做出合適的**診斷**。

估計和假設檢驗，是以**似然方程**爲基礎的。通常我們會利用便於計算的對數似然(比)，進行假設檢驗。

獲得似然方程以後，我們可以用對數似然比，進一步進行推斷：

1. 確認最佳估計 $MLE$，和它的方差 (標準誤)；
2. 計算參數的點估計量，和信賴區間；
3. 爲感興趣的參數實施假設檢驗。

### 試爲下面的醫學研究問題提出合適的統計學模型

1. 在一所醫院收集了 80 名患者的血壓和體重的數據，醫生想要分析血壓 (bp) 跟體重 (weight) 之間是否有相關性。

答： 用簡單線性迴歸模型。(r.v. = random variable)

$$
Y \text{ r.v. for bp } Y_j | \text{weight}_j \stackrel{i}{\sim} N(\alpha + \beta \text{weight}, \sigma^2), j = 1,2,\cdots,80; \text{H}_0: \beta=0
$$

2. 爲了調查某市青光眼的患病率 (prevalence)，從一般人羣中隨機抽取了 100 人進行眼部檢查。

答：用二項分佈模型。

$$
K \text{ r.v. for number of people found with glaucoma } \\
K \sim \text{Bin}(100, \pi); \text{ Estimate } \pi \text{ with CI.}
$$


3. 另一個醫生拿到了 2. 的數據，打算分析這100人中青光眼的患病與否是否和血壓相關。

答：用邏輯迴歸模型。 $\text{logit}\pi = \text{log}\frac{\pi}{1-\pi}$

$$
K_i | bp_i \sim \text{Bin}(100, \pi_i), \text{logit}(\pi_i) = \alpha + \beta bp_i; \text{H}_0: \beta = 0
$$


4. 有好事者打算調查 25 名研究對象的血清膽固醇水平是否在實驗前後 (實驗時間3個月) 發生有意義的改變。

答：正態分佈模型，單樣本 $t$ 檢驗。

$$
D \text{ r.v. for cholesterol change; } D_j \stackrel{i.i.d}{\sim} N(\delta, \sigma^2), j= 1,\cdots,25; \text{H}_0: \delta = 0\\
\text{Where } D_j = \text{chol}_{j,3m} - \text{chol}_{j,entry}
$$

5. 前一題的好事者，打算進一步分析膽固醇水平的變化在某些進行特殊飲食的觀察對象中是否更加顯著。

答：簡單線性迴歸模型。

$$
D_j | \text{diet}_j \stackrel{i}{\sim} N(\alpha + \beta \text{diet}_j, \sigma^2), j=1,\cdots,25; \text{H}_0: \beta = 0
$$

6. 某降壓藥物已知能有效地降低高血壓患者的血壓。某項實驗將收集來的高血壓患者分成 6 個小組，每組給予的藥物劑量不同，最低 1 毫克每次，最高 6 毫克每次，每組相差 1 毫克劑量。研究者希望通過實驗確定該藥物的降壓效果是否在某個劑量時達到最大，如果沒有，是否降壓藥物的效果隨着劑量增加而增加。

$$
\begin{aligned}
& bp_j | \text{dose}_j \stackrel{\cdot}{\sim} N(\alpha + \beta\text{dose}_j + \gamma\text{dose}^2_j, \sigma^2), j=1,\cdots,n;\\
\text{1) test } & \text{ H}_0: \gamma=0; \text{ if do not reject, then do next test } \\
& bp_j | \text{dose}_j \stackrel{\cdot}{\sim} N(\alpha + \beta\text{dose}_j, \sigma^2)
\text{2) test } & \text{ H}_0: \beta=0
\end{aligned}
$$

### 醫生來找統計學家問問題

7. 一個**“臨牀醫生”**來找你問了這樣的一個常見的問題：當我們使用 $t$ 檢驗的時候，爲什麼前提假設是數據服從 **正態分佈**? 而不使用**服從 $t$ 分佈** 這樣的前提條件，因爲我們實施該檢驗的時候明明就在用 $t$ 分佈？

答：我們從未假定**觀察數據服從 $t$ 分佈**，我們假定的前提是檢驗統計量，也就是樣本均值和標準誤服從 $t$ 分佈。因爲我們不知道收集獲得的數據來自的人羣的方差是多少，需要使用樣本數據對方差也進行估計的時候，不得已而必須使用 $t$ 分佈來獲得估計的樣本均值的標準誤差，用於計算信賴區間和實施假設檢驗。

8. 還是那個有好奇心的**“臨牀醫生”**又來問一個弱智問題：當我們使用正態分佈近似法對一個服從二項分佈的比例的單樣本檢驗的時候，我們把計算的檢驗統計量拿去跟正態分佈的特徵值作比較。然而，不用正態分佈近似，直接對連續型變量實施單樣本 $t$ 檢驗的時候卻把計算的檢驗統計量拿去和 $t$ 分佈的特徵值作比較，這是爲什麼？

答：對連續型變量實施單樣本 $t$ 檢驗的時候，我們需要用樣本數據同時估計均值和標準誤。但是對於二項分佈的數據來說，它的樣本比例的標準誤是總體比例的一個方程，所以只要用樣本比例估計總體比例以後，總體的標準誤就已經可以知道，不必再作估計。所以，二項分佈的正態近似法就真的使用標準正態分佈的特徵值，但是連續型變量的總體標準誤同時被估計，它的不確定性也要考慮進來，只能使用 $t$ 分佈。


9. 某**“臨牀醫生”**假裝很熱心想學習統計跑來問問題：該醫生實施的臨牀試驗，比較病例和對照之間某指標是否不同。但是，病例組看上去的年齡似乎比對照組要高一些，該醫生記得自己統計課上聽老師說過混雜因素的知識。所以他跑回家自己實施了一下病例組和對照組之間年齡是否有差別的 $t$ 檢驗，結果顯示病例組對照組的年齡沒有顯著性差異。所以他認爲可以從線性模型中去掉年齡這一變量。但是身爲統計學家的你堅持必須要保留年齡在模型裏。所以醫生問你是否關心年齡有差別所以才堅持要調整年齡。你的回答是“對不起大哥，我對病例對照之間的年齡差是否有統計學意義完全沒有興趣。”醫生更加困惑了。$\text{variable}_i = \alpha + \beta\text{patient}_i + \gamma\text{age}_i + \varepsilon_i$

答：年齡是否會混雜了病人分組和指標之間的關係，**不是通過比較兩組來自的人羣的年齡是否有差別來判斷的**。如果**樣本的年齡有差別**，就很有可能會對你想要分析的關係造成混淆。因爲你進行的年齡均值是否有差異的 $t$ 檢驗，比較的並不是樣本年齡的差別，而是用樣本估計來自的人羣的年齡之間的比較。
