

本章的練習，我們主要使用四個計算似然的命令來加深我們對似然這一概念的理解：

- `blik`: binomial likelihood （二項分佈的似然）
- `plik`: Poisson likelihood （泊松分佈的似然）
- `bloglik`: binomial log-likelihood （二項分佈的對數似然）
- `ploglik`: Poisson log-likelihood （泊松分佈的對數似然）


## Q1 二項分佈似然的圖形


使用 `blik` 命令來繪製二項分佈參數 $\pi$ 在不同情況下的似然函數圖： 


1. 

```{r binomL4, fig.asp=.7, fig.width=6,  fig.cap='Binomial Likelihood ratio', fig.align='center', out.width='90%', cache=TRUE}
x <- seq(0,1,by=0.001)
y <- (x^4)*((1-x)^6) / (0.4^4*0.6^6)
plot(x, y, type = "l", ylab = "LR(\U03C0)", xlab = "\U03C0")
abline(v=0.4, lty=2)
abline(h=1.0, lty=2)
abline(h=0.1466, lty=2, lwd = 2, col = "red")
```

```{r binomL40, fig.asp=.7, fig.width=6,  fig.cap='Binomial Likelihood', fig.align='center', out.width='90%', cache=TRUE}
x <- seq(0,1,by=0.001)
y <- (x^40)*((1-x)^60) / (0.4^40*0.6^60)
plot(x, y, type = "l", ylab = "LR(\U03C0)", xlab = "\U03C0")
abline(h=1.0, lty=2)
abline(v=0.4, lty=2)
abline(h=0.1466, lty=2, lwd = 2, col = "red")

```




```{r binomL400, fig.asp=.7, fig.width=6,  fig.cap='Binomial Likelihood', fig.align='center', out.width='90%', cache=TRUE}
x <- seq(0,1,by=0.001)
y <- (x^400)*((1-x)^600) / (0.4^400*0.6^600)
plot(x, y, type = "l", ylab = "LR(\U03C0)", xlab = "\U03C0")
abline(v=0.4, lty=2)
abline(h=1.0, lty=2)
abline(h=0.1466, lty=2, lwd = 2, col = "red")

```