
### 練習題 exercise 8.1 

假設我們使用下面這樣的Cox擴展模型來研究關於肺部臟器移植與否的時間依存變量和死亡之間的關係：

$$
h(t|x) = h_0(t)\text{exp}(\beta x(t))
$$

如果患者$r$在時間點5時進行了肺部的臟器移植，患者$s$則整個隨訪中都沒有接受臟器移植。請試着計算下列時間點時兩名患者之間的死亡風險度比：

(1) 時間點4；
(2) 時間點6。


（我們假設兩名患者在這兩個時間點時都依然還是存活着的）

### 解答

(1) 在時間點4時，兩名患者都沒有接受臟器移植，此時，他們的死亡風險度都是基線風險：$h(t|x) = h_0(t)$，故在時間點4時，他們的死亡風險度比是 1。
(2) 在時間點6時，患者$r$的風險度是：$h(t|x) = h_0(t)\text{exp}(\beta)$。患者 $s$ 的風險度是：$h(t|x) = h_0(t)$。所以，在時間點6時，患者$r,s$之間的死亡風險度比就是 $\text{exp}(\beta)$。

-------------

在Cox擴展模型下，加入了時間依存變量之後，模型所使用的偏似然(partial likelihood)是：

$$
L_p = \prod_j\frac{\text{exp}\beta^Tx_{i_j}(t_j)}{\sum_{k\in R_j}\text{exp}\beta^Tx_k(t_j)}
$$

在這個偏似然中，我們實際比較了在時間點 $t_j$ 時，實際觀察到的有發生事件的對象的預測變量 $x_{i_j}(t_j)$ 的風險度，和在時間點 $t_j$ 時仍然存在在觀察數據集合(the risk set at time $t_j$)中的個體(假設人數爲 $R_j$)的預測變量 $x_k(t_j)$的風險度。這裏需要特別指出的是，當使用這個偏似然作爲估計的工具時，我們需要知道所有觀察對象，當他/她/它仍然處在觀察數據集合中的時候，每當有新的事件發生被觀察到，那每個新時間發生的時間點，模型中所有預測變量的最新值（包括時間依存變量本身）。這個假設對於二分類（是否接受移植臟器）時間依存變量來說不難，但是當時間依存變量是連續型變量的時候，要知道每一次事件發生時所有存在在觀察數據集合中每一名觀察對象的觀察值（例如血壓），是無法辦到的。這是因爲血壓值其實是時時刻刻都處在變化中的，但是我們實際對患者隨訪測量血壓時，都只能獲得患者在某個時間點上的血壓值。因此，這個Cox擴展模型中如果存在連續性的時間依存變量，那麼模型的另一個隱含的前提條件是，假設患者或者實驗對象的連續性時間依存變量在前後兩次測量值獲得的間隔期內是保持不變的（assuming that it stays constant from the last time it has been observed）。

