## 本章概要

- 學會如何有計劃，步驟清晰地對生存數據進行比例風險模型的建模，包括如何恰當地選擇放入模型中的解釋變量，和它們的形式。
- 能進行模型與模型之間比較的似然比檢驗 (likelihood ratio test)，並解釋該檢驗的結果。
- 掌握各種不同的檢驗“比例風險假設”的方法，特別是使用 Schoenfeld 殘差圖的方法，來觀察暴露變量對風險函數的作用是否隨着時間發生改變。
- 使用 Martingale 殘差圖和偏差殘差圖 (deviance residuals) 評價模型擬合程度 (model fitting)。
- 使用 Martingale 殘差來輔助判斷某個連續型變量合適放入模型的數學函數形式。
- 會使用 R/Stata 獲取風險比例模型建立之後的各種不同殘差。


## 生存分析策略

在分析生存數據的時候同樣一個數據集，你其實可以建立許多不同的（比例風險）模型，那麼解釋變量的選擇就顯得很重要，究竟你應該在模型中放入哪些變量才算是合適呢？其實這要根據研究的目的和分析時的上下文而有相應的調整。例如說，

1. 分析目的只是着重看某個暴露變量對生存/死亡風險的影響。也就是我們說到底只關心一個特殊的暴露變量。但是我們希望這個模型可以調整其他可能存在的混雜因子，從而獲得該暴露變量真實的效果 (true effect)。
2. 分析目的是爲了瞭解測量獲得的一組暴露變量數據集與研究對象生存時間之間的關係。其中可能着重關心該變量集合中的一個或者幾個對生存的影響，或者最終決定哪個/些是對生存概率的影響較大的。
3. 分析目的是爲了建立一個預測生存概率的模型。研究者可能希望通過在模型中加入儘可能多的變量以提高模型預測能力的精確度。這樣新的研究對象的生存概率就可以通過建立好的模型直接套用該對象具有的解釋變量計算。

在廣義線性回歸模型部分的分析策略章節 (Chapter \@ref(GLM-strategy)) 詳細討論過一般分析數據時建立回歸模型的策略。該策略也可以用於指導生存分析模型建立的過程。


### 關於似然比檢驗 A note on likelihood ratio tests

似然比檢驗法同樣可以用於比較兩個具有嵌套結構的Cox比例風險模型。這裏用兩個簡單的解釋變量 $X_1, X_2$ 來示範似然比檢驗的過程。

假設，我們主要對 $X_1$ 和生存概率之間的關係感興趣，而 $X_2$ 作爲唯一的混雜因子變量。那麼我們可以分別建立兩個生存分析模型，一個有 $X_2$，另一個不包含 $X_2$。如果這兩個模型給出的變量 $X_1$ 的風險度比估計值發生了較爲顯著的變化，那麼可以考慮模型中要保留 $X_2$ 作爲重要的混雜因子變量。如果包含了 $X_2$ 的回歸模型給出的 $X_1$ 的風險度比和不包含 $X_2$ 的回歸模型給出的風險度比估計值差別可以忽略不計，且可以認爲 $X_2$ 不是重要的獨立解釋變量，那麼我們決定把它從模型中移出也沒有太大的問題。如果數據集中有許多個潛在的混雜因子變量，那麼我們可以對每一個重複上述相同的步驟。最主要的是，要記住，對於混雜是否有意義，並沒有正式的檢驗方法。

如果 Model 1 包含的變量少於 Model 2 (Model 1 is nested within Model 2)，那麼似然比檢驗的檢驗統計量是

$$
-2 (\ell_{\text{Model 1}} - \ell_{\text{Model 2}}) \sim \chi^2_p
$$

其中，

- $\ell$ 是表示兩個模型的對數似然 (log-likelihood)
- $p$ 是兩個模型中相差的預測變量的個數 (the difference in the number of parameters in the two models)。
- 另外，這裏模型中還允許考慮變量之間的交互作用項或者是給連續型變量進行數學形式的調整（增加二次項甚至是三次，多次項）。

要注意的是，似然比檢驗顯然無法用於比較一個全參數模型（如 Weibull Model）和一個半參數模型（如 Cox 比例風險模型）。這是因爲他們之間不存在嵌套結構關係。

## 針對不同的研究設計不同的分析策略

分析策略需要根據不同的研究設計量身定製，下面我們着重討論兩種主要類型的生存數據研究設計 -- 隨機對照臨牀試驗型 (randomised controlled trial, RCT)，和觀察性研究 (observational study)。

### 針對隨機對照臨牀試驗 RCT

思考一個有治療組和對照組的隨機對照臨牀試驗，例如目前位置我們一直使用的白血病患者數據。由於隨機分配的法則，使我們認爲除了治療本身的暴露，不存在其餘的組間差異。那麼我們認爲一個比較合理的分析策略應該可以歸納如下：

1. 先總結 (summarize) 兩個不同治療組患者（實驗對象）的各方面數據：人數 (n)，事件數 (n of events)，刪失值數 (n of censors)，各組的生存時間中位數 (median of survival time)，及刪失對象的觀察時間長度的中位數 (median of censoring time)。
2. 使用非參數法，繪製兩個治療組的 Kaplan-Meier 生存曲線。
3. 再使用非參數法，特別是 log-rank 檢驗法對零假設：兩組生存曲線的模式無不同 (the survivor curves in the two treatment groups are the same)。
4. 使用繪圖法，初步（非正式地 informally）判斷比例風險假設是否成立，或者可能被違反
5. 如果可以認爲比例風險假設得到滿足，那麼，接下來可以進一步使用比例風險模型，或者你可能喜歡的指數模型，Weibull 模型等其他你認爲可能合適的模型來建立回歸模型，通過你最喜歡的R分析並計算獲得相應的風險度比 (hazard ratio) 及其信賴區間的估計。
6. 最後，對該模型的風險比例假設進行正式的統計學評估（將在接下來的章節中詳述）。可以是使用治療組 $\times$ 時間 這樣一個交互項看其回歸係數是否顯著不等於零，也可以是使用 Schoenfeld 殘差分析圖，也可以是把觀察時間進一步分割成幾個時間段之後分別估計每個時間段內的風險度比是否存在較大差異。



### 針對觀察型研究 observational studies

在觀察型研究獲得的生存數據中，分析者通常需要考慮多個不同類型的暴露（解釋變量）。同樣地，變量的選擇也要基於分析的目的和研究本身的設計來決定。同樣是觀察型研究，不同研究者的研究興趣各不相同。

1. 某些觀察型研究的主要目的是估計某一個特別感興趣的暴露變量對生存概率的影響，但同時希望把可能對暴露和結果之間的關係造成混雜影響的因素都儘可能的控制住。
2. 某些觀察型研究的主要目的是分析某幾個特定的暴露變量和生存概率之間的關係，同時希望瞭解哪些（個）變量可能對生存概率（時間）有最大的作用。
3. 某些觀察型研究的主要目的是通過收集到的所有可能的解釋變量建立符合該實驗目的的生存概率預測模型，用於對患者/實驗對象的實際生存時間或者某個時間點的生存概率的估計。

先看第一種情況下的分析策略：

#### 分析某個暴露變量對生存的影響 estimating an exposure effect





### 模型檢查的要點

1. 總體模型對數據的擬合情況是否合理？
2. 是否有極端數據，影響了模型的擬合結果？
3. 解釋變量，特別是連續型變量是否以正確的形式進入了模型？

## 比例風險假設的檢查 check the proportional hazard assumtion


主要有三板斧：

1. 用非參數法繪製簡單的生存曲線圖；
2. 用統計檢驗，判斷一個解釋變量對風險的影響是否和時間產生了交互作用；
3. 殘差繪圖法。

非參數法繪製生存曲線圖詳見第 \@ref(nonparametric) 章節部分。

### 比例風險檢查的統計檢驗法

在滿足比例風險前提下，某個解釋變量估計的風險比 (hazard ratio) 不會隨著時間變化而變化，根據這個特點，我們可以認為，如果某些解釋變量在追踪開始時對風險影響很強，在之後的追踪中，和風險之間的關係變弱的話，(或者反過來)，那麼風險比的這一變化就違背了比例風險這一前提。最簡單的，我們可以在模型中加入該變量和時間的相乘項 (交互作用項)：

$$
h(t|x) = h_0(t)\exp\{ \beta x + \gamma (x\times t)\}
$$

聰明的你一下子就明白了，接下來只要檢驗 $H_0: \gamma = 0$:

$$
\frac{\hat\gamma}{SE(\hat\gamma)} \sim N(0,1)
$$


### 用 Schoenfeld 殘差繪圖

另外一種視覺化檢查比例風險假設的方法是使用 **Schoenfeld 殘差**：

The residual compares the observed values of the explanatory variable for the case at a given envent time with the weighted average of the explanatory variable in the risk set. The residuals should not show any dependence on time -- this would indicate that the proportional hazards assumptions is not met.

It is actually more convenient to use the "scaled Schoenfeld residuals". **The Scaled Schoenfeld residuals have a mean which is the true log hazard ratio** under the proportional hazards assumption, and the average values of the scaled Schoenfeld residuals over time can be interpreted as the time-varying log-hazard ratio. A plot of the scaled Schoenfeld residuals over time is therefore directly informative about how the log hazard ratio changes overtime. It is useful to show a smoothed average curve on these plots.

## 評價模型擬合的其他有趣方法

### Martingale 殘差-assessing the functional form of continuous variables

Martingale (馬丁哥?) 殘差圖可以用來檢驗，比較連續型變量在模型中是否被正確擬合，因為有時候連續型變量需要增加該連續型變量的二次項或者多次項，也可能要用對數項之類的變形之後，才能完全把其與生存數據之間的關係完全解釋清楚。

A Martingale is a residual for an event process -- it is the difference between what happened to a person (whether they had the event or not) and what is predicted to happen to a person under the model that has been fitted. The Martingale residual for individual i is:


$$
r_{M_i} = \delta_i - \hat H_0(t_i)\exp(\hat\beta x_i)
$$

Where, $\delta_i$ is the indicator of whether the individual $i$ had the event (1) or was censored (0), $t_i$ is the event or censoring time, $x_i$ denotes the explanatory variable (or more generally a vector of explanatory variables), and $\hat H_0(t_i)$ is the estimated baseline cumulative hazard at time $t_i$. If the model is correct then the Martingale residuals should sum to 0.


### Deviance 偏差殘差 -- identifying individuals for whom the model does not provide a good fit

偏差殘差是馬丁哥殘差的轉換值，它的定義是:

$$
r_{D_i} = \text{sign}(r_{M_i})[-2\{r_{M_i} + \delta_i\log(\delta_i - r_{M_i})\}]^{\frac{1}{2}}
$$

偏差殘差通過上面的公式，把模型給出的馬丁哥殘差轉換成為一組理論上應該是平均分佈在零兩側的數據。如果某個個體的偏差殘差過大，偏離0太遠的話，提示該模型對該個體數據擬合不佳。具體來說，如果偏差殘差遠大於零，提示的是該個體遠在模型預測他/她/它會發生事件的時間之前就已經發生了事件；相反如果偏差殘差遠小於零，則提示該個體在模型預測發生事件的時間點之後很晚才真的發生事件。

把偏差殘差作 Y 軸，危險度評分 (risk score $=\beta^Tx$)，作 x 軸繪圖可以用於分析模型是否針對某些危險度高的人給出較高的偏差殘差，從而可以判斷模型是否合理。當判斷某些人可能偏差殘差過大，或者過小，之後要做的決定才是殘忍的，你要從數據中刪除這些個體？還是分析這些個體到底有哪些與眾不同的特質？或者是要重新對模型的各項解釋變量的形式進行修正？

**在進行生存分析的時候，請一定要一邊構建模型，一邊用這些殘差來綜合分析模型的合理性。**
