## 本章概要

- 學會寫下 Cox 比例風險方程的數學表達式
- 能夠解釋 Cox 比例風險模型是怎樣通過半似然的方法獲取 MLE 的，他們又是怎樣獲得估計風險度比 (hazard ratio)，和它的標準誤，p 值，以及信賴區間的
- 比較 Cox 比例風險模型和全參數模型 (fully parametric models)，及非參數方法 (non-parametric methods)
- 能夠解釋各種不同類型的（連續型，二進制型，或者多變量型）解釋（暴露）變量在 Cox 比例風險模型中獲得的參數估計的涵義
- 學會使用統計軟件繪製的圖形方法來分析並解釋比例風險度的假設條件是否得到滿足
- 能夠在 R 等統計包中準確地運行需要的 Cox 比例風險模型，並且會用這些統計包輔助進行模型性能評測

## 初步介紹 Cox 比例風險模型

如果可以認爲暴露（解釋）變量對風險度的作用是成比例的 (act proportionally on the hazard)，那麼對某個觀察對象來說，他/她/它的解釋變量如果用向量 $\mathbf{X} = x$ 來表示的話，他/她/它的風險度方程和基線風險度 (baseline hazard) 之間的關係可以描述爲：

$$
h(t|x) = h_0(t)e^{\beta^Tx}
$$

其中，$h_0(t)$ 就是被比較的基線組成員(baseline individual)的風險度函數 (hazard function)，在 Weibull 模型或者指數模型中，這個基線風險 (baseline hazard) 是需要被模型根據數據來進行參數估計的 (parameterized)。但是，1972年，神一樣的人物 Cox [@Cox1972b] 提出，其實我們不需要對這個基線風險進行估計，可以忽略它在模型中的存在。正因為如此，這個模型被冠以發明者的名字 Cox proportional hazards model。因為此模型不對基線風險進行任何估計，但是對預測變量對於風險的效果 (effect of the explanatory variable) 用模型中的 $\beta$ 進行參數估計，所以，它又被稱爲是半參數化模型 (semi-parametric model)。

下面的討論，我們保持和之前的章節使用相同的數學標記法。

- $i = 1, \dots, n$ 標記實驗對象的個體編
- $x_i$ 表示她/他/它的解釋型變量（大多數情況下它是包含了多個變量的向量）
- $t_i$ 表示生存時間（刪失時間）
- $\delta_i$ 則是指示是使用生存時間，或者刪失時間的指示變量 (indicator)

那麼用這些標記法描述的 Cox 比例風險模型下的似然是：

$$
L= \prod_{i=1}^n\{ h_0(t)e^{\beta^Tx_i}\exp(-\int_0^{t_i} h_0(u)e^{\beta^Tx_i}du) \}^{\delta_i}\{ \exp(-\int_0^{t_i} h_0(u)e^{\beta^Tx_i}du) \}^{1-\delta_i}
$$

是無法估計的，此時要用到偏似然法 (partial likelihood)，

## 偏似然法 (partial likelihood)

思考這樣一個問題，在一組用 $R_j$ 標記的患者集合中，當我們已知它們同時都存活到了時間點 $t_j$，且沒有發生刪失，那麼這組患者中的某個 $i_j$，他/她有一個解釋變量 $x_i$，他在這個時間點恰好發生事件的條件概率該怎麼計算：

$$
\frac{h_0(t_j)\exp(\beta^Tx_{i_j})}{\sum_{k\in R_j}h_0(t_j)\exp(\beta^Tx_k)} = \frac{\exp(\beta^Tx_{i_j})}{\sum_{k\in R_j}\exp(\beta^Tx_k)}
$$

是的，你沒有看錯，基線風險被完美的消除掉了，這就是它不需要被參數估計的原因。此時，我們用偏似然來計算這樣的模型似然：

$$
L_p = \prod_j \frac{\exp(\beta^Tx_{i_j})}{\sum_{k\in R_j}\exp(\beta^Tx_k)}
$$



模型的假設：

$$
h(t|x) = h_0(t)e^{\beta^Tx}
$$

1. Proportional hazards assumption - explanatory variables act **multiplicatively** on the hazard and their effect on the hazard does not change over time;
2. We have correctly specified the form for how continuous explanatory variables act on the hazard;
3. We have included all relevant explanatory variables including possbile interactions;
4. Uninformative censoring;
5. Individuals are independent.

## 該用半參數模型還是用全參數模型

- 如果說指數模型或者 Weibull 模型是合理的，通常此時用 Cox 半參數模型也是合理的；
- 如果指數模型或者 Weibull 模型都是合理的，那麼 Cox 半參數模型給出的估計，其實不會和指數模型或者 Weibull 模型相差甚遠。指數模型或者 Weibull 模型可能給出的估計會相對更精確 (更小的標準誤)，但是實際應用中這種更加精確的程度其實十分有限；
- 另外，使用指數模型或者 Weibull 模型，重要的基線風險是否被模型擬合正確將會是關鍵 (baseline hazard mis-specified?)，但是使用 Cox 模型，就可以避免這個假設，忽略掉基線風險；
- 2002 年，[@Royston2002] 提出第三種生存數據模型，"flexible parametric survival models"，結合了參數和半參數模型的長處，正在變得流行起來。在這個新型靈活參數生存模型中，使用了三次方程平滑曲線 (cubic splines modelled smoothly) 擬合對數基線累積風險 (log cumulative baseline hazard)。
