## 本章概要

1. 理解回歸模型對於生存數據的重要性
2. 掌握如何定義不同生存分佈的回歸模型（包括指數分佈模型和 Weibull 分佈模型），並在模型中加入解釋變量。
3. 理解這些不同生存分佈模型之間的異同。
4. 能夠用數學表達式描述生存數據的參數模型（parametric models），包括在模型中加入解釋型變量，並考慮刪失值。
5. 用極大似然法 (maximum likelihood estimation)估計生存數據參數模型中的各個參數。
6. 掌握使用R來建立生存數據參數模型的方法，能看懂軟件報告的結果並作出正確的解釋。

## 使用參數模型分析生存數據的目的

非參數法章節 (Chapter \@ref(nonparametric)) 討論的那些分析生存數據的基礎方法已經被廣泛接受並應用於比較兩組甚至是多組之間的生存函數（曲線），或風險度的異同。但是這些非參數方法的缺點也很明顯：

1. 無法把連續型變量作爲暴露變量。唯一的解決方法是認爲地把連續型變量給轉換成分類型變量，然後比較落入不同區段內的對象和落入其他區段內對象之間的生存函數/風險度。
2. 如果我們除了有需要比較的主要暴露還需要同時考慮混雜因子（或者互相調整），解決方法是把實驗對象人爲地分組，或者是把對象根據多個分類型暴露變量的組合進行組內的比較。這種方法最終導致劃分地越來越細的那些小組中可以用於分析的對象數據越來越少，最終不可能使分析獲得有意義的結果或解釋。
3. 一般來說，我們希望同時在分析中把多個暴露變量都考慮進來，而且這些暴露變量可以同時包括連續型，二進制型，還有多分類型的變量。這樣的話使用非參數方法逐一分析變得不太有實際操作意義。


本章我們介紹用參數型回歸模型的方法來分析生存數據。這裏所說的回歸模型 (regression modelling) 其實相當類似我們學習過的簡單線性回歸模型，該模型是分析連續型結果變量和多個不同類型解釋變量；或也可以類比與廣義線性回歸中的邏輯回歸模型，即分析一個二進制結果變量和多個不同類型的解釋變量時所構建的回歸模型。之所以我們在這需要強調生存數據的**參數**模型 (parametric models)，是由於本章節討論的生存回歸模型都假定了生存時間會服從某一個特殊形狀的分佈，這些特殊形狀的生存時間分佈本身由一個或者多個不同的參數來定義。與此形成對比的是非參數分析法中，並沒有使用任何定義生存時間分佈的參數。

## 生存數據的似然方程

我們來回憶一下在生存分析第一章節 (Chapter \@ref(surv-intro)) 就介紹過的生存數據似然的數學表達式。

$$
L = \prod_i f(t_i)^{\delta_i}S(t_i)^{1-\delta_i}
$$

- $i = 1, \cdots, n$ 是患者的編號
- $t_i$ 是 $i$ 號患者的生存/刪失時間
- $\delta_i$ 是表示 $i$ 號患者的生存/刪失狀態的啞變量 (indicator/dummy variable)
- $f(t_i)$ 是生存數據(死亡/事件發生患者的)的概率密度方程 probablity density function
- $S(t_i)$ 是生存數據(生存/刪失患者的)生存概率方程 survivor function

## 如何加入解釋變量

先考慮簡單的情況，一個二進制變量 (binary explanatory variable $X = 0 \text{ or } 1$)，可以是治療組對照組等簡單的二分類變量。可以認爲其中一組 $(X=1)$ 患者在時間點 $t$ 時的風險度 (hazard) $h_1(t)$ 和另一個被看作是對照的基準組 (baseline group $X=0$) 的風險度 $h_0(t)$ 之間的關系是相乘的話:

$$
h_1(t) = \psi h_0 (t)
$$


那麼這裏的 $\psi$ 就是我們關心的參數。注意這裏兩組患者的風險度，等式左右兩邊都必須是大於零的，因此 $psi$ 的取值要被限制在 $>0$ 範圍。所以，我們常常直接寫成:

$$
h_1(t) = e^\beta h_0(t)
$$

那麼參數 $\beta$ 就沒有了取值的限制。這就是大名鼎鼎的**比例風險度模型 (proportional hazard model)**。$e^\beta$ 就是風險度比 (Hazard ratio):

$$
\frac{h_1(t)}{h_0(t)} = e^\beta
$$

$\beta$ 是對數風險度比 (log-hazard ratio)，這個風險度比，不隨着時間推進而變化。所以在生存分析的參數模型中，**前提條件--比例風險度 (proportional hazard assumption)，是必須被滿足的假設**。當你認爲治療組對照組之間的療效差 (treatment effect) 會隨着時間發生變化的話，這個前提條件就被違反了。用於生存分析的這些參數模型，都需要比例風險度這一重要的前提條件被滿足。

## 指數模型 exponential model

指數模型是最簡單的生存時間分析參數模型。

**風險度方程 hazard function:**

$$
h(t) = \lim_{\delta\rightarrow0}\frac{1}{\delta}\text{Pr}(t\leqslant T <t + \delta | T>t) = \lambda
$$

**生存概率方程 survivor function:**

$$
S(t) = \text{Pr}(T>t) = \exp\{-\lambda t\}
$$

**概率密度方程 probability density function:**

$$
f(t) = \lambda \exp\{ - \lambda t\}
$$

在指數分布時，風險度本身 (而不是比例) 保持不變。這也意味着事件發生的率 (rate of the event) 不隨時間發生變化 (constant over time)。

在指數分布模型下加入解釋變量:

$$
\left\{
  \begin{array}{ll}
  h(t;0) = \lambda & X=0  \\
  h(t;1) = \lambda e^\beta & X=1
  \end{array}
\right.
$$

這個聯立方程等價於:

$$
h(t;x) = \lambda e^{\beta x}
$$


類似地，風險度方程已知了的話，概率密度方程和生存方程可以寫作:

$$
f(t;x) = \lambda e^{\beta x} \exp({-\lambda t^{\beta x}}); \\
S(t;x) = \exp(-\lambda t^{\beta x})
$$

此時的似然方程就是

$$
L = \prod_{i = 1}^n\{\lambda e^{\beta x} \exp({-\lambda t^{\beta x}}) \}^{\delta_i}\{ \exp(-\lambda t^{\beta x})\}^{1-\delta_i}
$$


此時，似然方程中兩個參數 $\lambda, \beta$ 可以利用自己似然函數的方法分別對其中一個求導數獲得 MLE，然後用 Fisher information matrix 計算各自的標準誤，從而計算 95% 信賴區間。這裏的 $\beta$ 回歸系數，可以做是否爲零 (等價於比較 $e^\beta = 1$) 的 Wald 檢驗:

$$
\frac{\hat\beta}{SE(\hat\beta)} \sim N(0,1)
$$


```{example 11-Survival-analysis-3}
**推導$\lambda,\beta$的MLE:**
```

$$
\begin{aligned}
L & = \prod_{i = 1}^n\{\lambda e^{\beta x} \exp({-\lambda t^{\beta x}}) \}^{\delta_i}\{ \exp(-\lambda t^{\beta x})\}^{1-\delta_i} \\
  & = \prod_{i = 1}^n\{\lambda e^{\beta x}\}^{\delta_i}\exp(-\lambda t^{\beta x}) \\
\Rightarrow \ell & = \log(\lambda)\sum_{i=1}^n \delta_i + \beta \sum_{i = 1}^n(x_i\delta_i) - \lambda\sum_{i = 1}^n t_ie^{\beta x_i} \\
\text{Let} & \sum_{i = 1}^n = n_1 \text{(numer of events)}; \\
&\sum_{i=1}^n(x_i\delta_i) = n_{11} \text{(number of events in } x=1); \\
&\sum_{x_i=1}^n t_i = T_1 \text{(sum of survival/censors T in } x=1);\\
&\sum_{x_i=0}^n t_i = T_0 \text{(sum of survival/censors T in } x=0);\\
\Rightarrow \ell & =n_1 \log(\lambda) + n_{11}\beta - \lambda(T_0 + T_1e^\beta)
\end{aligned}
$$

接下來求 MLE 就等同於解下面的聯立方程組:

$$
\left\{\begin{array}{l}
\frac{\text{d}\ell}{\text{d}\lambda} = \frac{n_1}{\lambda} - (T_0 +T_1e^\beta) =0 \\
\frac{\text{d}\ell}{\text{d}\beta} = n_{11} = T_1\lambda e^\beta = 0
\end{array}
\right. \\
\hat\lambda = \frac{n_1 - n_{11}}{T_0} \\
\hat\beta = \log\frac{T_0n_{11}}{T_1(n_1 - n_{11})}
$$

## Weibull 分布

指數分布的模型只能用於擬合數據滿足事件發生率恆定不變這一十分強的假設的前提下。Weibull 分布放鬆了這個假設前提，不再要求時間發生率恆定不變，但是它的前提條件是時間發生率隨着時間的變化是單調的 (遞增或者遞減，二者只能選一)。且 Weibull 分布是指數分布的一般化形式，或者說指數分布是 Weibull 分布的特殊形式。

**Weibull 分布的風險度方程:**

$$
h(t) = \kappa \lambda t^{\kappa - 1}
$$

**生存概率方程**

$$
S(t;x) = \exp\{ -\lambda t^\kappa \}
$$

**概率密度方程**

$$
f(t) = \kappa \lambda t^{\kappa - 1}  \exp\{ -\lambda t^\kappa \}
$$

那麼加入了一個二分類解釋變量 $x$ 的 Weibull 比例風險度方程就是:

$$
h(t;x) =  \kappa \lambda t^{\kappa - 1}e^{\beta x}
$$

其生存概率方程就是:

$$
S(t;x) = \exp\{ -\lambda t^\kappa e^{\beta x}\}
$$

概率密度方程是二者的乘積，那麼所有的生存數據的似然方程就是:

$$
L = \prod_{i=1}^n \{\kappa \lambda t^{\kappa - 1}e^{\beta x}\exp\{ -\lambda t^\kappa e^{\beta x}\} \}^{\delta_i}\{ \exp\{ -\lambda t^\kappa e^{\beta x}\}\}^{1-\delta_i}
$$

但是，比較悲劇的是，在 Weibull 分布的生存模型中，沒有辦法簡單的獲得參數 $\kappa, \lambda. \beta$ 的MLE。只能使用迭代法 (iterative numerical methods are required)。

## Weibull 和 指數模型的比較

### 繪圖法

在指數分布模型中，累積風險度 cumulative hazard 是和時間呈正比的:
$$
H(t;x) = -\log S(t;x) = \lambda t e^{\beta x}
$$

在 Weibull 分布模型中，累積風險度 cumulative hazard，取了對數以後:

$$
\log H(t;x) = \log\{ -\log S(t;x) \} = \log \lambda + \kappa \log t + \beta x
$$

所以，累積風險度如果取了對數，那麼這個值和時間的對數 $\log t$ 是呈線性關系的，且當這個直線的坡度爲 1 的話 $\kappa = 1$，就說明數據符合指數模型。如果，$x$ 只是一個二分類解釋變量的話，你會看到對數累積風險度和對數時間呈現爲**兩條平行線**。

### 統計檢驗法

很簡單， Wald test:

$$
\frac{\log \hat\kappa}{SE(\log \hat\kappa)} \sim N(0,1)
$$


當然你也可以使用似然比檢驗 likelihood ratio test，因爲指數分布模型是 Weibull 分布模型在 $\kappa = 1$ 時的特殊形態，二者擬合的統計模型也會是嵌套式模型:

$$
-2(\ell_{\text{exponential}} - \ell_{\text{Weibull}}) \sim \chi_1^2
$$

服從的卡方分布的自由度是兩個模型的參數數量的差。


## 多於 1 個解釋變量的參數模型

當然可以在生存分析參數模型中加入多於一個變量，而且可以是分類型，連續型變量:

$$
h(t;x) = h_0 (t)e^{\beta^Tx}
$$

- $h_0(t)$ 是基線組的風險度 (baseline hazard);
- $\mathbf{\beta} = (\beta_1, \beta_2, \cdots, \beta_p)^T$ 是一組解釋變量的回歸系數;
- $\beta_k$ 是當保持所有其他變量不變時，解釋變量 $X_k$ 在增加/減少一個單位對應的對數風險度比 (log-hazard ratio)。


