<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>醫學統計學</title>
  <meta name="description" content="在LSHTM的學習筆記">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="醫學統計學" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="img/cover.jpg" />
  <meta property="og:description" content="在LSHTM的學習筆記" />
  <meta name="github-repo" content="winterwang/LSHTMlearningnote" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="醫學統計學" />
  
  <meta name="twitter:description" content="在LSHTM的學習筆記" />
  <meta name="twitter:image" content="img/cover.jpg" />

<meta name="author" content="王 超辰 Chaochen Wang">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="-multivariable-models.html">
<link rel="next" href="section-31.html">
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">在LSHTM的學習筆記</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>前言</a></li>
<li class="chapter" data-level="" data-path="author.html"><a href="author.html"><i class="fa fa-check"></i>我是誰</a></li>
<li class="part"><span><b>I 概率論 Probability</b></span></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> 概率論入門：定義與公理</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#section-1.1"><i class="fa fa-check"></i><b>1.1</b> 三個概率公理：</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#conditonalProb"><i class="fa fa-check"></i><b>1.2</b> 條件概率 Conditional probability</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#-independence-"><i class="fa fa-check"></i><b>1.3</b> 獨立 (independence) 的定義</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#section-1.4"><i class="fa fa-check"></i><b>1.4</b> 賭博問題</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#section-1.5"><i class="fa fa-check"></i><b>1.5</b> 賭博問題的答案</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Bayes-Definition.html"><a href="Bayes-Definition.html"><i class="fa fa-check"></i><b>2</b> Bayes 貝葉斯理論的概念</a></li>
<li class="chapter" data-level="3" data-path="-expectation-or-mean-variance.html"><a href="-expectation-or-mean-variance.html"><i class="fa fa-check"></i><b>3</b> 期望 Expectation (或均值 or mean) 和 方差 Variance</a><ul>
<li class="chapter" data-level="3.1" data-path="-expectation-or-mean-variance.html"><a href="-expectation-or-mean-variance.html#section-3.1"><i class="fa fa-check"></i><b>3.1</b> 方差的性質：</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="-bernoulli-distribution.html"><a href="-bernoulli-distribution.html"><i class="fa fa-check"></i><b>4</b> 伯努利分佈 Bernoulli distribution</a></li>
<li class="chapter" data-level="5" data-path="-binomial-distribution.html"><a href="-binomial-distribution.html"><i class="fa fa-check"></i><b>5</b> 二項分佈的概念 Binomial distribution</a><ul>
<li class="chapter" data-level="5.1" data-path="-binomial-distribution.html"><a href="-binomial-distribution.html#section-5.1"><i class="fa fa-check"></i><b>5.1</b> 二項分佈的期望和方差</a></li>
<li class="chapter" data-level="5.2" data-path="-binomial-distribution.html"><a href="-binomial-distribution.html#hyperdist"><i class="fa fa-check"></i><b>5.2</b> 超幾何分佈 hypergeometric distribution</a></li>
<li class="chapter" data-level="5.3" data-path="-binomial-distribution.html"><a href="-binomial-distribution.html#section-5.3"><i class="fa fa-check"></i><b>5.3</b> 樂透中獎概率問題：</a><ul>
<li class="chapter" data-level="5.3.1" data-path="-binomial-distribution.html"><a href="-binomial-distribution.html#-3-"><i class="fa fa-check"></i><b>5.3.1</b> 如果我只想中其中的 <span class="math inline">\(3\)</span> 個號碼，概率有多大？</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="poisson.html"><a href="poisson.html"><i class="fa fa-check"></i><b>6</b> 泊松分佈 Poisson Distribution</a></li>
<li class="chapter" data-level="7" data-path="section-7.html"><a href="section-7.html"><i class="fa fa-check"></i><b>7</b> 正態分佈</a><ul>
<li class="chapter" data-level="7.1" data-path="section-7.html"><a href="section-7.html#-probability-density-function-pdf"><i class="fa fa-check"></i><b>7.1</b> 概率密度曲線 probability density function， PDF</a></li>
<li class="chapter" data-level="7.2" data-path="section-7.html"><a href="section-7.html#-1"><i class="fa fa-check"></i><b>7.2</b> 正態分佈</a></li>
<li class="chapter" data-level="7.3" data-path="section-7.html"><a href="section-7.html#standardNormal"><i class="fa fa-check"></i><b>7.3</b> 標準正態分佈</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="CLT.html"><a href="CLT.html"><i class="fa fa-check"></i><b>8</b> 中心極限定理 the Central Limit Theorem</a><ul>
<li class="chapter" data-level="8.1" data-path="CLT.html"><a href="CLT.html#covariance"><i class="fa fa-check"></i><b>8.1</b> 協方差 Covariance</a></li>
<li class="chapter" data-level="8.2" data-path="CLT.html"><a href="CLT.html#correlation"><i class="fa fa-check"></i><b>8.2</b> 相關 Correlation</a></li>
<li class="chapter" data-level="8.3" data-path="CLT.html"><a href="CLT.html#-the-central-limit-theorem"><i class="fa fa-check"></i><b>8.3</b> 中心極限定理 the Central Limit Theorem</a></li>
<li class="chapter" data-level="8.4" data-path="CLT.html"><a href="CLT.html#binomial-normal-approx"><i class="fa fa-check"></i><b>8.4</b> 二項分佈的正態分佈近似</a></li>
<li class="chapter" data-level="8.5" data-path="CLT.html"><a href="CLT.html#section-8.5"><i class="fa fa-check"></i><b>8.5</b> 泊松分佈的正態分佈近似</a></li>
<li class="chapter" data-level="8.6" data-path="CLT.html"><a href="CLT.html#continuity-correction"><i class="fa fa-check"></i><b>8.6</b> 正態分佈模擬的校正：continuity corrections</a><ul>
<li class="chapter" data-level="8.6.1" data-path="CLT.html"><a href="CLT.html#section-8.6.1"><i class="fa fa-check"></i><b>8.6.1</b> 例題</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="CLT.html"><a href="CLT.html#section-8.7"><i class="fa fa-check"></i><b>8.7</b> 兩個連續隨機變量</a></li>
<li class="chapter" data-level="8.8" data-path="CLT.html"><a href="CLT.html#-"><i class="fa fa-check"></i><b>8.8</b> 兩個連續隨機變量 例子：</a></li>
<li class="chapter" data-level="8.9" data-path="CLT.html"><a href="CLT.html#section-8.9"><i class="fa fa-check"></i><b>8.9</b> 條件分佈和邊緣分佈的概念</a></li>
<li class="chapter" data-level="8.10" data-path="CLT.html"><a href="CLT.html#section-8.10"><i class="fa fa-check"></i><b>8.10</b> 條件分佈和邊緣分佈的例子</a><ul>
<li class="chapter" data-level="8.10.1" data-path="section-7.html"><a href="section-7.html#-1"><i class="fa fa-check"></i><b>8.10.1</b> 例題</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II 統計推斷 Inference</b></span></li>
<li class="chapter" data-level="9" data-path="section-9.html"><a href="section-9.html"><i class="fa fa-check"></i><b>9</b> 統計推斷的概念</a><ul>
<li class="chapter" data-level="9.1" data-path="section-9.html"><a href="section-9.html#-population-and-sample"><i class="fa fa-check"></i><b>9.1</b> 人羣與樣本 (population and sample)</a></li>
<li class="chapter" data-level="9.2" data-path="section-9.html"><a href="section-9.html#-sample-and-statistic"><i class="fa fa-check"></i><b>9.2</b> 樣本和統計量 (sample and statistic)</a></li>
<li class="chapter" data-level="9.3" data-path="section-9.html"><a href="section-9.html#-estimation"><i class="fa fa-check"></i><b>9.3</b> 估計 Estimation</a></li>
<li class="chapter" data-level="9.4" data-path="section-9.html"><a href="section-9.html#-confidence-intervals"><i class="fa fa-check"></i><b>9.4</b> 信賴區間 confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="-estimation-and-precision.html"><a href="-estimation-and-precision.html"><i class="fa fa-check"></i><b>10</b> 估計和精確度 Estimation and Precision</a><ul>
<li class="chapter" data-level="10.1" data-path="-estimation-and-precision.html"><a href="-estimation-and-precision.html#CI-for-sample-mean"><i class="fa fa-check"></i><b>10.1</b> 估計量和他們的樣本分佈</a></li>
<li class="chapter" data-level="10.2" data-path="-estimation-and-precision.html"><a href="-estimation-and-precision.html#section-10.2"><i class="fa fa-check"></i><b>10.2</b> 估計量的特質</a><ul>
<li class="chapter" data-level="10.2.1" data-path="-estimation-and-precision.html"><a href="-estimation-and-precision.html#section-10.2.1"><i class="fa fa-check"></i><b>10.2.1</b> 偏倚</a></li>
<li class="chapter" data-level="10.2.2" data-path="-estimation-and-precision.html"><a href="-estimation-and-precision.html#-efficiency"><i class="fa fa-check"></i><b>10.2.2</b> 估計量的效能 Efficiency</a></li>
<li class="chapter" data-level="10.2.3" data-path="-estimation-and-precision.html"><a href="-estimation-and-precision.html#section-10.2.3"><i class="fa fa-check"></i><b>10.2.3</b> 均值和中位數的相對效能</a></li>
<li class="chapter" data-level="10.2.4" data-path="-estimation-and-precision.html"><a href="-estimation-and-precision.html#-mean-square-error-mse"><i class="fa fa-check"></i><b>10.2.4</b> 均方差 mean square error (MSE)</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="-estimation-and-precision.html"><a href="-estimation-and-precision.html#samplevarbias"><i class="fa fa-check"></i><b>10.3</b> 總體方差的估計，自由度</a></li>
<li class="chapter" data-level="10.4" data-path="-estimation-and-precision.html"><a href="-estimation-and-precision.html#samplevar"><i class="fa fa-check"></i><b>10.4</b> 樣本方差的樣本分佈</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chi-square-distribution.html"><a href="chi-square-distribution.html"><i class="fa fa-check"></i><b>11</b> 卡方分佈 Chi-square distribution</a><ul>
<li class="chapter" data-level="11.1" data-path="chi-square-distribution.html"><a href="chi-square-distribution.html#section-11.1"><i class="fa fa-check"></i><b>11.1</b> 卡方分佈的期望和方差的證明</a></li>
<li class="chapter" data-level="11.2" data-path="chi-square-distribution.html"><a href="chi-square-distribution.html#section-11.2"><i class="fa fa-check"></i><b>11.2</b> 卡方分佈的期望</a></li>
<li class="chapter" data-level="11.3" data-path="chi-square-distribution.html"><a href="chi-square-distribution.html#section-11.3"><i class="fa fa-check"></i><b>11.3</b> 卡方分佈的方差</a><ul>
<li class="chapter" data-level="11.3.1" data-path="chi-square-distribution.html"><a href="chi-square-distribution.html#-ex_14"><i class="fa fa-check"></i><b>11.3.1</b> 下面來求 <span class="math inline">\(E(X_1^4)\)</span></a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="chi-square-distribution.html"><a href="chi-square-distribution.html#section-11.4"><i class="fa fa-check"></i><b>11.4</b> 把上面的推導擴展</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="likelihood-definition.html"><a href="likelihood-definition.html"><i class="fa fa-check"></i><b>12</b> 似然 Likelihood</a><ul>
<li class="chapter" data-level="12.1" data-path="likelihood-definition.html"><a href="likelihood-definition.html#-vs.-probability-vs.inference"><i class="fa fa-check"></i><b>12.1</b> 概率 vs. 推斷 Probability vs. Inference</a></li>
<li class="chapter" data-level="12.2" data-path="likelihood-definition.html"><a href="likelihood-definition.html#-likelihood-and-maximum-likelihood-estimators"><i class="fa fa-check"></i><b>12.2</b> 似然和極大似然估計 Likelihood and maximum likelihood estimators</a></li>
<li class="chapter" data-level="12.3" data-path="likelihood-definition.html"><a href="likelihood-definition.html#section-12.3"><i class="fa fa-check"></i><b>12.3</b> 似然方程的一般化定義</a></li>
<li class="chapter" data-level="12.4" data-path="likelihood-definition.html"><a href="likelihood-definition.html#-log-likelihood"><i class="fa fa-check"></i><b>12.4</b> 對數似然方程 log-likelihood</a></li>
<li class="chapter" data-level="12.5" data-path="likelihood-definition.html"><a href="likelihood-definition.html#-maximum-likelihood-estimator-mle-"><i class="fa fa-check"></i><b>12.5</b> 極大似然估計 (maximum likelihood estimator, MLE) 的性質：</a></li>
<li class="chapter" data-level="12.6" data-path="likelihood-definition.html"><a href="likelihood-definition.html#likelihood-poi"><i class="fa fa-check"></i><b>12.6</b> 率的似然估計 Likelihood for a rate</a></li>
<li class="chapter" data-level="12.7" data-path="likelihood-definition.html"><a href="likelihood-definition.html#-n-"><i class="fa fa-check"></i><b>12.7</b> 有 <span class="math inline">\(n\)</span> 個獨立觀察時的似然方程和對數似然方程</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="llr.html"><a href="llr.html"><i class="fa fa-check"></i><b>13</b> 對數似然比 Log-likelihood ratio</a><ul>
<li class="chapter" data-level="13.1" data-path="llr.html"><a href="llr.html#section-13.1"><i class="fa fa-check"></i><b>13.1</b> 正態分佈數據的極大似然和對數似然比</a></li>
<li class="chapter" data-level="13.2" data-path="llr.html"><a href="llr.html#llr-chi1"><i class="fa fa-check"></i><b>13.2</b> <span class="math inline">\(n\)</span> 個獨立正態分佈樣本的對數似然比</a></li>
<li class="chapter" data-level="13.3" data-path="llr.html"><a href="llr.html#llr-chi"><i class="fa fa-check"></i><b>13.3</b> <span class="math inline">\(n\)</span> 個獨立正態分佈樣本的對數似然比的分佈</a></li>
<li class="chapter" data-level="13.4" data-path="llr.html"><a href="llr.html#section-13.4"><i class="fa fa-check"></i><b>13.4</b> 似然比信賴區間</a><ul>
<li class="chapter" data-level="13.4.1" data-path="llr.html"><a href="llr.html#binomial-ex"><i class="fa fa-check"></i><b>13.4.1</b> 以二項分佈數據爲例</a></li>
<li class="chapter" data-level="13.4.2" data-path="llr.html"><a href="llr.html#normal-ex"><i class="fa fa-check"></i><b>13.4.2</b> 以正態分佈數據爲例</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="llr.html"><a href="llr.html#section-13.5"><i class="fa fa-check"></i><b>13.5</b> 練習題</a><ul>
<li class="chapter" data-level="13.5.1" data-path="llr.html"><a href="llr.html#q1"><i class="fa fa-check"></i><b>13.5.1</b> Q1</a></li>
<li class="chapter" data-level="13.5.2" data-path="llr.html"><a href="llr.html#q2"><i class="fa fa-check"></i><b>13.5.2</b> Q2</a></li>
<li class="chapter" data-level="13.5.3" data-path="llr.html"><a href="llr.html#q3"><i class="fa fa-check"></i><b>13.5.3</b> Q3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="quadratic-llr.html"><a href="quadratic-llr.html"><i class="fa fa-check"></i><b>14</b> 二次方程近似法求對數似然比 approximate log-likelihood ratios</a><ul>
<li class="chapter" data-level="14.1" data-path="quadratic-llr.html"><a href="quadratic-llr.html#quadratic-llr2"><i class="fa fa-check"></i><b>14.1</b> 正態近似法求對數似然 Normal approximation to the log-likelihood</a><ul>
<li class="chapter" data-level="14.1.1" data-path="quadratic-llr.html"><a href="quadratic-llr.html#section-14.1.1"><i class="fa fa-check"></i><b>14.1.1</b> 近似法估算對數似然比的信賴區間</a></li>
<li class="chapter" data-level="14.1.2" data-path="quadratic-llr.html"><a href="quadratic-llr.html#section-14.1.2"><i class="fa fa-check"></i><b>14.1.2</b> 以泊松分佈爲例</a></li>
<li class="chapter" data-level="14.1.3" data-path="quadratic-llr.html"><a href="quadratic-llr.html#quadratic-binomial-approx"><i class="fa fa-check"></i><b>14.1.3</b> 以二項分佈爲例</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="quadratic-llr.html"><a href="quadratic-llr.html#para-trans"><i class="fa fa-check"></i><b>14.2</b> 參數转换 parameter transformations</a><ul>
<li class="chapter" data-level="14.2.1" data-path="quadratic-llr.html"><a href="quadratic-llr.html#Possion-log-transform"><i class="fa fa-check"></i><b>14.2.1</b> 以泊松分佈爲例</a></li>
<li class="chapter" data-level="14.2.2" data-path="quadratic-llr.html"><a href="quadratic-llr.html#section-14.2.2"><i class="fa fa-check"></i><b>14.2.2</b> 以二項分佈爲例</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="section-7.html"><a href="section-7.html#-1"><i class="fa fa-check"></i><b>14.3</b> 練習題</a><ul>
<li class="chapter" data-level="14.3.1" data-path="quadratic-llr.html"><a href="quadratic-llr.html#q1-1"><i class="fa fa-check"></i><b>14.3.1</b> Q1</a></li>
<li class="chapter" data-level="14.3.2" data-path="quadratic-llr.html"><a href="quadratic-llr.html#q2-1"><i class="fa fa-check"></i><b>14.3.2</b> Q2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html"><i class="fa fa-check"></i><b>15</b> 假設檢驗的構建 Construction of a hypothesis test</a><ul>
<li class="chapter" data-level="15.1" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#null-and-alter"><i class="fa fa-check"></i><b>15.1</b> 什麼是假設檢驗 Hypothesis testing</a></li>
<li class="chapter" data-level="15.2" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#-error-probabilities-and-the-power-function"><i class="fa fa-check"></i><b>15.2</b> 錯誤概率和效能方程 error probabilities and the power function</a><ul>
<li class="chapter" data-level="15.2.1" data-path="section-7.html"><a href="section-7.html#-1"><i class="fa fa-check"></i><b>15.2.1</b> 以二項分佈爲例</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#Neyman-Pearson"><i class="fa fa-check"></i><b>15.3</b> 如何選擇要檢驗的統計量</a><ul>
<li class="chapter" data-level="15.3.1" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#section-15.3.1"><i class="fa fa-check"></i><b>15.3.1</b> 以已知方差的正態分佈爲例</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#-composite-hypotheses"><i class="fa fa-check"></i><b>15.4</b> 複合假設 composite hypotheses</a><ul>
<li class="chapter" data-level="15.4.1" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#section-15.4.1"><i class="fa fa-check"></i><b>15.4.1</b> 單側替代假設</a></li>
<li class="chapter" data-level="15.4.2" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#section-15.4.2"><i class="fa fa-check"></i><b>15.4.2</b> 雙側替代假設</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#-h_0-"><i class="fa fa-check"></i><b>15.5</b> 爲反對零假設 <span class="math inline">\(H_0\)</span> 的證據定量</a><ul>
<li class="chapter" data-level="15.5.1" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#normal-mean-compare"><i class="fa fa-check"></i><b>15.5.1</b> 回到正態分佈的均值比較問題上來(單側替代假設)</a></li>
</ul></li>
<li class="chapter" data-level="15.6" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#-p-"><i class="fa fa-check"></i><b>15.6</b> 雙側替代假設情況下，雙側 <span class="math inline">\(p\)</span> 值的定量方法</a></li>
<li class="chapter" data-level="15.7" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#test-summary"><i class="fa fa-check"></i><b>15.7</b> 假設檢驗構建之總結</a></li>
<li class="chapter" data-level="15.8" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#-2"><i class="fa fa-check"></i><b>15.8</b> 練習題</a><ul>
<li class="chapter" data-level="15.8.1" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#q1-2"><i class="fa fa-check"></i><b>15.8.1</b> Q1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="section-16.html"><a href="section-16.html"><i class="fa fa-check"></i><b>16</b> 假設檢驗的近似方法</a><ul>
<li class="chapter" data-level="16.1" data-path="section-16.html"><a href="section-16.html#-approximate-and-exact-tests"><i class="fa fa-check"></i><b>16.1</b> 近似和精確檢驗 approximate and exact tests</a></li>
<li class="chapter" data-level="16.2" data-path="section-16.html"><a href="section-16.html#LRT"><i class="fa fa-check"></i><b>16.2</b> 精確檢驗法之 – 似然比檢驗法 Likelihood ratio test</a></li>
<li class="chapter" data-level="16.3" data-path="section-16.html"><a href="section-16.html#-3"><i class="fa fa-check"></i><b>16.3</b> 練習題</a></li>
<li class="chapter" data-level="16.4" data-path="section-16.html"><a href="section-16.html#Wald"><i class="fa fa-check"></i><b>16.4</b> 近似檢驗法之 – Wald 檢驗</a><ul>
<li class="chapter" data-level="16.4.1" data-path="section-16.html"><a href="section-16.html#section-16.4.1"><i class="fa fa-check"></i><b>16.4.1</b> 再以二項分佈爲例</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="section-16.html"><a href="section-16.html#Score"><i class="fa fa-check"></i><b>16.5</b> 近似檢驗法之 – Score 检验</a><ul>
<li class="chapter" data-level="16.5.1" data-path="section-16.html"><a href="section-16.html#section-16.5.1"><i class="fa fa-check"></i><b>16.5.1</b> 再再以二項分佈爲例</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="section-16.html"><a href="section-16.html#LRTwaldScore-Compare"><i class="fa fa-check"></i><b>16.6</b> LRT, Wald, Score 檢驗三者的比較</a></li>
<li class="chapter" data-level="16.7" data-path="section-16.html"><a href="section-16.html#-4"><i class="fa fa-check"></i><b>16.7</b> 練習題</a><ul>
<li class="chapter" data-level="16.7.1" data-path="section-16.html"><a href="section-16.html#q1-3"><i class="fa fa-check"></i><b>16.7.1</b> Q1</a></li>
<li class="chapter" data-level="16.7.2" data-path="section-16.html"><a href="section-16.html#q2-2"><i class="fa fa-check"></i><b>16.7.2</b> Q2</a></li>
<li class="chapter" data-level="16.7.3" data-path="section-16.html"><a href="section-16.html#q3-1"><i class="fa fa-check"></i><b>16.7.3</b> Q3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="-normal-error-models.html"><a href="-normal-error-models.html"><i class="fa fa-check"></i><b>17</b> 正態誤差模型 Normal error models</a><ul>
<li class="chapter" data-level="17.1" data-path="-normal-error-models.html"><a href="-normal-error-models.html#section-17.1"><i class="fa fa-check"></i><b>17.1</b> 服從正態分佈的隨機變量</a></li>
<li class="chapter" data-level="17.2" data-path="-normal-error-models.html"><a href="-normal-error-models.html#Fandtdistr"><i class="fa fa-check"></i><b>17.2</b> <span class="math inline">\(F\)</span> 分佈和 <span class="math inline">\(t\)</span> 分佈的概念</a></li>
<li class="chapter" data-level="17.3" data-path="-normal-error-models.html"><a href="-normal-error-models.html#section-17.3"><i class="fa fa-check"></i><b>17.3</b> 兩個參數的模型</a><ul>
<li class="chapter" data-level="17.3.1" data-path="-normal-error-models.html"><a href="-normal-error-models.html#section-17.3.1"><i class="fa fa-check"></i><b>17.3.1</b> 一組數據兩個參數</a></li>
<li class="chapter" data-level="17.3.2" data-path="-normal-error-models.html"><a href="-normal-error-models.html#section-17.3.2"><i class="fa fa-check"></i><b>17.3.2</b> 兩組數據各一個參數</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="-normal-error-models.html"><a href="-normal-error-models.html#--t--one-sample-t-test-"><i class="fa fa-check"></i><b>17.4</b> 正態分佈概率密度方程中總體均值和方差都未知 (單樣本 <span class="math inline">\(t\)</span> 檢驗 one sample <span class="math inline">\(t\)</span> test 的統計學推導)</a></li>
<li class="chapter" data-level="17.5" data-path="-normal-error-models.html"><a href="-normal-error-models.html#-two-sample-t-test-with-equal-unknown-sigma2"><i class="fa fa-check"></i><b>17.5</b> 比較兩組獨立數據的均值 two sample <span class="math inline">\(t\)</span> test with equal unknown <span class="math inline">\(\sigma^2\)</span></a></li>
<li class="chapter" data-level="17.6" data-path="-normal-error-models.html"><a href="-normal-error-models.html#section-17.6"><i class="fa fa-check"></i><b>17.6</b> 各個統計分佈之間的關係</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="-inference-with-multiple-parameters-i.html"><a href="-inference-with-multiple-parameters-i.html"><i class="fa fa-check"></i><b>18</b> 多個參數時的統計推斷 Inference with multiple parameters I</a><ul>
<li class="chapter" data-level="18.1" data-path="-inference-with-multiple-parameters-i.html"><a href="-inference-with-multiple-parameters-i.html#-multiple-parameters---lrt"><i class="fa fa-check"></i><b>18.1</b> 多參數 multiple parameters - LRT</a><ul>
<li class="chapter" data-level="18.1.1" data-path="-inference-with-multiple-parameters-i.html"><a href="-inference-with-multiple-parameters-i.html#-likelihood"><i class="fa fa-check"></i><b>18.1.1</b> 似然 likelihood</a></li>
<li class="chapter" data-level="18.1.2" data-path="-inference-with-multiple-parameters-i.html"><a href="-inference-with-multiple-parameters-i.html#section-18.1.2"><i class="fa fa-check"></i><b>18.1.2</b> 對數似然比檢驗</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="-inference-with-multiple-parameters-i.html"><a href="-inference-with-multiple-parameters-i.html#-wald----wald-test"><i class="fa fa-check"></i><b>18.2</b> 多參數 Wald 檢驗 - Wald test</a></li>
<li class="chapter" data-level="18.3" data-path="-inference-with-multiple-parameters-i.html"><a href="-inference-with-multiple-parameters-i.html#-score----score-test"><i class="fa fa-check"></i><b>18.3</b> 多參數 Score 檢驗 - Score test</a></li>
<li class="chapter" data-level="18.4" data-path="-inference-with-multiple-parameters-i.html"><a href="-inference-with-multiple-parameters-i.html#condilikeli"><i class="fa fa-check"></i><b>18.4</b> 條件似然 conditional likelihood</a></li>
<li class="chapter" data-level="18.5" data-path="-inference-with-multiple-parameters-i.html"><a href="-inference-with-multiple-parameters-i.html#section-18.5"><i class="fa fa-check"></i><b>18.5</b> 練習</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html"><i class="fa fa-check"></i><b>19</b> 多個參數時的統計推斷 – 子集似然函數 profile log-likelihoods</a><ul>
<li class="chapter" data-level="19.1" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#section-19.1"><i class="fa fa-check"></i><b>19.1</b> 子集似然法推導的過程總結</a><ul>
<li class="chapter" data-level="19.1.1" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#section-19.1.1"><i class="fa fa-check"></i><b>19.1.1</b> 子集對數似然方程的分佈</a></li>
<li class="chapter" data-level="19.1.2" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#section-19.1.2"><i class="fa fa-check"></i><b>19.1.2</b> 假設檢驗過程舉例</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#section-19.2"><i class="fa fa-check"></i><b>19.2</b> 子集對數似然比的近似</a><ul>
<li class="chapter" data-level="19.2.1" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#section-19.2.1"><i class="fa fa-check"></i><b>19.2.1</b> 子集對數似然比近似的一般化</a></li>
<li class="chapter" data-level="19.2.2" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#-wald-"><i class="fa fa-check"></i><b>19.2.2</b> 事件發生率之比的 Wald 檢驗統計量</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#-practical"><i class="fa fa-check"></i><b>19.3</b> 練習 Practical</a></li>
<li class="chapter" data-level="19.4" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#section-19.4"><i class="fa fa-check"></i><b>19.4</b> 總結</a><ul>
<li class="chapter" data-level="19.4.1" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#section-19.4.1"><i class="fa fa-check"></i><b>19.4.1</b> 快速複習</a></li>
<li class="chapter" data-level="19.4.2" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#section-19.4.2"><i class="fa fa-check"></i><b>19.4.2</b> 試爲下面的醫學研究問題提出合適的統計學模型</a></li>
<li class="chapter" data-level="19.4.3" data-path="profile-log-likelihood.html"><a href="profile-log-likelihood.html#section-19.4.3"><i class="fa fa-check"></i><b>19.4.3</b> 醫生來找統計學家問問題</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III 統計分析方法 Analytical Techniques</b></span></li>
<li class="chapter" data-level="20" data-path="section-20.html"><a href="section-20.html"><i class="fa fa-check"></i><b>20</b> 探索數據和簡單描述</a><ul>
<li class="chapter" data-level="20.1" data-path="section-20.html"><a href="section-20.html#section-20.1"><i class="fa fa-check"></i><b>20.1</b> 數據分析的流程</a><ul>
<li class="chapter" data-level="20.1.1" data-path="section-20.html"><a href="section-20.html#section-20.1.1"><i class="fa fa-check"></i><b>20.1.1</b> 研究設計和實施</a></li>
<li class="chapter" data-level="20.1.2" data-path="section-20.html"><a href="section-20.html#section-20.1.2"><i class="fa fa-check"></i><b>20.1.2</b> 數據分析</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="section-20.html"><a href="section-20.html#section-20.2"><i class="fa fa-check"></i><b>20.2</b> 數據類型</a></li>
<li class="chapter" data-level="20.3" data-path="section-20.html"><a href="section-20.html#section-20.3"><i class="fa fa-check"></i><b>20.3</b> 如何總結並展示數據</a><ul>
<li class="chapter" data-level="20.3.1" data-path="section-20.html"><a href="section-20.html#----frequency-table"><i class="fa fa-check"></i><b>20.3.1</b> 離散型分類型數據的描述 - 頻數分佈表 frequency table</a></li>
<li class="chapter" data-level="20.3.2" data-path="section-20.html"><a href="section-20.html#section-20.3.2"><i class="fa fa-check"></i><b>20.3.2</b> 連續型變量</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="section-20.html"><a href="section-20.html#section-20.4"><i class="fa fa-check"></i><b>20.4</b> 數據總結方案：位置，分散，偏度，和峰度</a><ul>
<li class="chapter" data-level="20.4.1" data-path="section-20.html"><a href="section-20.html#section-20.4.1"><i class="fa fa-check"></i><b>20.4.1</b> 位置</a></li>
<li class="chapter" data-level="20.4.2" data-path="section-20.html"><a href="section-20.html#section-20.4.2"><i class="fa fa-check"></i><b>20.4.2</b> 分散</a></li>
<li class="chapter" data-level="20.4.3" data-path="section-20.html"><a href="section-20.html#-skewness"><i class="fa fa-check"></i><b>20.4.3</b> 偏度 skewness</a></li>
<li class="chapter" data-level="20.4.4" data-path="section-20.html"><a href="section-20.html#-kurtosis"><i class="fa fa-check"></i><b>20.4.4</b> 峯度 kurtosis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="21" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html"><i class="fa fa-check"></i><b>21</b> 信賴區間 confidence intervals</a><ul>
<li class="chapter" data-level="21.1" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#section-21.1"><i class="fa fa-check"></i><b>21.1</b> 定義</a></li>
<li class="chapter" data-level="21.2" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#section-21.2"><i class="fa fa-check"></i><b>21.2</b> 利用總體參數的樣本分佈求信賴區間</a></li>
<li class="chapter" data-level="21.3" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#1"><i class="fa fa-check"></i><b>21.3</b> 情況1：已知方差的正態分佈數據均值的信賴區間</a></li>
<li class="chapter" data-level="21.4" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#CImean"><i class="fa fa-check"></i><b>21.4</b> 信賴區間的意義</a></li>
<li class="chapter" data-level="21.5" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#AT2-5"><i class="fa fa-check"></i><b>21.5</b> 情況2：未知方差，但是已知服從正態分佈數據均值的信賴區間</a></li>
<li class="chapter" data-level="21.6" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#varCI"><i class="fa fa-check"></i><b>21.6</b> 情況3：服從正態分佈的隨機變量方差的信賴區間</a></li>
<li class="chapter" data-level="21.7" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#section-21.7"><i class="fa fa-check"></i><b>21.7</b> 當樣本量足夠大時</a></li>
<li class="chapter" data-level="21.8" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#4"><i class="fa fa-check"></i><b>21.8</b> 情況4：求人羣百分比的信賴區間</a><ul>
<li class="chapter" data-level="21.8.1" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#section-21.8.1"><i class="fa fa-check"></i><b>21.8.1</b> 一般原則</a></li>
<li class="chapter" data-level="21.8.2" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#exactprop"><i class="fa fa-check"></i><b>21.8.2</b> 二項分佈的“精確法”計算信賴區間</a></li>
<li class="chapter" data-level="21.8.3" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#section-21.8.3"><i class="fa fa-check"></i><b>21.8.3</b> 二項分佈的近似法計算信賴區間</a></li>
</ul></li>
<li class="chapter" data-level="21.9" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#CIrate"><i class="fa fa-check"></i><b>21.9</b> 率的信賴區間</a><ul>
<li class="chapter" data-level="21.9.1" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#section-21.9.1"><i class="fa fa-check"></i><b>21.9.1</b> 利用泊松分佈精確計算</a></li>
<li class="chapter" data-level="21.9.2" data-path="-confidence-intervals-1.html"><a href="-confidence-intervals-1.html#section-21.9.2"><i class="fa fa-check"></i><b>21.9.2</b> 利用正態近似法計算</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="section-22.html"><a href="section-22.html"><i class="fa fa-check"></i><b>22</b> 假設檢驗</a><ul>
<li class="chapter" data-level="22.1" data-path="section-22.html"><a href="section-22.html#section-22.1"><i class="fa fa-check"></i><b>22.1</b> 拋硬幣的例子</a><ul>
<li class="chapter" data-level="22.1.1" data-path="section-22.html"><a href="section-22.html#section-22.1.1"><i class="fa fa-check"></i><b>22.1.1</b> 單側和雙側檢驗</a></li>
<li class="chapter" data-level="22.1.2" data-path="section-22.html"><a href="section-22.html#p-"><i class="fa fa-check"></i><b>22.1.2</b> <span class="math inline">\(p\)</span> 值的意義</a></li>
<li class="chapter" data-level="22.1.3" data-path="section-22.html"><a href="section-22.html#p-"><i class="fa fa-check"></i><b>22.1.3</b> <span class="math inline">\(p\)</span> 值和信賴區間的關係</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="section-22.html"><a href="section-22.html#section-22.2"><i class="fa fa-check"></i><b>22.2</b> 二項分佈的精確假設檢驗</a></li>
<li class="chapter" data-level="22.3" data-path="section-22.html"><a href="section-22.html#section-22.3"><i class="fa fa-check"></i><b>22.3</b> 當樣本量較大</a></li>
<li class="chapter" data-level="22.4" data-path="section-22.html"><a href="section-22.html#section-22.4"><i class="fa fa-check"></i><b>22.4</b> 二項分佈的正態近似法假設檢驗</a><ul>
<li class="chapter" data-level="22.4.1" data-path="section-22.html"><a href="section-22.html#-continuity-correction"><i class="fa fa-check"></i><b>22.4.1</b> 連續性校正 continuity correction</a></li>
</ul></li>
<li class="chapter" data-level="22.5" data-path="section-22.html"><a href="section-22.html#AT3-5"><i class="fa fa-check"></i><b>22.5</b> 情況1：對均值進行假設檢驗 (方差已知)</a></li>
<li class="chapter" data-level="22.6" data-path="section-22.html"><a href="section-22.html#OneSampleT"><i class="fa fa-check"></i><b>22.6</b> 情況2：對均值進行假設檢驗 (方差未知) the one-sample t-test</a></li>
<li class="chapter" data-level="22.7" data-path="section-22.html"><a href="section-22.html#3-the-paired-t-test"><i class="fa fa-check"></i><b>22.7</b> 情況3：對配對實驗數據的均值差進行假設檢驗 the paired t-test</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="-association.html"><a href="-association.html"><i class="fa fa-check"></i><b>23</b> 相關 association</a><ul>
<li class="chapter" data-level="23.1" data-path="-association.html"><a href="-association.html#section-23.1"><i class="fa fa-check"></i><b>23.1</b> 背景介紹</a></li>
<li class="chapter" data-level="23.2" data-path="-association.html"><a href="-association.html#section-23.2"><i class="fa fa-check"></i><b>23.2</b> 兩個連續型變量的相關分析</a><ul>
<li class="chapter" data-level="23.2.1" data-path="-association.html"><a href="-association.html#section-23.2.1"><i class="fa fa-check"></i><b>23.2.1</b> 相關係數的定義</a></li>
<li class="chapter" data-level="23.2.2" data-path="-association.html"><a href="-association.html#section-23.2.2"><i class="fa fa-check"></i><b>23.2.2</b> 相關係數的性質</a></li>
<li class="chapter" data-level="23.2.3" data-path="-association.html"><a href="-association.html#section-23.2.3"><i class="fa fa-check"></i><b>23.2.3</b> 對相關係數是否爲零進行假設檢驗</a></li>
<li class="chapter" data-level="23.2.4" data-path="-association.html"><a href="-association.html#-95-"><i class="fa fa-check"></i><b>23.2.4</b> 相關係數的 <span class="math inline">\(95\%\)</span> 信賴區間</a></li>
<li class="chapter" data-level="23.2.5" data-path="-association.html"><a href="-association.html#section-23.2.5"><i class="fa fa-check"></i><b>23.2.5</b> 比較兩個相關係數是否相等</a></li>
<li class="chapter" data-level="23.2.6" data-path="-association.html"><a href="-association.html#section-23.2.6"><i class="fa fa-check"></i><b>23.2.6</b> 相關係數那些事兒</a></li>
<li class="chapter" data-level="23.2.7" data-path="-association.html"><a href="-association.html#-r-"><i class="fa fa-check"></i><b>23.2.7</b> 在 R 裏面計算相關係數</a></li>
</ul></li>
<li class="chapter" data-level="23.3" data-path="-association.html"><a href="-association.html#-association-between-pairs-of-binary-variables"><i class="fa fa-check"></i><b>23.3</b> 二元變量之間的相關性 association between pairs of binary variables</a><ul>
<li class="chapter" data-level="23.3.1" data-path="-association.html"><a href="-association.html#or-"><i class="fa fa-check"></i><b>23.3.1</b> OR 的信賴區間</a></li>
<li class="chapter" data-level="23.3.2" data-path="-association.html"><a href="-association.html#section-23.3.2"><i class="fa fa-check"></i><b>23.3.2</b> 比值比的假設檢驗</a></li>
<li class="chapter" data-level="23.3.3" data-path="-association.html"><a href="-association.html#chisquaretest"><i class="fa fa-check"></i><b>23.3.3</b> 兩個百分比的卡方檢驗</a></li>
<li class="chapter" data-level="23.3.4" data-path="-association.html"><a href="-association.html#-fishers-exact-test"><i class="fa fa-check"></i><b>23.3.4</b> 確切檢驗法 Fisher’s “exact” test</a></li>
</ul></li>
<li class="chapter" data-level="23.4" data-path="-association.html"><a href="-association.html#---mtimes-n-"><i class="fa fa-check"></i><b>23.4</b> 多分類 (無排序) 的情況 <span class="math inline">\(M\times N\)</span> 表格</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="-comparisons.html"><a href="-comparisons.html"><i class="fa fa-check"></i><b>24</b> 比較 Comparisons</a><ul>
<li class="chapter" data-level="24.1" data-path="-comparisons.html"><a href="-comparisons.html#-comparing-two-population-means"><i class="fa fa-check"></i><b>24.1</b> 比較兩個均值 comparing two population means</a><ul>
<li class="chapter" data-level="24.1.1" data-path="-comparisons.html"><a href="-comparisons.html#-z-test"><i class="fa fa-check"></i><b>24.1.1</b> 當方差已知，且數據服從正態分佈 Z-test</a></li>
<li class="chapter" data-level="24.1.2" data-path="-comparisons.html"><a href="-comparisons.html#-two-sample-t-test"><i class="fa fa-check"></i><b>24.1.2</b> 當方差未知，但是方差可以被認爲相等，且數據服從正態分佈 two sample <span class="math inline">\(t\)</span> test</a></li>
<li class="chapter" data-level="24.1.3" data-path="section-7.html"><a href="section-7.html#-1"><i class="fa fa-check"></i><b>24.1.3</b> 練習</a></li>
<li class="chapter" data-level="24.1.4" data-path="-comparisons.html"><a href="-comparisons.html#section-24.1.4"><i class="fa fa-check"></i><b>24.1.4</b> 當方差未知，但是方差<strong>不可以</strong>被認爲相等，且數據服從正態分佈</a></li>
</ul></li>
<li class="chapter" data-level="24.2" data-path="-comparisons.html"><a href="-comparisons.html#section-24.2"><i class="fa fa-check"></i><b>24.2</b> 兩個人羣的方差比較</a><ul>
<li class="chapter" data-level="24.2.1" data-path="-comparisons.html"><a href="-comparisons.html#Ftest"><i class="fa fa-check"></i><b>24.2.1</b> 方差比值檢驗 variance ratio test</a></li>
<li class="chapter" data-level="24.2.2" data-path="-comparisons.html"><a href="-comparisons.html#section-24.2.2"><i class="fa fa-check"></i><b>24.2.2</b> 信賴區間</a></li>
</ul></li>
<li class="chapter" data-level="24.3" data-path="-comparisons.html"><a href="-comparisons.html#section-24.3"><i class="fa fa-check"></i><b>24.3</b> 比較兩個百分比</a><ul>
<li class="chapter" data-level="24.3.1" data-path="-comparisons.html"><a href="-comparisons.html#proportiontest"><i class="fa fa-check"></i><b>24.3.1</b> 兩個百分比差是否爲零的推斷 Risk difference</a></li>
<li class="chapter" data-level="24.3.2" data-path="-comparisons.html"><a href="-comparisons.html#-1--relative-riskrisk-ratio"><i class="fa fa-check"></i><b>24.3.2</b> 兩個百分比商是否爲 1 的推斷 relative risk/risk ratio</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="25" data-path="-assumptions-and-transformations.html"><a href="-assumptions-and-transformations.html"><i class="fa fa-check"></i><b>25</b> 前提和數據轉換 Assumptions and transformations</a><ul>
<li class="chapter" data-level="25.1" data-path="-assumptions-and-transformations.html"><a href="-assumptions-and-transformations.html#section-25.1"><i class="fa fa-check"></i><b>25.1</b> 穩健性</a></li>
<li class="chapter" data-level="25.2" data-path="-assumptions-and-transformations.html"><a href="-assumptions-and-transformations.html#section-25.2"><i class="fa fa-check"></i><b>25.2</b> 正態性</a><ul>
<li class="chapter" data-level="25.2.1" data-path="-assumptions-and-transformations.html"><a href="-assumptions-and-transformations.html#normalplot"><i class="fa fa-check"></i><b>25.2.1</b> 正態分佈圖 normal plot</a></li>
</ul></li>
<li class="chapter" data-level="25.3" data-path="-assumptions-and-transformations.html"><a href="-assumptions-and-transformations.html#section-25.3"><i class="fa fa-check"></i><b>25.3</b> 總結連續型變量不服從正態分佈時的處理方案</a></li>
<li class="chapter" data-level="25.4" data-path="-assumptions-and-transformations.html"><a href="-assumptions-and-transformations.html#-power-transformations"><i class="fa fa-check"></i><b>25.4</b> 數學冪轉換 power transformations</a><ul>
<li class="chapter" data-level="25.4.1" data-path="-assumptions-and-transformations.html"><a href="-assumptions-and-transformations.html#-logarithmic-transformation"><i class="fa fa-check"></i><b>25.4.1</b> 對數轉換 logarithmic Transformation</a></li>
<li class="chapter" data-level="25.4.2" data-path="-assumptions-and-transformations.html"><a href="-assumptions-and-transformations.html#-back-transformation-of-cis"><i class="fa fa-check"></i><b>25.4.2</b> 逆轉換信賴區間 back-transformation of CIs</a></li>
<li class="chapter" data-level="25.4.3" data-path="-assumptions-and-transformations.html"><a href="-assumptions-and-transformations.html#-log-normal-distribution"><i class="fa fa-check"></i><b>25.4.3</b> 對數正態分佈 log-normal distribution</a></li>
<li class="chapter" data-level="25.4.4" data-path="-assumptions-and-transformations.html"><a href="-assumptions-and-transformations.html#section-25.4.4"><i class="fa fa-check"></i><b>25.4.4</b> 百分比的轉換</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV 線性迴歸 Linear Regression</b></span></li>
<li class="chapter" data-level="26" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html"><i class="fa fa-check"></i><b>26</b> 簡單線性迴歸 Simple Linear Regression</a><ul>
<li class="chapter" data-level="26.1" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#section-26.1"><i class="fa fa-check"></i><b>26.1</b> 一些背景和術語</a></li>
<li class="chapter" data-level="26.2" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#-simple-linear-regression-model"><i class="fa fa-check"></i><b>26.2</b> 簡單線性迴歸模型 simple linear regression model</a><ul>
<li class="chapter" data-level="26.2.1" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#-a"><i class="fa fa-check"></i><b>26.2.1</b> 數據 A</a></li>
<li class="chapter" data-level="26.2.2" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#-b"><i class="fa fa-check"></i><b>26.2.2</b> 數據 B</a></li>
</ul></li>
<li class="chapter" data-level="26.3" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#section-26.3"><i class="fa fa-check"></i><b>26.3</b> 區分因變量和預測變量</a><ul>
<li class="chapter" data-level="26.3.1" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#meanfunction"><i class="fa fa-check"></i><b>26.3.1</b> 均值 (期待值) 公式</a></li>
<li class="chapter" data-level="26.3.2" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#-the-conditional-distribution-and-the-variance-function"><i class="fa fa-check"></i><b>26.3.2</b> 條件分佈和方差 the conditional distribution and the variance function</a></li>
<li class="chapter" data-level="26.3.3" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#defLM"><i class="fa fa-check"></i><b>26.3.3</b> 定義簡單線性迴歸模型</a></li>
<li class="chapter" data-level="26.3.4" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#-residuals"><i class="fa fa-check"></i><b>26.3.4</b> 殘差 residuals</a></li>
</ul></li>
<li class="chapter" data-level="26.4" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#-estimation-of-parameters"><i class="fa fa-check"></i><b>26.4</b> 參數的估計 estimation of parameters</a><ul>
<li class="chapter" data-level="26.4.1" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#MLEalphabeta"><i class="fa fa-check"></i><b>26.4.1</b> 普通最小二乘法估計 <span class="math inline">\(\alpha, \beta\)</span></a></li>
</ul></li>
<li class="chapter" data-level="26.5" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#ResidualVar"><i class="fa fa-check"></i><b>26.5</b> 殘差方差的估計 Estimation of the residual variance <span class="math inline">\((\sigma^2)\)</span></a></li>
<li class="chapter" data-level="26.6" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#r---1--reffigage-wt-"><i class="fa fa-check"></i><b>26.6</b> R 演示 例 1： 圖 @ref(fig:age-wt) 數據</a></li>
<li class="chapter" data-level="26.7" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#binarylms"><i class="fa fa-check"></i><b>26.7</b> R 演示 例 2： 表@ref(tab:walk) 數據</a></li>
<li class="chapter" data-level="26.8" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#exeChol"><i class="fa fa-check"></i><b>26.8</b> 練習</a><ul>
<li class="chapter" data-level="26.8.1" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#-c_1-c_2-c_2alphabeta-c_2-varepsilon"><i class="fa fa-check"></i><b>26.8.1</b> 兩次測量的膽固醇水平分別用 <span class="math inline">\(C_1, C_2\)</span> 來標記的話，考慮這樣的簡單線性迴歸模型：<span class="math inline">\(C_2=\alpha+\beta C_2 + \varepsilon\)</span>。我們進行這樣迴歸的前提假設有哪些？</a></li>
<li class="chapter" data-level="26.8.2" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#-ols--hatalpha-hatbeta"><i class="fa fa-check"></i><b>26.8.2</b> 計算普通最小二乘法 (OLS) 下，截距和斜率的估計值 <span class="math inline">\(\hat\alpha, \hat\beta\)</span></a></li>
<li class="chapter" data-level="26.8.3" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#section-26.8.3"><i class="fa fa-check"></i><b>26.8.3</b> 和迴歸模型計算的結果作比較，解釋這些估計值的含義</a></li>
<li class="chapter" data-level="26.8.4" data-path="CLT.html"><a href="CLT.html#-"><i class="fa fa-check"></i><b>26.8.4</b> 加上計算的估計值直線 (即迴歸直線)</a></li>
<li class="chapter" data-level="26.8.5" data-path="-simple-linear-regression.html"><a href="-simple-linear-regression.html#diagnosis"><i class="fa fa-check"></i><b>26.8.5</b> 下面的代碼用於模型的假設診斷</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="27" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html"><i class="fa fa-check"></i><b>27</b> 最小二乘估計的性質和推斷 Ordinary Least Squares Estimators and Inference</a><ul>
<li class="chapter" data-level="27.1" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#ols-"><i class="fa fa-check"></i><b>27.1</b> OLS 估計量的性質</a></li>
<li class="chapter" data-level="27.2" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#hatbeta-"><i class="fa fa-check"></i><b>27.2</b> <span class="math inline">\(\hat\beta\)</span> 的性質</a><ul>
<li class="chapter" data-level="27.2.1" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#randbeta"><i class="fa fa-check"></i><b>27.2.1</b> <span class="math inline">\(Y\)</span> 對 <span class="math inline">\(X\)</span> 迴歸， 和 <span class="math inline">\(X\)</span> 對 <span class="math inline">\(Y\)</span> 迴歸</a></li>
<li class="chapter" data-level="27.2.2" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#-1--reffigage-wt-"><i class="fa fa-check"></i><b>27.2.2</b> 例 1： 還是圖 @ref(fig:age-wt) 數據</a></li>
</ul></li>
<li class="chapter" data-level="27.3" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#section-27.3"><i class="fa fa-check"></i><b>27.3</b> 截距和迴歸係數的方差，協方差</a><ul>
<li class="chapter" data-level="27.3.1" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#centring"><i class="fa fa-check"></i><b>27.3.1</b> 中心化 centring</a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#alpha-beta-"><i class="fa fa-check"></i><b>27.4</b> <span class="math inline">\(\alpha, \beta\)</span> 的推斷</a><ul>
<li class="chapter" data-level="27.4.1" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#section-27.4.1"><i class="fa fa-check"></i><b>27.4.1</b> 對迴歸係數進行假設檢驗</a></li>
<li class="chapter" data-level="27.4.2" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#section-27.4.2"><i class="fa fa-check"></i><b>27.4.2</b> 迴歸係數，截距的信賴區間</a></li>
<li class="chapter" data-level="27.4.3" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#----"><i class="fa fa-check"></i><b>27.4.3</b> 預測值的信賴區間 (置信帶) - 測量迴歸曲線本身的不確定性</a></li>
<li class="chapter" data-level="27.4.4" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#-reference-range----95-"><i class="fa fa-check"></i><b>27.4.4</b> 預測帶 Reference range - 包含了 95% 觀察值的區間</a></li>
</ul></li>
<li class="chapter" data-level="27.5" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#rsquare"><i class="fa fa-check"></i><b>27.5</b> 線性迴歸模型和 Pearson 相關係數</a><ul>
<li class="chapter" data-level="27.5.1" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#r2-"><i class="fa fa-check"></i><b>27.5.1</b> <span class="math inline">\(r^2\)</span> 可以理解爲因變量平方和被模型解釋的比例</a></li>
</ul></li>
<li class="chapter" data-level="27.6" data-path="-ordinary-least-squares-estimators-and-inference.html"><a href="-ordinary-least-squares-estimators-and-inference.html#t-r2-F"><i class="fa fa-check"></i><b>27.6</b> Pearson 相關係數和模型迴歸係數的檢驗統計量 <span class="math inline">\(t\)</span> 之間的關係</a></li>
<li class="chapter" data-level="27.7" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#-2"><i class="fa fa-check"></i><b>27.7</b> 練習</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="ANOVA.html"><a href="ANOVA.html"><i class="fa fa-check"></i><b>28</b> 方差分析 Introduction to Analysis of Variance</a><ul>
<li class="chapter" data-level="28.1" data-path="ANOVA.html"><a href="ANOVA.html#section-28.1"><i class="fa fa-check"></i><b>28.1</b> 背景</a></li>
<li class="chapter" data-level="28.2" data-path="ANOVA.html"><a href="ANOVA.html#section-28.2"><i class="fa fa-check"></i><b>28.2</b> 簡單線性迴歸模型的方差分析</a><ul>
<li class="chapter" data-level="28.2.1" data-path="ANOVA.html"><a href="ANOVA.html#section-28.2.1"><i class="fa fa-check"></i><b>28.2.1</b> 兩個模型的參數估計</a></li>
<li class="chapter" data-level="28.2.2" data-path="ANOVA.html"><a href="ANOVA.html#section-28.2.2"><i class="fa fa-check"></i><b>28.2.2</b> 分割零假設模型的殘差平方和</a></li>
<li class="chapter" data-level="28.2.3" data-path="ANOVA.html"><a href="ANOVA.html#Rsquare"><i class="fa fa-check"></i><b>28.2.3</b> <span class="math inline">\(R^2\)</span> – 我的名字叫<strong>決定係數</strong> coefficient of determination</a></li>
<li class="chapter" data-level="28.2.4" data-path="ANOVA.html"><a href="ANOVA.html#-the-anova-table"><i class="fa fa-check"></i><b>28.2.4</b> 方差分析表格 the ANOVA table</a></li>
<li class="chapter" data-level="28.2.5" data-path="ANOVA.html"><a href="ANOVA.html#-anova-"><i class="fa fa-check"></i><b>28.2.5</b> 用 ANOVA 進行假設檢驗</a></li>
<li class="chapter" data-level="28.2.6" data-path="ANOVA.html"><a href="ANOVA.html#lm-Ftest"><i class="fa fa-check"></i><b>28.2.6</b> 簡單線性迴歸時的 <span class="math inline">\(F\)</span> 檢驗</a></li>
<li class="chapter" data-level="28.2.7" data-path="ANOVA.html"><a href="ANOVA.html#F-t-same"><i class="fa fa-check"></i><b>28.2.7</b> 簡單線性迴歸時 <span class="math inline">\(F\)</span> 檢驗和 <span class="math inline">\(t\)</span> 檢驗的一致性</a></li>
</ul></li>
<li class="chapter" data-level="28.3" data-path="ANOVA.html"><a href="ANOVA.html#-anova"><i class="fa fa-check"></i><b>28.3</b> 分類變量用作預測變量時的 ANOVA</a><ul>
<li class="chapter" data-level="28.3.1" data-path="ANOVA.html"><a href="ANOVA.html#section-28.3.1"><i class="fa fa-check"></i><b>28.3.1</b> 一個二分類預測變量</a></li>
<li class="chapter" data-level="28.3.2" data-path="ANOVA.html"><a href="ANOVA.html#section-28.3.2"><i class="fa fa-check"></i><b>28.3.2</b> 一個模型，兩種表述</a></li>
<li class="chapter" data-level="28.3.3" data-path="ANOVA.html"><a href="ANOVA.html#section-28.3.3"><i class="fa fa-check"></i><b>28.3.3</b> 分組變量的平方和</a></li>
<li class="chapter" data-level="28.3.4" data-path="ANOVA.html"><a href="ANOVA.html#section-28.3.4"><i class="fa fa-check"></i><b>28.3.4</b> 簡單模型的分組變量大於兩組的情況</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="29" data-path="-multivariable-models.html"><a href="-multivariable-models.html"><i class="fa fa-check"></i><b>29</b> 多元模型分析 Multivariable Models</a><ul>
<li class="chapter" data-level="29.1" data-path="section-7.html"><a href="section-7.html#-1"><i class="fa fa-check"></i><b>29.1</b> 背景</a></li>
<li class="chapter" data-level="29.2" data-path="-multivariable-models.html"><a href="-multivariable-models.html#section-29.2"><i class="fa fa-check"></i><b>29.2</b> 兩個預測變量的線性迴歸模型</a><ul>
<li class="chapter" data-level="29.2.1" data-path="-multivariable-models.html"><a href="-multivariable-models.html#section-29.2.1"><i class="fa fa-check"></i><b>29.2.1</b> 數學標記法和解釋</a></li>
<li class="chapter" data-level="29.2.2" data-path="-multivariable-models.html"><a href="-multivariable-models.html#-least-squares-estimation"><i class="fa fa-check"></i><b>29.2.2</b> 最小平方和估計 Least Squares Estimation</a></li>
</ul></li>
<li class="chapter" data-level="29.3" data-path="-multivariable-models.html"><a href="-multivariable-models.html#section-29.3"><i class="fa fa-check"></i><b>29.3</b> 線性回歸模型中使用分組變量</a></li>
<li class="chapter" data-level="29.4" data-path="-multivariable-models.html"><a href="-multivariable-models.html#-the-analysis-of-covariance-ancova-model"><i class="fa fa-check"></i><b>29.4</b> 協方差分析模型 the Analysis of Covariance (ANCOVA) Model</a></li>
<li class="chapter" data-level="29.5" data-path="-multivariable-models.html"><a href="-multivariable-models.html#section-29.5"><i class="fa fa-check"></i><b>29.5</b> 偏回歸係數的變化</a><ul>
<li class="chapter" data-level="29.5.1" data-path="-multivariable-models.html"><a href="-multivariable-models.html#1-beta_1-beta_1"><i class="fa fa-check"></i><b>29.5.1</b> 情況1： <span class="math inline">\(\beta_1 &gt; \beta_1^*\)</span></a></li>
<li class="chapter" data-level="29.5.2" data-path="-multivariable-models.html"><a href="-multivariable-models.html#2beta_1beta_1"><i class="fa fa-check"></i><b>29.5.2</b> 情況2：<span class="math inline">\(\beta_1&lt;\beta_1^*\)</span></a></li>
<li class="chapter" data-level="29.5.3" data-path="-multivariable-models.html"><a href="-multivariable-models.html#3-beta_1-beta_1"><i class="fa fa-check"></i><b>29.5.3</b> 情況3： <span class="math inline">\(\beta_1 = \beta_1^*\)</span></a></li>
</ul></li>
<li class="chapter" data-level="29.6" data-path="-multivariable-models.html"><a href="-multivariable-models.html#confounding"><i class="fa fa-check"></i><b>29.6</b> 混雜 confounding</a><ul>
<li class="chapter" data-level="29.6.1" data-path="-multivariable-models.html"><a href="-multivariable-models.html#-mediation-effect"><i class="fa fa-check"></i><b>29.6.1</b> 作為媒介 mediation effect</a></li>
<li class="chapter" data-level="29.6.2" data-path="-multivariable-models.html"><a href="-multivariable-models.html#section-29.6.2"><i class="fa fa-check"></i><b>29.6.2</b> 兩個預測變量之間的關係</a></li>
<li class="chapter" data-level="29.6.3" data-path="-multivariable-models.html"><a href="-multivariable-models.html#rct"><i class="fa fa-check"></i><b>29.6.3</b> RCT臨床實驗是個特例</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="30" data-path="section-30.html"><a href="section-30.html"><i class="fa fa-check"></i><b>30</b> 多元模型分析：矩陣標記與其意義</a><ul>
<li class="chapter" data-level="30.1" data-path="section-30.html"><a href="section-30.html#section-30.1"><i class="fa fa-check"></i><b>30.1</b> 線性回歸模型的矩陣/非矩陣標記法</a><ul>
<li class="chapter" data-level="30.1.1" data-path="section-30.html"><a href="section-30.html#section-30.1.1"><i class="fa fa-check"></i><b>30.1.1</b> 模型標記：</a></li>
</ul></li>
<li class="chapter" data-level="30.2" data-path="section-30.html"><a href="section-30.html#section-30.2"><i class="fa fa-check"></i><b>30.2</b> 解讀參數</a><ul>
<li class="chapter" data-level="30.2.1" data-path="section-30.html"><a href="section-30.html#section-30.2.1"><i class="fa fa-check"></i><b>30.2.1</b> 最小二乘估計</a></li>
<li class="chapter" data-level="30.2.2" data-path="section-30.html"><a href="section-30.html#-mathbfhat-y"><i class="fa fa-check"></i><b>30.2.2</b> 因變量的期待值 <span class="math inline">\(\mathbf{\hat Y}\)</span></a></li>
<li class="chapter" data-level="30.2.3" data-path="section-30.html"><a href="section-30.html#section-30.2.3"><i class="fa fa-check"></i><b>30.2.3</b> 殘差</a></li>
</ul></li>
<li class="chapter" data-level="30.3" data-path="section-30.html"><a href="section-30.html#-f-"><i class="fa fa-check"></i><b>30.3</b> 方差分析一般化和 <span class="math inline">\(F\)</span> 檢驗</a><ul>
<li class="chapter" data-level="30.3.1" data-path="section-30.html"><a href="section-30.html#section-30.3.1"><i class="fa fa-check"></i><b>30.3.1</b> 多元線性迴歸時的決定係數和殘差方差</a></li>
<li class="chapter" data-level="30.3.2" data-path="section-30.html"><a href="section-30.html#section-30.3.2"><i class="fa fa-check"></i><b>30.3.2</b> 方差分析表格</a></li>
<li class="chapter" data-level="30.3.3" data-path="section-30.html"><a href="section-30.html#globalsig"><i class="fa fa-check"></i><b>30.3.3</b> 迴歸方程的顯著性檢驗</a></li>
<li class="chapter" data-level="30.3.4" data-path="section-30.html"><a href="section-30.html#partialF"><i class="fa fa-check"></i><b>30.3.4</b> <span class="math inline">\(\text{partial }F\)</span> 檢驗</a></li>
</ul></li>
<li class="chapter" data-level="30.4" data-path="section-30.html"><a href="section-30.html#section-30.4"><i class="fa fa-check"></i><b>30.4</b> 添加新變量對迴歸模型的影響</a><ul>
<li class="chapter" data-level="30.4.1" data-path="section-30.html"><a href="section-30.html#section-30.4.1"><i class="fa fa-check"></i><b>30.4.1</b> 偏迴歸係數方差的改變</a></li>
<li class="chapter" data-level="30.4.2" data-path="section-30.html"><a href="section-30.html#section-30.4.2"><i class="fa fa-check"></i><b>30.4.2</b> 偏迴歸係數檢驗結果的改變</a></li>
<li class="chapter" data-level="30.4.3" data-path="section-30.html"><a href="section-30.html#section-30.4.3"><i class="fa fa-check"></i><b>30.4.3</b> 擬合值的改變</a></li>
<li class="chapter" data-level="30.4.4" data-path="section-30.html"><a href="section-30.html#section-30.4.4"><i class="fa fa-check"></i><b>30.4.4</b> 決定係數的改變</a></li>
<li class="chapter" data-level="30.4.5" data-path="section-30.html"><a href="section-30.html#-collinearity"><i class="fa fa-check"></i><b>30.4.5</b> 共線性 collinearity</a></li>
</ul></li>
<li class="chapter" data-level="30.5" data-path="section-30.html"><a href="section-30.html#section-30.5"><i class="fa fa-check"></i><b>30.5</b> 實戰演習</a><ul>
<li class="chapter" data-level="30.5.1" data-path="section-30.html"><a href="section-30.html#-c-"><i class="fa fa-check"></i><b>30.5.1</b> 血清維生素 C 濃度的預測變量</a></li>
<li class="chapter" data-level="30.5.2" data-path="section-30.html"><a href="section-30.html#section-30.5.2"><i class="fa fa-check"></i><b>30.5.2</b> 紅細胞容積與血紅蛋白</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="31" data-path="section-31.html"><a href="section-31.html"><i class="fa fa-check"></i><b>31</b> 線性迴歸的模型診斷</a><ul>
<li class="chapter" data-level="31.1" data-path="section-31.html"><a href="section-31.html#section-31.1"><i class="fa fa-check"></i><b>31.1</b> 線性迴歸模型的前提條件</a></li>
<li class="chapter" data-level="31.2" data-path="section-31.html"><a href="section-31.html#section-31.2"><i class="fa fa-check"></i><b>31.2</b> 用圖形來視覺診斷</a></li>
<li class="chapter" data-level="31.3" data-path="section-31.html"><a href="section-31.html#section-31.3"><i class="fa fa-check"></i><b>31.3</b> 殘差圖</a></li>
<li class="chapter" data-level="31.4" data-path="section-31.html"><a href="section-31.html#-normal-plot-of-residuals"><i class="fa fa-check"></i><b>31.4</b> 殘差正態圖 normal plot of residuals</a><ul>
<li class="chapter" data-level="31.4.1" data-path="section-31.html"><a href="section-31.html#section-31.4.1"><i class="fa fa-check"></i><b>31.4.1</b> 模型診斷實例</a></li>
</ul></li>
<li class="chapter" data-level="31.5" data-path="section-31.html"><a href="section-31.html#section-31.5"><i class="fa fa-check"></i><b>31.5</b> 前提條件的統計學檢驗</a><ul>
<li class="chapter" data-level="31.5.1" data-path="section-31.html"><a href="section-31.html#section-31.5.1"><i class="fa fa-check"></i><b>31.5.1</b> 二次方程迴歸法檢驗非線性</a></li>
<li class="chapter" data-level="31.5.2" data-path="section-31.html"><a href="section-31.html#section-31.5.2"><i class="fa fa-check"></i><b>31.5.2</b> 非線性關係模型</a></li>
</ul></li>
<li class="chapter" data-level="31.6" data-path="section-31.html"><a href="section-31.html#section-31.6"><i class="fa fa-check"></i><b>31.6</b> 異常值，槓桿值，和庫克距離</a><ul>
<li class="chapter" data-level="31.6.1" data-path="section-31.html"><a href="section-31.html#section-31.6.1"><i class="fa fa-check"></i><b>31.6.1</b> 異常值和標準化殘差</a></li>
<li class="chapter" data-level="31.6.2" data-path="section-31.html"><a href="section-31.html#-leverage"><i class="fa fa-check"></i><b>31.6.2</b> 槓桿值 Leverage</a></li>
<li class="chapter" data-level="31.6.3" data-path="section-31.html"><a href="section-31.html#-cooks-distance"><i class="fa fa-check"></i><b>31.6.3</b> 庫克距離 Cook’s Distance</a></li>
</ul></li>
<li class="chapter" data-level="31.7" data-path="section-31.html"><a href="section-31.html#section-31.7"><i class="fa fa-check"></i><b>31.7</b> 在統計忍者包裏面對模型診斷作圖</a></li>
</ul></li>
<li class="chapter" data-level="32" data-path="interaction.html"><a href="interaction.html"><i class="fa fa-check"></i><b>32</b> 交互作用 Interactions</a><ul>
<li class="chapter" data-level="32.1" data-path="interaction.html"><a href="interaction.html#section-32.1"><i class="fa fa-check"></i><b>32.1</b> 兩個預測變量之間的線性模型交互作用</a><ul>
<li class="chapter" data-level="32.1.1" data-path="interaction.html"><a href="interaction.html#section-32.1.1"><i class="fa fa-check"></i><b>32.1.1</b> 交互作用線性模型的一般表達式</a></li>
<li class="chapter" data-level="32.1.2" data-path="interaction.html"><a href="interaction.html#interaction-cont-bin"><i class="fa fa-check"></i><b>32.1.2</b> 連續型變量和二分類變量之間的交互作用</a></li>
<li class="chapter" data-level="32.1.3" data-path="interaction.html"><a href="interaction.html#section-32.1.3"><i class="fa fa-check"></i><b>32.1.3</b> 兩個二分類變量之間的交互作用</a></li>
<li class="chapter" data-level="32.1.4" data-path="interaction.html"><a href="interaction.html#section-32.1.4"><i class="fa fa-check"></i><b>32.1.4</b> 兩個連續變量之間的交互作用</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V 臨床實驗 Clinical Trials</b></span></li>
<li class="chapter" data-level="33" data-path="sample-size.html"><a href="sample-size.html"><i class="fa fa-check"></i><b>33</b> 樣本量計算問題</a><ul>
<li class="chapter" data-level="33.1" data-path="-construction-of-a-hypothesis-test.html"><a href="-construction-of-a-hypothesis-test.html#-2"><i class="fa fa-check"></i><b>33.1</b> 背景</a></li>
<li class="chapter" data-level="33.2" data-path="sample-size.html"><a href="sample-size.html#section-33.2"><i class="fa fa-check"></i><b>33.2</b> 決定所需樣本量大小的統計學因素</a></li>
<li class="chapter" data-level="33.3" data-path="sample-size.html"><a href="sample-size.html#-type-i-and-type-ii-errors"><i class="fa fa-check"></i><b>33.3</b> 第一類和第二類錯誤 Type I and type II errors</a></li>
<li class="chapter" data-level="33.4" data-path="sample-size.html"><a href="sample-size.html#-percentages-or-proportions"><i class="fa fa-check"></i><b>33.4</b> 比較兩組之間的百分比 (percentages or proportions)</a><ul>
<li class="chapter" data-level="33.4.1" data-path="sample-size.html"><a href="sample-size.html#--5--90"><i class="fa fa-check"></i><b>33.4.1</b> 樣本量計算公式 (使用顯著水平 5%, 和檢驗效能 90%)</a></li>
<li class="chapter" data-level="33.4.2" data-path="CLT.html"><a href="CLT.html#-"><i class="fa fa-check"></i><b>33.4.2</b> 樣本量計算公式的一般化 (不同的顯著水平和檢驗效能條件下)</a></li>
</ul></li>
<li class="chapter" data-level="33.5" data-path="sample-size.html"><a href="sample-size.html#section-33.5"><i class="fa fa-check"></i><b>33.5</b> 比較兩組之間的均值</a><ul>
<li class="chapter" data-level="33.5.1" data-path="sample-size.html"><a href="sample-size.html#section-33.5.1"><i class="fa fa-check"></i><b>33.5.1</b> 樣本量計算公式</a></li>
</ul></li>
<li class="chapter" data-level="33.6" data-path="sample-size.html"><a href="sample-size.html#section-33.6"><i class="fa fa-check"></i><b>33.6</b> 樣本量計算的調整</a></li>
</ul></li>
<li class="chapter" data-level="34" data-path="baseline-adjustment-using-ancova.html"><a href="baseline-adjustment-using-ancova.html"><i class="fa fa-check"></i><b>34</b> Baseline Adjustment using ANCOVA</a></li>
<li class="part"><span><b>VI 穩健統計方法 Robust Statistic Methods</b></span></li>
<li class="chapter" data-level="35" data-path="section-35.html"><a href="section-35.html"><i class="fa fa-check"></i><b>35</b> 穩健統計方法入門</a></li>
<li class="chapter" data-level="36" data-path="section-36.html"><a href="section-36.html"><i class="fa fa-check"></i><b>36</b> 基於秩次的非參數檢驗</a><ul>
<li class="chapter" data-level="36.1" data-path="section-36.html"><a href="section-36.html#-the-sign-test"><i class="fa fa-check"></i><b>36.1</b> 符號檢驗 the Sign test</a><ul>
<li class="chapter" data-level="36.1.1" data-path="section-36.html"><a href="section-36.html#section-36.1.1"><i class="fa fa-check"></i><b>36.1.1</b> 符號檢驗的特點</a></li>
</ul></li>
<li class="chapter" data-level="36.2" data-path="section-36.html"><a href="section-36.html#wilcoxon-the-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>36.2</b> Wilcoxon 符號秩和檢驗，the Wilcoxon signed-rank test</a></li>
<li class="chapter" data-level="36.3" data-path="section-36.html"><a href="section-36.html#wilcoxon-mann-whitney-wmw-"><i class="fa fa-check"></i><b>36.3</b> Wilcoxon-Mann-Whitney (WMW) 檢驗</a></li>
<li class="chapter" data-level="36.4" data-path="section-36.html"><a href="section-36.html#spearmans-rank-correlation-coefficient"><i class="fa fa-check"></i><b>36.4</b> 秩相關，Spearman’s Rank Correlation Coefficient</a></li>
<li class="chapter" data-level="36.5" data-path="section-36.html"><a href="section-36.html#section-36.5"><i class="fa fa-check"></i><b>36.5</b> 基於秩次的非參數檢驗的優缺點</a></li>
</ul></li>
<li class="chapter" data-level="37" data-path="-permutation-procedures.html"><a href="-permutation-procedures.html"><i class="fa fa-check"></i><b>37</b> 排列置換法 Permutation procedures</a><ul>
<li class="chapter" data-level="37.1" data-path="section-7.html"><a href="section-7.html#-1"><i class="fa fa-check"></i><b>37.1</b> 背景介紹</a></li>
<li class="chapter" data-level="37.2" data-path="-permutation-procedures.html"><a href="-permutation-procedures.html#section-37.2"><i class="fa fa-check"></i><b>37.2</b> 直接上實例</a></li>
<li class="chapter" data-level="37.3" data-path="-permutation-procedures.html"><a href="-permutation-procedures.html#section-37.3"><i class="fa fa-check"></i><b>37.3</b> 排列置換法三板斧</a><ul>
<li class="chapter" data-level="37.3.1" data-path="-permutation-procedures.html"><a href="-permutation-procedures.html#-t"><i class="fa fa-check"></i><b>37.3.1</b> 該如何選用合適的檢驗統計量 <span class="math inline">\(T\)</span>？</a></li>
<li class="chapter" data-level="37.3.2" data-path="-permutation-procedures.html"><a href="-permutation-procedures.html#-adjustment-"><i class="fa fa-check"></i><b>37.3.2</b> 可以在排列置換法中對其他變量進行統計學調整 (adjustment) 嗎？</a></li>
<li class="chapter" data-level="37.3.3" data-path="-permutation-procedures.html"><a href="-permutation-procedures.html#section-37.3.3"><i class="fa fa-check"></i><b>37.3.3</b> 排列置換法，基於秩次的非參數檢驗之間的關係</a></li>
<li class="chapter" data-level="37.3.4" data-path="-permutation-procedures.html"><a href="-permutation-procedures.html#section-37.3.4"><i class="fa fa-check"></i><b>37.3.4</b> 排列置換檢驗法，是一種精確檢驗</a></li>
</ul></li>
<li class="chapter" data-level="37.4" data-path="-permutation-procedures.html"><a href="-permutation-procedures.html#section-37.4"><i class="fa fa-check"></i><b>37.4</b> 基於排序置換檢驗法計算信賴區間</a></li>
<li class="chapter" data-level="37.5" data-path="-permutation-procedures.html"><a href="-permutation-procedures.html#section-37.5"><i class="fa fa-check"></i><b>37.5</b> 排序置換法的優缺點</a></li>
</ul></li>
<li class="chapter" data-level="38" data-path="-the-bootstrap.html"><a href="-the-bootstrap.html"><i class="fa fa-check"></i><b>38</b> 自助重抽法 The bootstrap</a><ul>
<li class="chapter" data-level="38.1" data-path="section-7.html"><a href="section-7.html#-1"><i class="fa fa-check"></i><b>38.1</b> 定義</a></li>
</ul></li>
<li class="chapter" data-level="39" data-path="the-sandwich-estimator.html"><a href="the-sandwich-estimator.html"><i class="fa fa-check"></i><b>39</b> The sandwich estimator</a></li>
<li class="part"><span><b>VII 貝葉斯統計</b></span></li>
<li class="chapter" data-level="40" data-path="section-40.html"><a href="section-40.html"><i class="fa fa-check"></i><b>40</b> 貝葉斯統計入門</a><ul>
<li class="chapter" data-level="40.1" data-path="section-40.html"><a href="section-40.html#section-40.1"><i class="fa fa-check"></i><b>40.1</b> 概率論推斷的複習</a></li>
<li class="chapter" data-level="40.2" data-path="section-40.html"><a href="section-40.html#-bayesian-reasoninginverse-probability"><i class="fa fa-check"></i><b>40.2</b> 貝葉斯概率推理/逆概率 Bayesian reasoning/inverse probability</a><ul>
<li class="chapter" data-level="40.2.1" data-path="section-40.html"><a href="section-40.html#-deductive-reasoning---weak-syllogisms"><i class="fa fa-check"></i><b>40.2.1</b> 演繹推理 deductive reasoning 和 三段論 weak syllogisms</a></li>
<li class="chapter" data-level="40.2.2" data-path="section-40.html"><a href="section-40.html#-quantifying-plausibility"><i class="fa fa-check"></i><b>40.2.2</b> 如何給可能性定量 Quantifying plausibility</a></li>
</ul></li>
<li class="chapter" data-level="40.3" data-path="section-40.html"><a href="section-40.html#section-40.3"><i class="fa fa-check"></i><b>40.3</b> 貝葉斯推理的統計學實現</a><ul>
<li class="chapter" data-level="40.3.1" data-path="section-40.html"><a href="section-40.html#-diagnostic-testing"><i class="fa fa-check"></i><b>40.3.1</b> 醫學診斷測試 diagnostic testing</a></li>
<li class="chapter" data-level="40.3.2" data-path="section-40.html"><a href="section-40.html#hiv-"><i class="fa fa-check"></i><b>40.3.2</b> HIV 檢查時的應用</a></li>
<li class="chapter" data-level="40.3.3" data-path="section-40.html"><a href="section-40.html#section-40.3.3"><i class="fa fa-check"></i><b>40.3.3</b> 說點小歷史</a></li>
</ul></li>
<li class="chapter" data-level="40.4" data-path="section-40.html"><a href="section-40.html#-5"><i class="fa fa-check"></i><b>40.4</b> 練習題</a></li>
</ul></li>
<li class="chapter" data-level="41" data-path="section-41.html"><a href="section-41.html"><i class="fa fa-check"></i><b>41</b> 貝葉斯定理的應用：單一參數模型</a><ul>
<li class="chapter" data-level="41.1" data-path="section-41.html"><a href="section-41.html#-notation-for-probability-density-functions"><i class="fa fa-check"></i><b>41.1</b> 貝葉斯理論下的事後二項分佈概率密度方程 notation for probability density functions</a></li>
<li class="chapter" data-level="41.2" data-path="section-41.html"><a href="section-41.html#theta-"><i class="fa fa-check"></i><b>41.2</b> <span class="math inline">\(\theta\)</span> 的先驗概率</a><ul>
<li class="chapter" data-level="41.2.1" data-path="section-41.html"><a href="section-41.html#beta--the-beta-distribution"><i class="fa fa-check"></i><b>41.2.1</b> beta 分佈 the beta distribution</a></li>
<li class="chapter" data-level="41.2.2" data-path="section-41.html"><a href="section-41.html#conjugate"><i class="fa fa-check"></i><b>41.2.2</b> 二項分佈數據事後概率分佈的一般化：共軛性</a></li>
</ul></li>
<li class="chapter" data-level="41.3" data-path="section-41.html"><a href="section-41.html#-6"><i class="fa fa-check"></i><b>41.3</b> 練習題</a><ul>
<li class="chapter" data-level="41.3.1" data-path="section-41.html"><a href="section-41.html#q1-4"><i class="fa fa-check"></i><b>41.3.1</b> Q1</a></li>
<li class="chapter" data-level="41.3.2" data-path="section-41.html"><a href="section-41.html#q2-3"><i class="fa fa-check"></i><b>41.3.2</b> Q2</a></li>
<li class="chapter" data-level="41.3.3" data-path="section-41.html"><a href="section-41.html#q3-2"><i class="fa fa-check"></i><b>41.3.3</b> Q3</a></li>
<li class="chapter" data-level="41.3.4" data-path="section-41.html"><a href="section-41.html#q4"><i class="fa fa-check"></i><b>41.3.4</b> Q4</a></li>
<li class="chapter" data-level="41.3.5" data-path="section-41.html"><a href="section-41.html#q5"><i class="fa fa-check"></i><b>41.3.5</b> Q5</a></li>
<li class="chapter" data-level="41.3.6" data-path="section-41.html"><a href="section-41.html#q6"><i class="fa fa-check"></i><b>41.3.6</b> Q6</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="42" data-path="normal-distribution-applying-bayes-theorem.html"><a href="normal-distribution-applying-bayes-theorem.html"><i class="fa fa-check"></i><b>42</b> Normal distribution applying Bayes’ Theorem</a></li>
<li class="part"><span><b>VIII 廣義線性迴歸模型</b></span></li>
<li class="chapter" data-level="43" data-path="section-43.html"><a href="section-43.html"><i class="fa fa-check"></i><b>43</b> 重要概念複習</a><ul>
<li class="chapter" data-level="43.1" data-path="section-43.html"><a href="section-43.html#section-43.1"><i class="fa fa-check"></i><b>43.1</b> 概率論學派統計推斷要點複習</a></li>
<li class="chapter" data-level="43.2" data-path="section-43.html"><a href="section-43.html#section-43.2"><i class="fa fa-check"></i><b>43.2</b> 似然</a></li>
<li class="chapter" data-level="43.3" data-path="section-43.html"><a href="section-43.html#section-43.3"><i class="fa fa-check"></i><b>43.3</b> 極大似然估計</a></li>
<li class="chapter" data-level="43.4" data-path="section-43.html"><a href="section-43.html#section-43.4"><i class="fa fa-check"></i><b>43.4</b> 關於假設檢驗的複習</a><ul>
<li class="chapter" data-level="43.4.1" data-path="section-43.html"><a href="section-43.html#section-43.4.1"><i class="fa fa-check"></i><b>43.4.1</b> 子集似然函數</a></li>
</ul></li>
<li class="chapter" data-level="43.5" data-path="section-43.html"><a href="section-43.html#section-43.5"><i class="fa fa-check"></i><b>43.5</b> 線性迴歸複習</a><ul>
<li class="chapter" data-level="43.5.1" data-path="section-43.html"><a href="section-43.html#section-43.5.1"><i class="fa fa-check"></i><b>43.5.1</b> 簡單線性迴歸</a></li>
<li class="chapter" data-level="43.5.2" data-path="section-43.html"><a href="section-43.html#section-43.5.2"><i class="fa fa-check"></i><b>43.5.2</b> 多元線性迴歸</a></li>
<li class="chapter" data-level="43.5.3" data-path="section-43.html"><a href="section-43.html#section-43.5.3"><i class="fa fa-check"></i><b>43.5.3</b> 簡單線性迴歸的統計推斷</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="44" data-path="section-44.html"><a href="section-44.html"><i class="fa fa-check"></i><b>44</b> 廣義線性迴歸入門</a><ul>
<li class="chapter" data-level="44.1" data-path="section-44.html"><a href="section-44.html#section-44.1"><i class="fa fa-check"></i><b>44.1</b> 指數分佈家族</a><ul>
<li class="chapter" data-level="44.1.1" data-path="section-44.html"><a href="section-44.html#section-44.1.1"><i class="fa fa-check"></i><b>44.1.1</b> 泊松分佈和二項分佈的指數分佈家族屬性</a></li>
<li class="chapter" data-level="44.1.2" data-path="section-44.html"><a href="section-44.html#exercise.-exponential-distribution"><i class="fa fa-check"></i><b>44.1.2</b> Exercise. Exponential distribution</a></li>
</ul></li>
<li class="chapter" data-level="44.2" data-path="section-44.html"><a href="section-44.html#section-44.2"><i class="fa fa-check"></i><b>44.2</b> 廣義線性迴歸模型之定義</a></li>
<li class="chapter" data-level="44.3" data-path="section-44.html"><a href="section-44.html#section-44.3"><i class="fa fa-check"></i><b>44.3</b> 注意</a></li>
<li class="chapter" data-level="44.4" data-path="section-44.html"><a href="section-44.html#-r--glm"><i class="fa fa-check"></i><b>44.4</b> 如何在 R 裏擬合 “GLM”</a><ul>
<li class="chapter" data-level="44.4.1" data-path="section-44.html"><a href="section-44.html#margins-"><i class="fa fa-check"></i><b>44.4.1</b> <code>margins</code> 命令</a></li>
<li class="chapter" data-level="44.4.2" data-path="section-44.html"><a href="section-44.html#ggplot2geom_smoothmethod-loess-"><i class="fa fa-check"></i><b>44.4.2</b> <code>ggplot2::geom_smooth(method = &quot;loess&quot;)</code> 命令</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="45" data-path="-logistic-regression-model.html"><a href="-logistic-regression-model.html"><i class="fa fa-check"></i><b>45</b> 二項分佈數據的廣義線性迴歸模型 logistic regression model</a><ul>
<li class="chapter" data-level="45.1" data-path="-logistic-regression-model.html"><a href="-logistic-regression-model.html#-grouped-individual-"><i class="fa fa-check"></i><b>45.1</b> 分組/個人 (grouped / individual) 的二項分佈數據</a></li>
<li class="chapter" data-level="45.2" data-path="-logistic-regression-model.html"><a href="-logistic-regression-model.html#section-45.2"><i class="fa fa-check"></i><b>45.2</b> 二項分佈數據的廣義線性迴歸模型</a></li>
<li class="chapter" data-level="45.3" data-path="-logistic-regression-model.html"><a href="-logistic-regression-model.html#section-45.3"><i class="fa fa-check"></i><b>45.3</b> 注</a><ul>
<li class="chapter" data-level="45.3.1" data-path="-logistic-regression-model.html"><a href="-logistic-regression-model.html#exercise.-link-functions."><i class="fa fa-check"></i><b>45.3.1</b> Exercise. Link functions.</a></li>
</ul></li>
<li class="chapter" data-level="45.4" data-path="-logistic-regression-model.html"><a href="-logistic-regression-model.html#section-45.4"><i class="fa fa-check"></i><b>45.4</b> 邏輯迴歸模型迴歸係數的實際意義</a></li>
<li class="chapter" data-level="45.5" data-path="-logistic-regression-model.html"><a href="-logistic-regression-model.html#BSEinfection"><i class="fa fa-check"></i><b>45.5</b> 邏輯迴歸實際案例</a><ul>
<li class="chapter" data-level="45.5.1" data-path="-logistic-regression-model.html"><a href="-logistic-regression-model.html#section-45.5.1"><i class="fa fa-check"></i><b>45.5.1</b> 分析目的</a></li>
<li class="chapter" data-level="45.5.2" data-path="-logistic-regression-model.html"><a href="-logistic-regression-model.html#-1--"><i class="fa fa-check"></i><b>45.5.2</b> 模型 1 飼料 + 羣</a></li>
<li class="chapter" data-level="45.5.3" data-path="-logistic-regression-model.html"><a href="-logistic-regression-model.html#-2---times-"><i class="fa fa-check"></i><b>45.5.3</b> 模型 2 增加交互作用項 飼料 <span class="math inline">\(\times\)</span> 羣</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="46" data-path="section-46.html"><a href="section-46.html"><i class="fa fa-check"></i><b>46</b> 模型比較和擬合優度</a><ul>
<li class="chapter" data-level="46.1" data-path="section-46.html"><a href="section-46.html#-nested-models"><i class="fa fa-check"></i><b>46.1</b> 嵌套式模型的比較 nested models</a></li>
<li class="chapter" data-level="46.2" data-path="section-46.html"><a href="section-46.html#section-46.2"><i class="fa fa-check"></i><b>46.2</b> 嵌套式模型比較實例</a></li>
<li class="chapter" data-level="46.3" data-path="section-46.html"><a href="section-46.html#section-46.3"><i class="fa fa-check"></i><b>46.3</b> 飽和模型，模型的偏差，擬合優度</a><ul>
<li class="chapter" data-level="46.3.1" data-path="section-46.html"><a href="section-46.html#-saturated-model"><i class="fa fa-check"></i><b>46.3.1</b> 飽和模型 saturated model</a></li>
<li class="chapter" data-level="46.3.2" data-path="section-46.html"><a href="section-46.html#-deviance"><i class="fa fa-check"></i><b>46.3.2</b> 模型偏差 deviance</a></li>
</ul></li>
<li class="chapter" data-level="46.4" data-path="section-46.html"><a href="section-46.html#section-46.4"><i class="fa fa-check"></i><b>46.4</b> 個人數據擬合模型的優度檢驗</a></li>
</ul></li>
<li class="chapter" data-level="47" data-path="-poisson-regression.html"><a href="-poisson-regression.html"><i class="fa fa-check"></i><b>47</b> 計數型因變量 Poisson regression</a><ul>
<li class="chapter" data-level="47.1" data-path="-poisson-regression.html"><a href="-poisson-regression.html#-glm"><i class="fa fa-check"></i><b>47.1</b> 泊松 GLM</a></li>
<li class="chapter" data-level="47.2" data-path="-poisson-regression.html"><a href="-poisson-regression.html#section-47.2"><i class="fa fa-check"></i><b>47.2</b> 泊松迴歸實例</a></li>
<li class="chapter" data-level="47.3" data-path="-poisson-regression.html"><a href="-poisson-regression.html#-overdispersion"><i class="fa fa-check"></i><b>47.3</b> 過度離散 overdispersion</a><ul>
<li class="chapter" data-level="47.3.1" data-path="-poisson-regression.html"><a href="-poisson-regression.html#section-47.3.1"><i class="fa fa-check"></i><b>47.3.1</b> 過度離散怎麼查？</a></li>
<li class="chapter" data-level="47.3.2" data-path="-poisson-regression.html"><a href="-poisson-regression.html#-negative-binomial-model"><i class="fa fa-check"></i><b>47.3.2</b> 負二項式分佈模型 negative binomial model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="48" data-path="-poisson-glm-for-rates.html"><a href="-poisson-glm-for-rates.html"><i class="fa fa-check"></i><b>48</b> 率的廣義線性迴歸 Poisson GLM for rates</a><ul>
<li class="chapter" data-level="48.1" data-path="-poisson-glm-for-rates.html"><a href="-poisson-glm-for-rates.html#section-48.1"><i class="fa fa-check"></i><b>48.1</b> 醫學中的率</a></li>
<li class="chapter" data-level="48.2" data-path="-poisson-glm-for-rates.html"><a href="-poisson-glm-for-rates.html#section-48.2"><i class="fa fa-check"></i><b>48.2</b> 泊松過程</a></li>
<li class="chapter" data-level="48.3" data-path="-poisson-glm-for-rates.html"><a href="-poisson-glm-for-rates.html#section-48.3"><i class="fa fa-check"></i><b>48.3</b> 率的模型</a></li>
</ul></li>
<li class="chapter" data-level="49" data-path="section-49.html"><a href="section-49.html"><i class="fa fa-check"></i><b>49</b> 混雜，調整，交互作用</a></li>
<li class="chapter" data-level="50" data-path="section-50.html"><a href="section-50.html"><i class="fa fa-check"></i><b>50</b> 邏輯迴歸</a></li>
<li class="chapter" data-level="51" data-path="section-51.html"><a href="section-51.html"><i class="fa fa-check"></i><b>51</b> 分析策略</a></li>
<li class="chapter" data-level="52" data-path="section-52.html"><a href="section-52.html"><i class="fa fa-check"></i><b>52</b> 模型檢查</a></li>
<li class="chapter" data-level="53" data-path="assessing-model-performance.html"><a href="assessing-model-performance.html"><i class="fa fa-check"></i><b>53</b> Assessing model performance</a></li>
<li class="chapter" data-level="54" data-path="matched-studies.html"><a href="matched-studies.html"><i class="fa fa-check"></i><b>54</b> Matched studies</a></li>
<li class="chapter" data-level="55" data-path="section-55.html"><a href="section-55.html"><i class="fa fa-check"></i><b>55</b> 條件邏輯迴歸</a></li>
<li class="chapter" data-level="56" data-path="multinomial-logistic-regression.html"><a href="multinomial-logistic-regression.html"><i class="fa fa-check"></i><b>56</b> Multinomial Logistic Regression</a></li>
<li class="chapter" data-level="57" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html"><i class="fa fa-check"></i><b>57</b> Ordinal Logistic Regression</a></li>
<li class="part"><span><b>IX Statistical Methods in Epidemiology</b></span></li>
<li class="chapter" data-level="58" data-path="section-58.html"><a href="section-58.html"><i class="fa fa-check"></i><b>58</b> 流行病學中的統計</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>参考文献</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">本书由 bookdown 强力驱动</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">醫學統計學</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="section-30" class="section level1">
<h1><span class="header-section-number">第 30 章</span> 多元模型分析：矩陣標記與其意義</h1>
<p>在線性回歸目前為止介紹的內容中，我們最多只談到了預測變量為兩個的情況。本章，我們要把這些概念推廣到三個或者三個以上預測變量的情況。同時，多重線性回歸時採用的假設檢驗也會被談及。其實最常見的就是 <span class="math inline">\(F\)</span> 檢驗。而且我們也見識過了，當預測變量只有一個的時候，<span class="math inline">\(F\)</span> 檢驗和 <span class="math inline">\(t\)</span> 檢驗是等價的。</p>
<p>重要的概念我們都已經介紹完畢。前一章的多重回歸模型中也強調了，我們之所以希望把多個預測變量放進模型，最大的目的就是想了解這些預測變量之間的相互關係，當他們得到調整 (adjustment) 之後，彼此之間的關係是怎樣的。這樣的關係我們稱之為條件關係 (conditional relationships)。當我們使用條件關係的稱呼時，需要同時指明我們說的是哪個變量，在那個變量不變的條件下，與因變量的關係是如何如何。</p>
<p>本章節最後的部分將會著重關注共線性 (collinearity) 的問題。</p>
<div id="section-30.1" class="section level2">
<h2><span class="header-section-number">30.1</span> 線性回歸模型的矩陣/非矩陣標記法</h2>
<div id="section-30.1.1" class="section level3">
<h3><span class="header-section-number">30.1.1</span> 模型標記：</h3>
<p>假如，因變量用 <span class="math inline">\(Y\)</span> 表示，預測變量有 <span class="math inline">\(p\)</span> 個之多 <span class="math inline">\((X_1,\cdots, X_p)\)</span>。該模型的非矩陣標記法如下： <span class="math display" id="eq:nonmatrixlm">\[
\begin{equation}
y_i  = \alpha + \beta_1 x_{1i}+ \beta_2 x_{2i} + \cdots +  \beta_p x_{pi} + \varepsilon_i \text{ with } \varepsilon_i \sim \text{NID}(0, \sigma^2)
\end{equation}
\tag{30.1}
\]</span> 其中，</p>
<ul>
<li><span class="math inline">\(y_i =\)</span> 第 <span class="math inline">\(i\)</span> 名觀察對象的因變量數據；</li>
<li><span class="math inline">\(x_{pi} =\)</span> 第 <span class="math inline">\(i\)</span> 名觀察對象的第 <span class="math inline">\(p\)</span> 個預測變量的觀察數據。</li>
</ul>
<p>上面的非矩陣標記法，等同於如下的矩陣標記法： <span class="math display" id="eq:matrixlm2">\[
\begin{equation}
\textbf{Y} = \textbf{X}\beta+\varepsilon, \text{ where } \varepsilon \sim N(0, \textbf{I}\sigma^2) \\
\left(
\begin{array}{c}
y_1\\
y_2\\
\vdots\\
y_n
\end{array}
\right) = \left(
\begin{array}{c}
1&amp;  x_{11} &amp; \cdots &amp; x_{p1}  \\
1&amp;  x_{12} &amp; \cdots &amp; x_{p2} \\
\vdots &amp;   \vdots&amp; \vdots &amp; \vdots \\
1&amp;   x_{1n}&amp; \cdots &amp;x_{pn} \\
\end{array}
\right)\left(
\begin{array}{c}
\alpha \\
\beta_1\\
\beta_2 \\
\vdots \\
\beta_p
\end{array}
\right)+\left(
\begin{array}{c}
\varepsilon_1\\
\varepsilon_2\\
\vdots\\
\varepsilon_n\\
\end{array}
\right)
\end{equation}
\tag{30.2}
\]</span> 此公式 <a href="section-30.html#eq:matrixlm2">(30.2)</a> 中</p>
<ul>
<li><span class="math inline">\(\textbf{X}\)</span> 是一個 <span class="math inline">\(n\times(p+1)\)</span> 的矩陣；</li>
<li><span class="math inline">\(\textbf{Y}\)</span> 和 <span class="math inline">\(\varepsilon\)</span> 分別是長度為 <span class="math inline">\(n\)</span> 的列向量；</li>
<li><span class="math inline">\(\beta\)</span> 是長度為 <span class="math inline">\(p+1\)</span> 的列向量，且第一個元素是 <span class="math inline">\(\alpha\)</span>，偶爾被人誤寫成 <span class="math inline">\(\beta_0\)</span>。</li>
</ul>
<p>殘差被認為服從<strong>多元正態分佈 (multivariate normal distribution)</strong>，這個多元正態分佈的方差協方差矩陣等於 <span class="math inline">\(\sigma^2\)</span> 與單位矩陣相乘獲得的矩陣。這其實等價於認為殘差服從獨立正態且方差為 <span class="math inline">\(\sigma^2\)</span> 的分佈，</p>
</div>
</div>
<div id="section-30.2" class="section level2">
<h2><span class="header-section-number">30.2</span> 解讀參數</h2>
<p>模型中的參數的涵義為：</p>
<ul>
<li><span class="math inline">\(\alpha\)</span> 是截距，所有的預測變量都是零的時候，因變量 <span class="math inline">\(Y\)</span> 的期待值大小；</li>
<li><span class="math inline">\(\beta_j\)</span> 是預測變量 <span class="math inline">\(X_j\)</span> 升高一個單位，且其他變量保持不變的同時，因變量 <span class="math inline">\(Y\)</span> 的期待值的變化；</li>
<li><span class="math inline">\(\beta_j\)</span> 都是偏回歸係數，每個偏回歸係數，測量的都是該預測變量調整了其他預測變量之後對於因變量期待值的影響。</li>
</ul>
<div id="section-30.2.1" class="section level3">
<h3><span class="header-section-number">30.2.1</span> 最小二乘估計</h3>
<p>還是同之前一樣，我們對殘差的平方和最小化，來獲取我們關心的預測變量的回歸變量。</p>
<p><span class="math display" id="eq:lsemulti">\[
\begin{aligned}
SS_{RES} &amp; = \sum_{i=1}^n \hat\varepsilon_i^2 =  \sum_{i=1}^n(y_i-\hat{y})^2 \\
&amp; = \sum_{i=1}^n (y_i-\hat\alpha-\hat\beta_1x_{1i}-\hat\beta_2x_{2i}-\cdots-\hat\beta_px_{pi})^2
\end{aligned}
\tag{30.3}
\]</span></p>
<p>下面用矩陣標記法計算 <span class="math inline">\(\hat\beta\)</span>：</p>
<p><span class="math display" id="eq:lm5-4">\[
\begin{aligned}
\text{Because } \mathbf{Y} &amp; = \mathbf{X\hat\beta + \varepsilon} \\
\Rightarrow \mathbf{\varepsilon} &amp; = \mathbf{Y - X\hat\beta}\\
\Rightarrow \mathbf{SS_{RES}} &amp; = \varepsilon_1\times \varepsilon_1 + \varepsilon_2\times \varepsilon_2 + \cdots + \varepsilon_n\times \varepsilon_n \\
                     &amp; = (\varepsilon_1, \varepsilon_2, \cdots, \varepsilon_n)\left(
                     \begin{array}{c}
                     \varepsilon_1\\
                     \varepsilon_2\\
                     \vdots\\
                     \varepsilon_n
                     \end{array}
                     \right) \\
                     &amp; = \mathbf{\varepsilon^\prime} \mathbf{\varepsilon} \\
                     &amp; = \mathbf{(Y-X\hat\beta)^\prime(Y-X\hat\beta)} \\
                     &amp; = \mathbf{Y^\prime Y - X^\prime\hat\beta^\prime Y - Y^\prime X\hat\beta + X^\prime\hat\beta^\prime X \hat\beta} \\
\text{Because} &amp;\text{ transpose of a scalar is a scalar:} \\
 \mathbf{Y^\prime X\hat\beta} &amp; = \mathbf{(Y^\prime X\hat\beta)^\prime = X^\prime\hat\beta^\prime Y} \\
\Rightarrow  \mathbf{SS_{RES}} &amp; = \mathbf{Y^\prime Y - 2X^\prime\hat\beta^\prime Y + X^\prime\hat\beta^\prime X \hat\beta}\\
\Rightarrow \mathbf{\frac{\partial SS_{RES}}{\partial \hat\beta}} &amp; = \mathbf{-2X^\prime Y + 2 X^\prime X \hat\beta} = 0 \\
\Rightarrow \mathbf{\hat\beta} &amp; = \mathbf{(X^\prime X)^{-1}X^\prime Y}
\end{aligned}
\tag{30.4}
\]</span></p>
<p>公式 <a href="section-30.html#eq:lm5-4">(30.4)</a> 是參數矩陣 <span class="math inline">\(\mathbf{\beta}\)</span> 的無偏估計，且服從方差協方差矩陣爲 <span class="math inline">\(\mathbf{(X^\prime X)^{-1}\sigma^2}\)</span> 的多元正態分佈：</p>
<p><span class="math display" id="eq:lm5-5">\[
\begin{equation}
\mathbf{\hat\beta} \sim  N(\mathbf{\beta, (X^\prime X)^{-1}\sigma^2})
\end{equation}
\tag{30.5}
\]</span></p>
<p>另外可以被證明的是，多元線性迴歸模型的殘差方差的估計量計算公式爲：</p>
<p><span class="math display" id="eq:lm5-6">\[
\begin{aligned}
\hat\sigma^2 &amp; = \sum^n_{i=1}\frac{\hat\varepsilon^2_i}{[n-(p+1)]} \\
             &amp; = \sum^n_{i=1}\frac{\sum_{i=1}^n (y_i-\hat\alpha-\hat\beta_1x_{1i}-\hat\beta_2x_{2i}-\cdots-\hat\beta_px_{pi})^2}{[n-(p+1)]} \\
\text{Where } &amp; p \text{ is the number of predictors}
\end{aligned}
\tag{30.6}
\]</span></p>
</div>
<div id="-mathbfhat-y" class="section level3">
<h3><span class="header-section-number">30.2.2</span> 因變量的期待值 <span class="math inline">\(\mathbf{\hat Y}\)</span></h3>
<p>因變量的期待值矩陣 <span class="math inline">\(\mathbf{\hat Y}\)</span> 根據公式 <a href="section-30.html#eq:lm5-4">(30.4)</a> 推導：</p>
<p><span class="math display" id="eq:lm5-7">\[
\begin{aligned}
\mathbf{\hat Y} &amp; = \mathbf{X\hat\beta} \\
                &amp; = \mathbf{X(X^\prime X)^{-1}X^\prime Y}= \mathbf{PY} \\
\text{Where } \mathbf{P} &amp;= \mathbf{X(X^\prime X)^{-1}X^\prime}
\end{aligned}
\tag{30.7}
\]</span></p>
<p>這裏的 <span class="math inline">\(n\times n\)</span> 的正方形矩陣 <span class="math inline">\(\mathbf{P}\)</span> 在多元線性迴歸中是一個極爲重要的矩陣。</p>
<ul>
<li>它常被叫做“帽子/映射 (hat/projection)”矩陣，因爲它把觀察值 <span class="math inline">\(\mathbf{Y}\)</span> 和觀察值的擬合值一一映射；</li>
<li>帽子矩陣的第 <span class="math inline">\(i\)</span> 個對角元素，是第 <span class="math inline">\(i\)</span> 名觀察值的影響值 (leverage)，會用在下章節的模型診斷中；</li>
<li>擬合值矩陣的方差協方差矩陣被定義爲：</li>
</ul>
<p><span class="math display" id="eq:lm5-8">\[
\begin{equation}
\text{Var}(\mathbf{\hat Y}) = \mathbf{P}\sigma^2
\end{equation}
\tag{30.8}
\]</span></p>
</div>
<div id="section-30.2.3" class="section level3">
<h3><span class="header-section-number">30.2.3</span> 殘差</h3>
<p>殘差的觀察值 <span class="math inline">\(\mathbf{\hat\varepsilon}\)</span> 被定義爲觀察值和擬合值的差。根據前節 <a href="section-30.html#eq:lm5-8">(30.8)</a> 推導：</p>
<p><span class="math display" id="eq:lm5-9">\[
\begin{equation}
\mathbf{\hat\varepsilon} = \mathbf{Y - \hat Y} = \mathbf{Y - PY} = \mathbf{(I - P)Y}
\end{equation}
\tag{30.9}
\]</span></p>
<p>這個觀察殘差的方差被定義爲：</p>
<p><span class="math display" id="eq:lm5-10">\[
\begin{equation}
\text{Var}(\mathbf{\hat\varepsilon}) = \mathbf{(I - P)}\sigma^2
\end{equation}
\tag{30.10}
\]</span></p>
<ul>
<li>一般地，<span class="math inline">\(\mathbf{P}\)</span> 不是一個對角矩陣，意思是觀察殘差之間無法保證是獨立的；</li>
<li><span class="math inline">\(\mathbf{P}\)</span> 的對角元素也不全都相等，意思是觀察殘差的方差無法保證是恆定不變的。</li>
</ul>
</div>
</div>
<div id="-f-" class="section level2">
<h2><span class="header-section-number">30.3</span> 方差分析一般化和 <span class="math inline">\(F\)</span> 檢驗</h2>
<div id="section-30.3.1" class="section level3">
<h3><span class="header-section-number">30.3.1</span> 多元線性迴歸時的決定係數和殘差方差</h3>
<p>和簡單線性迴歸一樣，因變量的校正平方和可以被分割成兩部分：迴歸模型能夠解釋的平方和；模型無法解釋的殘差平方和。類比方差分析章節 (Section <a href="ANOVA.html#ANOVA">28</a>) 的公式 <a href="ANOVA.html#eq:SSres-partition">(28.1)</a>：</p>
<p><span class="math display" id="eq:lm5-11">\[
\begin{aligned}
\sum_{i=1}^n(y_i-\bar{y})^2 &amp; = \sum_{i=1}^n(\hat{y}_i - \bar{y})^2 + \sum_{i=1}^n(y_i - \hat{y}_i)^2 \\
SS_{yy}  &amp; = SS_{REG} + SS_{RES}
\end{aligned}
\tag{30.11}
\]</span></p>
<p>和簡單線性迴歸也一樣，多元線性迴歸時的模型決定係數 (coefficient of determination) 的定義爲：</p>
<p><span class="math display" id="eq:lm5-12">\[
\begin{aligned}
R^2 &amp; = \frac{SS_{yy}-SS_{RES}}{SS_{yy}} = 1- \frac{SS_{RES}}{SS_{yy}} \\
    &amp; = 1 - \frac{\sum_{i=1}^n(y_i-\hat{y}_i)^2}{\sum_{i=1}^n(y_i - \bar{y})^2}
\end{aligned}
\tag{30.12}
\]</span></p>
<p>這裏的 <span class="math inline">\(R^2\)</span> 也一樣可以被解釋爲模型能夠解釋的因變量變動部分的百分比 (proportion of the variability in the dependent variable explained by the model)。值得注意的是，當模型中預測變量不減少，每加入一個新的預測變量，決定係數也會增加，相反殘差平方和卻絕不會增加。</p>
</div>
<div id="section-30.3.2" class="section level3">
<h3><span class="header-section-number">30.3.2</span> 方差分析表格</h3>
<p>下表和簡單線性迴歸的方差分析表格很類似，也可以用來作假設檢驗 (迴歸方程的顯著性檢驗 Global <span class="math inline">\(F-\text{test}\)</span>，和偏 <span class="math inline">\(F\)</span> 檢驗 Partial <span class="math inline">\(F-\text{test}\)</span>)。</p>
<table class="table table-striped table-bordered" style="margin-left: auto; margin-right: auto;">
<caption>
表 30.1: Analysis of Variance table for a liear regression model with <span class="math inline">\(p\)</span> predictor variables
</caption>
<thead>
<tr>
<th style="text-align:center;">
Source of <br>Variation
</th>
<th style="text-align:center;">
Sum of <br>Squares
</th>
<th style="text-align:center;">
Degrees of <br>Freedom
</th>
<th style="text-align:center;">
Mean Sum of <br>Squares
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Regression (model)
</td>
<td style="text-align:center;">
<span class="math inline">\(SS_{REG}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(p\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(MS_{REG} = \frac{SS_{REG}}{p}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
Residual
</td>
<td style="text-align:center;">
<span class="math inline">\(SS_{RES}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(n-(p+1)\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(MS_{RES} = \frac{SS_{RES}}{[n-(p+1)]}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
Total
</td>
<td style="text-align:center;">
<span class="math inline">\(SS_{yy}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(n-1\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\frac{SS_{yy}}{(n-1)}\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<div id="globalsig" class="section level3">
<h3><span class="header-section-number">30.3.3</span> 迴歸方程的顯著性檢驗</h3>
<p>整個方程的顯著性檢驗，檢驗的是所有的迴歸係數都等於零的零假設，其對應的替代假設則是：“迴歸係數<strong>不全爲零</strong>”。就是至少有一個不等於零。</p>
<p>在零假設條件下，檢驗統計量的計算公式爲：</p>
<p><span class="math display" id="eq:lm5-13">\[
\begin{equation}
F = \frac{MS_{REG}}{MS_{RES}} \sim F_{p, [n-(p+1)]}
\end{equation}
\tag{30.13}
\]</span></p>
<p>在零假設條件下，<span class="math inline">\(F\)</span> 的期望值接近 <span class="math inline">\(1\)</span>，而替代假設條件下的 <span class="math inline">\(F\)</span> 總是會大於此，所以和 <span class="math inline">\(F\)</span> 分佈比較特徵值時只需要比較單側的 (右側的) 值，即可獲得雙側 <span class="math inline">\(p\)</span> 值。</p>
<p>在 R 裏面，迴歸方程的結果的最底下會出現統計量 <span class="math inline">\(F\)</span> 的大小，但是 <span class="math inline">\(MS_{REG}, MS_{RES}\)</span> 要用 <code>anova()</code> 代碼獲得：</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(haven)
growgam1 &lt;-<span class="st"> </span><span class="kw">read_dta</span>(<span class="st">&quot;backupfiles/growgam1.dta&quot;</span>)
growgam1<span class="op">$</span>sex &lt;-<span class="st"> </span><span class="kw">as.factor</span>(growgam1<span class="op">$</span>sex)

Model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(wt <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>len, <span class="dt">data=</span>growgam1)
<span class="kw">print</span>(<span class="kw">summary</span>(Model1), <span class="dt">digits =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wt ~ age + len, data = growgam1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -3.20525 -0.64402 -0.00303  0.55967  2.86277 
## 
## Coefficients:
##              Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) -8.351244   1.259968 -6.6281 3.531e-10 ***
## age         -0.011260   0.016751 -0.6722    0.5023    
## len          0.237129   0.019516 12.1502 &lt; 2.2e-16 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9546 on 187 degrees of freedom
## Multiple R-squared:  0.74337,    Adjusted R-squared:  0.74063 
## F-statistic: 270.84 on 2 and 187 DF,  p-value: &lt; 2.22e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(<span class="kw">anova</span>(Model1), <span class="dt">digits =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: wt
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## age         1 359.06  359.06  394.06 &lt; 2.2e-16 ***
## len         1 134.52  134.52  147.63 &lt; 2.2e-16 ***
## Residuals 187 170.39    0.91                      
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>可以看到 <code>summary()</code> 輸出結果的最後一行是關於迴歸方程整體的 <span class="math inline">\(F\)</span> 檢驗結果 <code>F-statistic: 270.84 on 2 and 187 DF,  p-value: &lt; 2.22e-16</code>，從 <code>anova()</code> 結果中可以獲得 <span class="math inline">\(MS_{REG} = \frac{359.0632 + 134.5153}{2} = 246.7892\)</span>。<span class="math inline">\(F_{2,187} = \frac{246.7892}{0.9111833} = 270.84\)</span>。這個檢驗結果證明了，兩個預測變量 “體重” 和 “身長” 至少有一個的迴歸係數不等於零。</p>
</div>
<div id="partialF" class="section level3">
<h3><span class="header-section-number">30.3.4</span> <span class="math inline">\(\text{partial }F\)</span> 檢驗</h3>
<p>如果我們建立兩個模型，一個稍微複雜一些 <span class="math inline">\((B)\)</span>，比起略簡單的模型 <span class="math inline">\((A)\)</span>，增加了 <span class="math inline">\(k\)</span> 個預測變量。兩個模型放在一起的方差分析表格可以歸納成：</p>
<table class="table table-striped table-bordered" style="margin-left: auto; margin-right: auto;">
<caption>
表 30.2: Analysis of Variance table comparing the fit of a model <span class="math inline">\((B)\)</span> with <span class="math inline">\(p\)</span> predictor variables with that of one (model <span class="math inline">\(A\)</span>) with <span class="math inline">\(p-k\)</span> predictor variables
</caption>
<thead>
<tr>
<th style="text-align:center;">
Source of <br>Variation
</th>
<th style="text-align:center;">
Sum of <br>Squares
</th>
<th style="text-align:center;">
Degrees of <br>Freedom
</th>
<th style="text-align:center;">
Mean Sum of <br>Squares
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Explained by <br> model <span class="math inline">\(A\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(SS_{REG_A}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(p-k\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(MS_{REG_A} = \frac{SS_{REG_A}}{p-k}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
Extra Explained <br> by model <span class="math inline">\(B\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(SS_{REG_B}-SS_{REG_A}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(k\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\frac{SS_{REG_B}-SS_{REG_A}}{k}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
Residual from <br> model <span class="math inline">\(B\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(SS_{RES_B}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(n-(p+1)\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(MS_{RES_B} = \frac{SS_{RES_B}}{[n-(p+1)]}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
Total
</td>
<td style="text-align:center;">
<span class="math inline">\(SS_{yy}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(n-1\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\frac{SS_{yy}}{(n-1)}\)</span>
</td>
</tr>
</tbody>
</table>
<p>那麼偏 <span class="math inline">\(F\)</span> 檢驗的零假設就是：<span class="math inline">\(B\)</span> 模型中包含，<span class="math inline">\(A\)</span> 模型中不包含的 <span class="math inline">\(k\)</span> 個預測變量的迴歸係數都等於零。</p>
<p><span class="math display" id="eq:lm5-14">\[
\begin{equation}
F=\frac{(SS_{REG-B}-SS_{REG-A})/k}{MS_{RES-B}} \sim F_{k, [n-(p+1)]}
\end{equation}
\tag{30.14}
\]</span></p>
<p>在 R 裏建立兩個模型：</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(wt <span class="op">~</span><span class="st"> </span>len, <span class="dt">data=</span>growgam1)
<span class="kw">print</span>(<span class="kw">summary</span>(Model1), <span class="dt">digits =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wt ~ len, data = growgam1)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -3.155217 -0.629239  0.014555  0.544783  2.928738 
## 
## Coefficients:
##               Estimate Std. Error t value  Pr(&gt;|t|)
## (Intercept) -7.6694406  0.7463556 -10.276 &lt; 2.2e-16
## len          0.2257467  0.0096893  23.299 &lt; 2.2e-16
##                
## (Intercept) ***
## len         ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9532 on 188 degrees of freedom
## Multiple R-squared:  0.74275,    Adjusted R-squared:  0.74139 
## F-statistic: 542.82 on 1 and 188 DF,  p-value: &lt; 2.22e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(<span class="kw">anova</span>(Model1), <span class="dt">digits =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: wt
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## len         1 493.17  493.17  542.82 &lt; 2.2e-16 ***
## Residuals 188 170.80    0.91                      
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Model2 &lt;-<span class="st"> </span><span class="kw">lm</span>(wt <span class="op">~</span><span class="st"> </span>len <span class="op">+</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>sex, <span class="dt">data =</span> growgam1)
<span class="kw">print</span>(<span class="kw">summary</span>(Model2), <span class="dt">digits =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wt ~ len + age + sex, data = growgam1)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -3.110422 -0.648401  0.026103  0.560621  2.768583 
## 
## Coefficients:
##               Estimate Std. Error t value  Pr(&gt;|t|)
## (Intercept) -7.8906758  1.3003091 -6.0683 7.091e-09
## len          0.2317997  0.0198470 11.6793 &lt; 2.2e-16
## age         -0.0077959  0.0168974 -0.4614    0.6451
## sex2        -0.1964758  0.1421171 -1.3825    0.1685
##                
## (Intercept) ***
## len         ***
## age            
## sex2           
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9522 on 186 degrees of freedom
## Multiple R-squared:  0.74599,    Adjusted R-squared:  0.74189 
## F-statistic: 182.08 on 3 and 186 DF,  p-value: &lt; 2.22e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(<span class="kw">anova</span>(Model2), <span class="dt">digits =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: wt
##            Df Sum Sq Mean Sq  F value Pr(&gt;F)    
## len         1 493.17  493.17 543.8753 &lt;2e-16 ***
## age         1   0.41    0.41   0.4540 0.5013    
## sex         1   1.73    1.73   1.9113 0.1685    
## Residuals 186 168.66    0.91                    
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>根據公式 <a href="section-30.html#eq:lm5-14">(30.14)</a>，<span class="math inline">\(F=\frac{0.4116944+1.7330862}{2\times0.9067645} = 1.18\)</span>。<span class="math inline">\(p\)</span> 值可以在 R 裏面這樣計算：</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pf</span>(<span class="dt">df1 =</span> <span class="dv">2</span>,<span class="dt">df2 =</span> <span class="dv">186</span>,<span class="dt">q =</span> (<span class="fl">0.4116944</span><span class="op">+</span><span class="fl">1.7330862</span>)<span class="op">/</span>(<span class="dv">2</span><span class="op">*</span><span class="fl">0.9067645</span>))</code></pre></div>
<pre><code>## [1] 0.3088</code></pre>
<p>更方便的是直接用 <code>anova()</code> 進行偏 <span class="math inline">\(F\)</span> 檢驗：</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(<span class="kw">anova</span>(Model1, Model2), <span class="dt">digits =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: wt ~ len
## Model 2: wt ~ len + age + sex
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1    188 170.80                           
## 2    186 168.66  2    2.1448 1.1827 0.3088</code></pre>
</div>
</div>
<div id="section-30.4" class="section level2">
<h2><span class="header-section-number">30.4</span> 添加新變量對迴歸模型的影響</h2>
<p>當你決定給建立的模型 <span class="math inline">\(\mathbf{A}\)</span> 增加新的預測變量時，輸出的結果<strong>改變</strong>的有：</p>
<ol style="list-style-type: decimal">
<li>模型 <span class="math inline">\(\mathbf{A}\)</span> 原先的預測變量的<strong>偏迴歸係數</strong>會改變；</li>
<li>模型 <span class="math inline">\(\mathbf{A}\)</span> 原先的預測變量的<strong>偏迴歸係數的方差</strong>會改變；</li>
<li>模型 <span class="math inline">\(\mathbf{A}\)</span> 原先的預測變量的<strong>偏迴歸係數的檢驗結果</strong>會改變；</li>
<li>模型 <span class="math inline">\(\mathbf{A}\)</span> 原先的 <strong>擬合值 (predicted values/fitted values)</strong>會改變；</li>
<li>決定係數 <span class="math inline">\(R^2\)</span> 會改變。</li>
</ol>
<div id="section-30.4.1" class="section level3">
<h3><span class="header-section-number">30.4.1</span> 偏迴歸係數方差的改變</h3>
<p>偏迴歸係數矩陣 <span class="math inline">\(\mathbf{\hat\beta}\)</span> 的方差 <span class="math inline">\(\mathbf{(X^\prime X)^{-1}\sigma^2}\)</span> <a href="section-30.html#eq:lm5-5">(30.5)</a>，取決於</p>
<ol style="list-style-type: decimal">
<li>殘差方差 (residual variance) <span class="math inline">\(\sigma^2\)</span>；</li>
<li>樣本量大小 (sample size) <span class="math inline">\(n\)</span>；</li>
<li>預測變量之間的協方差 (covariance between the predictor variable in question and the others)。</li>
</ol>
<p>在簡單線性迴歸中，預測變量的變化性 (variability，用方差或標準差衡量) 越大，迴歸係數的估計就越精確。類似地，多元線性迴歸中，預測變量之間的協方差之所以重要，因爲它決定了<strong>其他預測變量保持不變時</strong>，該預測變量的變化性。如果某兩個預測變量之間高度相關 (high covariance)，那麼當一個預測變量保持不變時，另一個的變化性就很小。</p>
<p>所以當給一個模型加入新的預測變量時，可能觀察的現象是原先模型中已有的預測變量的偏迴歸係數的方差<strong>可能升高，也可能降低</strong>。</p>
<ul>
<li>如果新加入的變量能解釋很大比例的殘差方差，那麼其他原有變量的偏迴歸係數會降低 (變精確)；</li>
<li>如果新加入的變量和原模型中的某個變量高度相關，那麼加入新變量後，原模型中與之高度相關的預測變量的方差會升高 (不精確)，這個現象會在共線性 (collinearity) 中繼續討論。</li>
</ul>
</div>
<div id="section-30.4.2" class="section level3">
<h3><span class="header-section-number">30.4.2</span> 偏迴歸係數檢驗結果的改變</h3>
<p>加入新預測變量時，原有的偏迴歸係數的檢驗結果發生的改變可以歸類成兩種情況：</p>
<ol style="list-style-type: decimal">
<li>估計的偏迴歸係數本身發生了改變；</li>
<li>偏迴歸係數的方差改變，導致了檢驗結果發生變化。</li>
</ol>
</div>
<div id="section-30.4.3" class="section level3">
<h3><span class="header-section-number">30.4.3</span> 擬合值的改變</h3>
<p>很明顯，當模型中加入新的變量，觀察對象的擬合值會發生改變，但是通常這樣的影響要遠遠小於對偏迴歸係數估計 (和其方差) 的影響。</p>
</div>
<div id="section-30.4.4" class="section level3">
<h3><span class="header-section-number">30.4.4</span> 決定係數的改變</h3>
<p>模型中增加新的預測變量，那麼模型的決定係數不會減少，只會增加。</p>
</div>
<div id="-collinearity" class="section level3">
<h3><span class="header-section-number">30.4.5</span> 共線性 collinearity</h3>
<p>當預測變量 <span class="math inline">\(X_1\)</span> 和另一個預測變量 <span class="math inline">\(X_2\)</span> 之間呈高度線性關係時被定義爲共線性現象。如果這兩個變量的關係是<strong>完全線性 (exact linear)</strong>，那麼多元迴歸其實是無法進行的，因爲這兩個變量中的一個隨着另一個改變，無法像我們設想的那樣把其中一個變量保持不變，從而估計另一個變量的迴歸係數。用矩陣表示多元預測變量時 <span class="math inline">\(\mathbf{X}\)</span> 是<strong><a href="https://www.youtube.com/watch?v=UqyN7-tRS00">奇異矩陣 singular matrix</a></strong>，<span class="math inline">\(\mathbf{(X^\prime X)^{-1}}\)</span> 是不存在的。</p>
<p>完全線性的最佳例子是我們在對分類變量使用啞變量的情況下。每個啞變量之間都是完全線性的關係，因而我們只能用 <span class="math inline">\(0,1\)</span> 來編碼啞變量，當某個啞變量存在時，其餘的啞變量取 <span class="math inline">\(0\)</span> 從模型中消失。否則模型將無法擬合。</p>
<p>如果某兩個變量之間高度相關，那麼他們的預測變量矩陣接近 <strong>奇異矩陣</strong>，把這兩個變量同時作爲預測變量放入模型中會引起共線性現象，表現出來的形式有：</p>
<ol style="list-style-type: decimal">
<li>偏迴歸係數的方差變得很大；</li>
<li>偏迴歸係數本身的絕對值變得異常大；</li>
<li>某些已知的重要預測變量的偏迴歸係數變得過小且不再有意義；</li>
<li>雖然會有 1-3 描述的異常現象出現，但是擬合值的變化卻可能微不足道。</li>
</ol>
<p>所以擬合多元線性迴歸模型時，<strong>極爲重要的一點是要避免共線性</strong>。如果有些變量高度相關，必須考慮改變他們放入模型的形式：</p>
<ol style="list-style-type: decimal">
<li>收縮期血壓，舒張期血壓兩個變量是高度相關的，不能一起放入模型中。如果需要同時考慮兩個變量，可以用其中一個，另一個預測變量用二者之差；</li>
<li>身高，體重常常是高度相關的，儘量不要一起放入模型中，可以使用他們的結合形式體質指數 (BMI, <span class="math inline">\(\text{kg/m}^2\)</span>)；</li>
<li>當使用二次方程進行模型擬合的時候，用 <span class="math inline">\((x_i - \bar{x})^2\)</span> 取代 <span class="math inline">\(x_i^2\)</span>。</li>
</ol>
</div>
</div>
<div id="section-30.5" class="section level2">
<h2><span class="header-section-number">30.5</span> 實戰演習</h2>
<div id="-c-" class="section level3">
<h3><span class="header-section-number">30.5.1</span> 血清維生素 C 濃度的預測變量</h3>
<p>數據來自與某個橫斷面研究，其目的是找出與血清維生素 C 濃度相關的預測變量。</p>
<p>數據中個變量含義如下表所示。</p>
<table class="table table-striped table-bordered" style="margin-left: auto; margin-right: auto;">
<caption>
表 30.3: Data set of serum vitamin C level explained
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable name
</th>
<th style="text-align:left;">
content
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<code>serial</code>
</td>
<td style="text-align:left;">
Patient identifier
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>age</code>
</td>
<td style="text-align:left;">
Age of subjects in years
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>height</code>
</td>
<td style="text-align:left;">
Height in metres
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>cigs</code>
</td>
<td style="text-align:left;">
Smoking status (0=non-smoker; 1=smoker)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>weight</code>
</td>
<td style="text-align:left;">
Weight in kg
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>sex</code>
</td>
<td style="text-align:left;">
Gender (0=men; 1=women)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>seruvitc</code>
</td>
<td style="text-align:left;">
Serum Vitamin C level (<span class="math inline">\(\mu\text{mol/L}\)</span>)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>ctakers</code>
</td>
<td style="text-align:left;">
Vitamin C supplements taken (1=yes, 0=no)
</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: decimal">
<li>在 R 裏讀入數據，並對數據內容總結，對維生素C濃度和其他連續性變量作散點圖，對分類變量如性別，吸菸狀況，和維生素C補充劑服用與否之間的維生素 C 濃度作初步的分析表格。</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(haven)
vitC &lt;-<span class="st"> </span><span class="kw">read_dta</span>(<span class="st">&quot;backupfiles/vitC.dta&quot;</span>)

##########################################
<span class="co"># Recoding the categorical variables     #</span>
##########################################

vitC<span class="op">$</span>sex[vitC<span class="op">$</span>sex <span class="op">==</span><span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> &quot;Men&quot;</span>
vitC<span class="op">$</span>sex[vitC<span class="op">$</span>sex <span class="op">==</span><span class="st"> </span><span class="dv">1</span>] &lt;-<span class="st"> &quot;Women&quot;</span>
vitC<span class="op">$</span>sex &lt;-<span class="st"> </span><span class="kw">as.factor</span>(vitC<span class="op">$</span>sex)
vitC<span class="op">$</span>cigs[vitC<span class="op">$</span>cigs <span class="op">==</span><span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> &quot;Non-smoker&quot;</span>
vitC<span class="op">$</span>cigs[vitC<span class="op">$</span>cigs <span class="op">==</span><span class="st"> </span><span class="dv">1</span>] &lt;-<span class="st"> &quot;Smoker&quot;</span>
vitC<span class="op">$</span>cigs &lt;-<span class="st"> </span><span class="kw">as.factor</span>(vitC<span class="op">$</span>cigs)
vitC<span class="op">$</span>ctakers[vitC<span class="op">$</span>ctakers <span class="op">==</span><span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> &quot;No&quot;</span>
vitC<span class="op">$</span>ctakers[vitC<span class="op">$</span>ctakers <span class="op">==</span><span class="st"> </span><span class="dv">1</span>] &lt;-<span class="st"> &quot;Yes&quot;</span>
vitC<span class="op">$</span>ctakers &lt;-<span class="st"> </span><span class="kw">as.factor</span>(vitC<span class="op">$</span>ctakers)

############################################
<span class="co"># End of recoding the categorical variables#</span>
############################################

<span class="kw">summary</span>(vitC) <span class="co">#Basic summary without any package</span></code></pre></div>
<pre><code>##      serial           age           height    
##  Min.   :  1.0   Min.   :65.0   Min.   :1.48  
##  1st Qu.: 23.8   1st Qu.:67.0   1st Qu.:1.58  
##  Median : 49.0   Median :69.0   Median :1.64  
##  Mean   : 49.2   Mean   :69.3   Mean   :1.65  
##  3rd Qu.: 73.2   3rd Qu.:71.0   3rd Qu.:1.72  
##  Max.   :100.0   Max.   :74.0   Max.   :1.89  
##                                 NA&#39;s   :1     
##          cigs        weight         sex    
##  Non-smoker:80   Min.   : 44.0   Men  :44  
##  Smoker    :12   1st Qu.: 57.8   Women:48  
##                  Median : 67.0             
##                  Mean   : 68.6             
##                  3rd Qu.: 76.5             
##                  Max.   :103.0             
##                  NA&#39;s   :1                 
##     seruvitc     ctakers 
##  Min.   :  8.0   No :73  
##  1st Qu.: 34.8   Yes:19  
##  Median : 58.0           
##  Mean   : 53.2           
##  3rd Qu.: 71.0           
##  Max.   :100.0           
## </code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(vitC) <span class="co">#See the first 6 observations</span></code></pre></div>
<pre><code>## # A tibble: 6 x 8
##   serial   age height cigs       weight sex   seruvitc
##    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;fct&gt;       &lt;dbl&gt; &lt;fct&gt;    &lt;dbl&gt;
## 1   1.00  71.0   1.72 Smoker       68.8 Men       9.00
## 2   2.00  70.0   1.63 Non-smoker   58.2 Women    19.0 
## 3   3.00  69.0   1.65 Non-smoker   94.3 Women    69.0 
## 4   4.00  67.0   1.62 Non-smoker   87.6 Women    71.0 
## 5   5.00  68.0   1.53 Non-smoker   66.3 Women    87.0 
## 6   6.00  71.0   1.64 Non-smoker   72.2 Women    96.0 
## # ... with 1 more variable: ctakers &lt;fct&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(psych) <span class="co">#some detailed summary function from this package</span>
<span class="kw">describe</span>(vitC)</code></pre></div>
<pre><code>##          vars  n  mean    sd median trimmed   mad
## serial      1 92 49.25 29.07  49.00   48.97 37.06
## age         2 92 69.32  2.91  69.00   69.27  2.97
## height      3 91  1.65  0.10   1.64    1.64  0.10
## cigs*       4 92  1.13  0.34   1.00    1.04  0.00
## weight      5 91 68.57 13.48  67.00   67.92 14.08
## sex*        6 92  1.52  0.50   2.00    1.53  0.00
## seruvitc    7 92 53.21 23.83  58.00   54.16 22.24
## ctakers*    8 92  1.21  0.41   1.00    1.14  0.00
##            min    max range  skew kurtosis   se
## serial    1.00 100.00 99.00  0.04    -1.23 3.03
## age      65.00  74.00  9.00  0.15    -1.20 0.30
## height    1.48   1.89  0.41  0.33    -0.76 0.01
## cigs*     1.00   2.00  1.00  2.16     2.69 0.04
## weight   44.00 103.00 59.00  0.41    -0.42 1.41
## sex*      1.00   2.00  1.00 -0.09    -2.01 0.05
## seruvitc  8.00 100.00 92.00 -0.40    -0.94 2.48
## ctakers*  1.00   2.00  1.00  1.43     0.04 0.04</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(epiDisplay) <span class="co">#some STATA-like simple summary function</span>
<span class="kw">summ</span>(vitC)</code></pre></div>
<pre><code>## 
## No. of observations = 92
## 
##   Var. name obs. mean   median  s.d.   min.   max.  
## 1 serial    92   49.25  49      29.07  1      100   
## 2 age       92   69.32  69      2.91   65     74    
## 3 height    91   1.65   1.64    0.1    1.48   1.89  
## 4 cigs                                              
## 5 weight    91   68.57  67      13.48  44     103   
## 6 sex                                               
## 7 seruvitc  92   53.21  58      23.83  8      100   
## 8 ctakers</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vitC<span class="op">$</span>serial[<span class="kw">which</span>(<span class="kw">is.na</span>(vitC<span class="op">$</span>height))]</code></pre></div>
<pre><code>## [1] 24</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vitC<span class="op">$</span>serial[<span class="kw">which</span>(<span class="kw">is.na</span>(vitC<span class="op">$</span>weight))]</code></pre></div>
<pre><code>## [1] 24</code></pre>
<p>從初步的熟悉數據結構和歸納結果可以看出，身高體重兩個數據有出現缺損值 (編號 24 的患者)。</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summ</span>(vitC<span class="op">$</span>seruvitc, <span class="dt">by=</span>vitC<span class="op">$</span>sex, <span class="dt">graph =</span> <span class="ot">FALSE</span>) <span class="co"># From package &quot;epiDisplay&quot;</span></code></pre></div>
<pre><code>## For vitC$sex = Men 
##  obs. mean   median  s.d.   min.   max.  
##  44   46.091 52.5    24.877 8      100   
## 
## For vitC$sex = Women 
##  obs. mean   median  s.d.   min.   max.  
##  48   59.729 66.5    21.043 15     96</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summ</span>(vitC<span class="op">$</span>seruvitc, <span class="dt">by=</span>vitC<span class="op">$</span>cigs, <span class="dt">graph =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## For vitC$cigs = Non-smoker 
##  obs. mean   median  s.d.   min.   max.  
##  80   55.138 58      23.323 8      100   
## 
## For vitC$cigs = Smoker 
##  obs. mean   median  s.d.   min.   max.  
##  12   40.333 49.5    24.186 9      68</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summ</span>(vitC<span class="op">$</span>seruvitc, <span class="dt">by=</span>vitC<span class="op">$</span>ctakers, <span class="dt">graph =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## For vitC$ctakers = No 
##  obs. mean   median  s.d.   min.   max.  
##  73   48.644 55      22.795 8      84    
## 
## For vitC$ctakers = Yes 
##  obs. mean   median  s.d.   min.   max.  
##  19   70.737 72      19.612 13     100</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># You can also get similar detailed descriptive statistics by groups from package &quot;psych&quot;</span>
<span class="kw">describeBy</span>(vitC<span class="op">$</span>seruvitc, <span class="dt">group =</span> vitC<span class="op">$</span>sex)</code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: Men
##    vars  n  mean    sd median trimmed   mad min max
## X1    1 44 46.09 24.88   52.5   45.61 25.95   8 100
##    range  skew kurtosis   se
## X1    92 -0.06    -1.12 3.75
## ----------------------------------------- 
## group: Women
##    vars  n  mean    sd median trimmed   mad min max
## X1    1 48 59.73 21.04   66.5   61.15 15.57  15  96
##    range  skew kurtosis   se
## X1    81 -0.65    -0.62 3.04</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">describeBy</span>(vitC<span class="op">$</span>seruvitc, <span class="dt">group =</span> vitC<span class="op">$</span>cigs)</code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: Non-smoker
##    vars  n  mean    sd median trimmed   mad min max
## X1    1 80 55.14 23.32     58    56.3 22.24   8 100
##    range  skew kurtosis   se
## X1    92 -0.43    -0.85 2.61
## ----------------------------------------- 
## group: Smoker
##    vars  n  mean    sd median trimmed  mad min max
## X1    1 12 40.33 24.19   49.5    40.7 25.2   9  68
##    range  skew kurtosis   se
## X1    59 -0.19    -1.93 6.98</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">describeBy</span>(vitC<span class="op">$</span>seruvitc, <span class="dt">group =</span> vitC<span class="op">$</span>ctakers)</code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: No
##    vars  n  mean    sd median trimmed  mad min max
## X1    1 73 48.64 22.79     55   49.47 25.2   8  84
##    range  skew kurtosis   se
## X1    76 -0.33    -1.24 2.67
## ----------------------------------------- 
## group: Yes
##    vars  n  mean    sd median trimmed   mad min max
## X1    1 19 70.74 19.61     72   72.41 19.27  13 100
##    range  skew kurtosis  se
## X1    87 -1.07     1.52 4.5</code></pre>
<p>所以，血清維生素水平在女性，非吸菸者，和服用補充劑(廢話) 的人中較高。</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(vitC<span class="op">$</span>age, vitC<span class="op">$</span>seruvitc, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">xlab =</span> <span class="st">&quot;age on study entry&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Serum ascorbate&quot;</span>)
<span class="kw">plot</span>(vitC<span class="op">$</span>weight, vitC<span class="op">$</span>seruvitc, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">xlab =</span> <span class="st">&quot;Clothed weight&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Serum ascorbate&quot;</span>)
<span class="kw">plot</span>(vitC<span class="op">$</span>height, vitC<span class="op">$</span>seruvitc, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">xlab =</span> <span class="st">&quot;Height&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Serum ascorbate&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:practicalfig1"></span>
<img src="bookdown_files/figure-html/practicalfig1-1.png" alt="Scatter plots between serum ascorbate and age/weight/height" width="80%" />
<p class="caption">
圖 30.1: Scatter plots between serum ascorbate and age/weight/height
</p>
</div>
<p>散點圖似乎沒有證據提示血清維生素 C 濃度和連續型變量，年齡，身高，體重之間有什麼相關性。</p>
<ol start="2" style="list-style-type: decimal">
<li>建立維生素 C 和其他預測變量的簡單線性迴歸模型，你有什麼結論？</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>age, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = seruvitc ~ age, data = vitC)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -44.94 -18.98   5.82  16.67  46.52 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  113.104     59.511    1.90    0.061 .
## age           -0.864      0.858   -1.01    0.316  
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 23.8 on 90 degrees of freedom
## Multiple R-squared:  0.0111, Adjusted R-squared:  0.000163 
## F-statistic: 1.01 on 1 and 90 DF,  p-value: 0.316</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>age, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>##              2.5 %   97.5 %
## (Intercept) -5.125 231.3335
## age         -2.568   0.8401</code></pre>
<p>血清維生素 C 濃度隨着年齡增加遞減，但是迴歸係數不具有統計學意義 (<span class="math inline">\(p=0.32\)</span>)。年齡每增加 1 歲，血清維生素平均下降 <span class="math inline">\(0.864 \:\mu\text{mol/L， 95% CI:} (-2.57, 0.840)\)</span>，</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>height, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = seruvitc ~ height, data = vitC)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -45.11 -19.81   5.76  17.94  48.29 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)    115.9       41.2    2.81    0.006 **
## height         -37.8       25.0   -1.51    0.134   
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 23.3 on 89 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.0251, Adjusted R-squared:  0.0141 
## F-statistic: 2.29 on 1 and 89 DF,  p-value: 0.134</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>height, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>##              2.5 % 97.5 %
## (Intercept)  34.05 197.75
## height      -87.37  11.84</code></pre>
<p>血清維生素 C 濃度隨着身高增加遞減，但是迴歸係數不具有統計學意義 (<span class="math inline">\(p=0.134\)</span>)。身高每增加 1cm，血清維生素平均下降 <span class="math inline">\(0.378 \:\mu\text{mol/L， 95% CI:} (-0.874, 0.118)\)</span>，</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>cigs, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = seruvitc ~ cigs, data = vitC)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -47.14 -19.53   3.26  17.86  44.86 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    55.14       2.62   21.05   &lt;2e-16 ***
## cigsSmoker    -14.80       7.25   -2.04    0.044 *  
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 23.4 on 90 degrees of freedom
## Multiple R-squared:  0.0442, Adjusted R-squared:  0.0336 
## F-statistic: 4.17 on 1 and 90 DF,  p-value: 0.0442</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>cigs, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>##              2.5 %  97.5 %
## (Intercept)  49.93 60.3417
## cigsSmoker  -29.21 -0.3945</code></pre>
<p>血清維生素 C 濃度與在吸菸人羣中較低，與不吸菸人羣相比，吸菸人羣的血清維生素 C 濃度平均低 <span class="math inline">\(14.8 \:\mu\text{mol/L， 95% CI:} (0.394, 29.2)\)</span>，這個濃度差具有臨界統計學意義 <span class="math inline">\((p=0.044)\)</span>。</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>weight, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = seruvitc ~ weight, data = vitC)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -44.71 -18.39   4.41  17.21  46.28 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 53.04017   12.90016    4.11  8.7e-05 ***
## weight       0.00967    0.18463    0.05     0.96    
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 23.6 on 89 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  3.08e-05,   Adjusted R-squared:  -0.0112 
## F-statistic: 0.00274 on 1 and 89 DF,  p-value: 0.958</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>weight, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>##               2.5 %  97.5 %
## (Intercept) 27.4078 78.6725
## weight      -0.3572  0.3765</code></pre>
<p>維生素濃度和體重關係幾乎可以忽略 <span class="math inline">\((p=0.96)\)</span>。</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = seruvitc ~ sex, data = vitC)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -44.73 -20.23   6.59  17.27  53.91 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    46.09       3.46   13.32   &lt;2e-16 ***
## sexWomen       13.64       4.79    2.85   0.0055 ** 
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 23 on 90 degrees of freedom
## Multiple R-squared:  0.0826, Adjusted R-squared:  0.0724 
## F-statistic:  8.1 on 1 and 90 DF,  p-value: 0.00547</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>##             2.5 % 97.5 %
## (Intercept) 39.22  52.97
## sexWomen     4.12  23.16</code></pre>
<p>血清維生素 C 濃度與在女性中較高，與男性相比，女性的血清維生素 C 濃度平均高 <span class="math inline">\(13.6 \:\mu\text{mol/L， 95% CI:} (4.12, 23.2)\)</span>，這個濃度差具有顯著統計學意義 <span class="math inline">\((p=0.005)\)</span>。</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>ctakers, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = seruvitc ~ ctakers, data = vitC)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -57.74 -15.42   5.81  18.61  35.36 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    48.64       2.60   18.73  &lt; 2e-16 ***
## ctakersYes     22.09       5.72    3.87  0.00021 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 22.2 on 90 degrees of freedom
## Multiple R-squared:  0.142,  Adjusted R-squared:  0.133 
## F-statistic: 14.9 on 1 and 90 DF,  p-value: 0.000209</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>ctakers, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>##             2.5 % 97.5 %
## (Intercept) 43.48  53.80
## ctakersYes  10.74  33.45</code></pre>
<p>血清維生素 C 濃度與在服用補充劑的人中較高，與不服用補充劑的人相比，服用者的血清維生素 C 濃度平均高 <span class="math inline">\(22.1 \:\mu\text{mol/L， 95% CI:} (10.7, 33.4)\)</span>，這個濃度差具有顯著統計學意義 <span class="math inline">\((p=0.00021)\)</span>。</p>
<ol start="3" style="list-style-type: decimal">
<li>擬合一個多元線性迴歸模型，因變量爲血清維生素 C 濃度，預測變量使用 性別，吸菸狀態，和 是否服用維生素補充劑。解釋輸出結果的數字的含義。跟這些預測變量單獨和血清維生素 C 濃度建立的簡單線性迴歸模型作比較。說明哪些結果發生了改變，爲什麼。</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>cigs <span class="op">+</span><span class="st"> </span>ctakers, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = seruvitc ~ sex + cigs + ctakers, data = vitC)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -40.66 -19.07   2.24  17.62  38.03 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    44.97       3.55   12.69  &lt; 2e-16 ***
## sexWomen       10.66       4.51    2.36  0.02044 *  
## cigsSmoker    -11.57       6.66   -1.74  0.08586 .  
## ctakersYes     20.25       5.51    3.67  0.00041 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.3 on 88 degrees of freedom
## Multiple R-squared:  0.23,   Adjusted R-squared:  0.203 
## F-statistic: 8.74 on 3 and 88 DF,  p-value: 3.88e-05</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(<span class="kw">anova</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>cigs <span class="op">+</span><span class="st"> </span>ctakers, <span class="dt">data =</span> vitC)), <span class="dt">digits =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: seruvitc
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## sex        1   4270  4270.0  9.4354 0.0028320 ** 
## cigs       1   1497  1497.0  3.3080 0.0723454 .  
## ctakers    1   6102  6101.8 13.4831 0.0004125 ***
## Residuals 88  39824   452.5                      
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(<span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>cigs <span class="op">+</span><span class="st"> </span>ctakers, <span class="dt">data =</span> vitC))</code></pre></div>
<pre><code>##               2.5 % 97.5 %
## (Intercept)  37.927 52.017
## sexWomen      1.687 19.630
## cigsSmoker  -24.799  1.666
## ctakersYes    9.291 31.211</code></pre>
<p>從這個多元線性迴歸的輸出報告來看，血清維生素 C 濃度</p>
<ul>
<li>在吸菸者中較低 <span class="math inline">\(-11.6 \:\mu\text{mol/L， 95% CI:} (-24.8, +1.67), p = 0.086\)</span>；</li>
<li>在女性中較高 <span class="math inline">\(+10.7 \:\mu\text{mol/L， 95% CI:} (1.69, 19.6), p = 0.020\)</span>；</li>
<li>在服用維生素補充劑的人中較高 <span class="math inline">\(+20.3 \:\mu\text{mol/L， 95% CI:} (9.29, 31.2), p = 0.0004\)</span>。</li>
</ul>
<p>故，本次數據告訴我們，服用維生素補充劑是最強的預測變量。在多元線性迴歸模型的結果中可以看到：</p>
<ul>
<li>性別之間維生素 C 濃度差變小了 (<span class="math inline">\(+13.6 \rightarrow +10.7\)</span>) <br> 這是因爲女性中有較多人服用維生素補充劑。即便如此，性別差在多元線性迴歸模型中仍然是有意義的。</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span>Epi<span class="op">::</span><span class="kw">stat.table</span>(<span class="kw">list</span>(<span class="st">&quot;Vitamin C taker&quot;</span>=ctakers, <span class="st">&quot;Gender&quot;</span> =<span class="st"> </span>sex), <span class="kw">list</span>(<span class="kw">count</span>(),<span class="kw">percent</span>(ctakers)), <span class="dt">data =</span> vitC, <span class="dt">margins =</span> <span class="ot">TRUE</span>)
<span class="kw">print</span>(a, <span class="dt">digits =</span> <span class="kw">c</span>(<span class="dt">percent =</span> <span class="dv">2</span>))</code></pre></div>
<pre><code>##  ---------------------------------- 
##           ---------Gender---------- 
##  Vitamin       Men   Women   Total  
##  C taker                            
##  ---------------------------------- 
##  No             37      36      73  
##              84.09   75.00   79.35  
##                                     
##  Yes             7      12      19  
##              15.91   25.00   20.65  
##                                     
##                                     
##  Total          44      48      92  
##             100.00  100.00  100.00  
##  ----------------------------------</code></pre>
<ul>
<li>吸菸與非吸菸者之間的維生素 C 濃度差也變小了 (<span class="math inline">\(-14.8 \rightarrow -11.6\)</span>)，因爲儘管吸菸與非吸菸者的維生素補充劑服用比例差不不大，但是吸菸者中大部分是男性。(詳見下表) <br> 吸菸者和非吸菸者之間維生素 C 濃度差經過多元線性迴歸調整後變得不再有統計學意義 <span class="math inline">\((p=0.086)\)</span>。</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span>Epi<span class="op">::</span><span class="kw">stat.table</span>(<span class="kw">list</span>(<span class="st">&quot;Vitamin C taker&quot;</span>=ctakers, <span class="st">&quot;Smoker&quot;</span> =<span class="st"> </span>cigs), <span class="kw">list</span>(<span class="kw">count</span>(),<span class="kw">percent</span>(ctakers)), <span class="dt">data =</span> vitC, <span class="dt">margins =</span> <span class="ot">TRUE</span>)
<span class="kw">print</span>(a, <span class="dt">digits =</span> <span class="kw">c</span>(<span class="dt">percent =</span> <span class="dv">2</span>))</code></pre></div>
<pre><code>##  ------------------------------------- 
##           -----------Smoker----------- 
##  Vitamin   Non-smoker  Smoker   Total  
##  C taker                               
##  ------------------------------------- 
##  No                63      10      73  
##                 78.75   83.33   79.35  
##                                        
##  Yes               17       2      19  
##                 21.25   16.67   20.65  
##                                        
##                                        
##  Total             80      12      92  
##                100.00  100.00  100.00  
##  -------------------------------------</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span>Epi<span class="op">::</span><span class="kw">stat.table</span>(<span class="kw">list</span>(<span class="st">&quot;Gender&quot;</span> =<span class="st"> </span>sex, <span class="st">&quot;Smoker&quot;</span> =<span class="st"> </span>cigs), <span class="kw">list</span>(<span class="kw">count</span>(),<span class="kw">percent</span>(sex)), <span class="dt">data =</span> vitC, <span class="dt">margins =</span> <span class="ot">TRUE</span>)
<span class="kw">print</span>(a, <span class="dt">digits =</span> <span class="kw">c</span>(<span class="dt">percent =</span> <span class="dv">2</span>))</code></pre></div>
<pre><code>##  ------------------------------------ 
##          -----------Smoker----------- 
##  Gender   Non-smoker  Smoker   Total  
##  ------------------------------------ 
##  Men              36       8      44  
##                45.00   66.67   47.83  
##                                       
##  Women            44       4      48  
##                55.00   33.33   52.17  
##                                       
##                                       
##  Total            80      12      92  
##               100.00  100.00  100.00  
##  ------------------------------------</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>在前一個模型中加入年齡，身高，體重作爲新的預測變量。先解釋新的模型中報告的個數值的意義，利用方差分析表格比較兩個模型的差別 (先手計算，再用 R 計算確認你的答案)。</li>
</ol>
<p>由於身高體重有缺損值(serial=24)，所以要比較預測變量增加前後的模型，需要先把之前的模型中 serial=24 的觀察對象刪除掉才公平。</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>cigs <span class="op">+</span><span class="st"> </span>ctakers, <span class="dt">data =</span> vitC[<span class="op">-</span><span class="dv">24</span>,])
<span class="kw">summary</span>(Model1);<span class="kw">anova</span>(Model1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = seruvitc ~ sex + cigs + ctakers, data = vitC[-24, 
##     ])
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -40.79 -18.21   2.21  17.59  36.97 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    46.03       3.55   12.96  &lt; 2e-16 ***
## sexWomen        9.76       4.49    2.18  0.03228 *  
## cigsSmoker    -12.26       6.59   -1.86  0.06627 .  
## ctakersYes     19.83       5.45    3.64  0.00047 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21 on 87 degrees of freedom
## Multiple R-squared:  0.226,  Adjusted R-squared:  0.199 
## F-statistic: 8.46 on 3 and 87 DF,  p-value: 5.39e-05</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: seruvitc
##           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## sex        1   3689    3689    8.35 0.00486 ** 
## cigs       1   1679    1679    3.80 0.05440 .  
## ctakers    1   5841    5841   13.23 0.00047 ***
## Residuals 87  38418     442                    
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Model2 &lt;-<span class="st"> </span><span class="kw">lm</span>(seruvitc <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>cigs <span class="op">+</span><span class="st"> </span>ctakers <span class="op">+</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>weight <span class="op">+</span><span class="st"> </span>height, <span class="dt">data =</span> vitC[<span class="op">-</span><span class="dv">24</span>,])
<span class="kw">summary</span>(Model2);<span class="kw">anova</span>(Model2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = seruvitc ~ sex + cigs + ctakers + age + weight + 
##     height, data = vitC[-24, ])
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -40.56 -17.72   4.23  18.75  35.58 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   65.352     89.482    0.73  0.46722    
## sexWomen      10.367      7.285    1.42  0.15843    
## cigsSmoker   -11.800      6.757   -1.75  0.08444 .  
## ctakersYes    19.859      5.547    3.58  0.00057 ***
## age           -0.353      0.840   -0.42  0.67499    
## weight         0.107      0.223    0.48  0.63174    
## height        -1.573     42.259   -0.04  0.97040    
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.3 on 84 degrees of freedom
## Multiple R-squared:  0.233,  Adjusted R-squared:  0.178 
## F-statistic: 4.25 on 6 and 84 DF,  p-value: 0.00088</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: seruvitc
##           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## sex        1   3689    3689    8.14 0.00546 ** 
## cigs       1   1679    1679    3.70 0.05767 .  
## ctakers    1   5841    5841   12.88 0.00056 ***
## age        1    205     205    0.45 0.50283    
## weight     1    133     133    0.29 0.58951    
## height     1      1       1    0.00 0.97040    
## Residuals 84  38079     453                    
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>利用偏 <span class="math inline">\(F\)</span> 檢驗的公式</p>
<p><span class="math display">\[
F=\frac{(205.2889295+132.9899543+0.6280691)/3}{38079.42/84} = 0.2492713
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(Model1, Model2)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: seruvitc ~ sex + cigs + ctakers
## Model 2: seruvitc ~ sex + cigs + ctakers + age + weight + height
##   Res.Df   RSS Df Sum of Sq    F Pr(&gt;F)
## 1     87 38418                         
## 2     84 38079  3       339 0.25   0.86</code></pre>
<p>所以檢驗統計量對應的 <span class="math inline">\(p=0.86\)</span> 告訴我們沒有證明據證明調整了性別，吸菸狀況，服用補充劑與否之後，增加的年齡，體重，身高作爲預測變量和觀察對象的血清維生素 C 濃度有關係。模型 2 比模型 1 不能解釋更多的模型殘差 (不比模型 1 更加擬合數據)。</p>
</div>
<div id="section-30.5.2" class="section level3">
<h3><span class="header-section-number">30.5.2</span> 紅細胞容積與血紅蛋白</h3>
<table class="table table-striped table-bordered" style="margin-left: auto; margin-right: auto;">
<caption>
表 30.4: Data set of haemoglobin and PCV explained
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable name
</th>
<th style="text-align:left;">
content
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<code>hb</code>
</td>
<td style="text-align:left;">
Haemoglobin (gm/dl)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>pcv</code>
</td>
<td style="text-align:left;">
Pack cell volume %
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>age</code>
</td>
<td style="text-align:left;">
Age (years)
</td>
</tr>
<tr>
</tbody>
</table>
<ol start="5" style="list-style-type: decimal">
<li>把數據導入 R，並且建立因變量爲血紅蛋白，預測變量爲 PCV 和 年齡的多元線性迴歸模型</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(haven)
haem &lt;-<span class="st"> </span><span class="kw">read_dta</span>(<span class="st">&quot;backupfiles/haem.dta&quot;</span>)
psych<span class="op">::</span><span class="kw">describe</span>(haem)</code></pre></div>
<pre><code>##     vars  n  mean   sd median trimmed   mad  min  max
## hb     1 12 12.53 1.70   12.8   12.56  1.70  9.6 15.1
## pcv    2 12 38.58 8.14   37.5   38.80 11.12 25.0 50.0
## age    3 12 32.75 8.98   31.5   32.40  9.64 20.0 49.0
##     range  skew kurtosis   se
## hb    5.5 -0.26    -1.39 0.49
## pcv  25.0 -0.10    -1.59 2.35
## age  29.0  0.31    -1.20 2.59</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Model3 &lt;-<span class="st"> </span><span class="kw">lm</span>(hb <span class="op">~</span><span class="st"> </span>pcv <span class="op">+</span><span class="st"> </span>age, <span class="dt">data =</span> haem)
<span class="kw">summary</span>(Model3)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = hb ~ pcv + age, data = haem)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -1.413 -1.002  0.302  0.662  1.867 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)   5.0606     1.9680    2.57    0.030 *
## pcv           0.1056     0.0429    2.46    0.036 *
## age           0.1036     0.0389    2.66    0.026 *
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.15 on 9 degrees of freedom
## Multiple R-squared:  0.63,   Adjusted R-squared:  0.548 
## F-statistic: 7.65 on 2 and 9 DF,  p-value: 0.0114</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">haem<span class="op">$</span>e_hat &lt;-<span class="st"> </span>Model3<span class="op">$</span>residuals
haem<span class="op">$</span>y_hat &lt;-<span class="st"> </span>Model3<span class="op">$</span>fitted.values
<span class="kw">print</span>(haem)</code></pre></div>
<pre><code>## # A tibble: 12 x 5
##       hb   pcv   age  e_hat y_hat
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 11.1   35.0  20.0  0.274  10.8
##  2 10.7   45.0  22.0 -1.39   12.1
##  3 12.4   47.0  25.0 -0.211  12.6
##  4 14.0   50.0  28.0  0.762  13.2
##  5 13.1   31.0  28.0  1.87   11.2
##  6 10.5   30.0  31.0 -0.938  11.4
##  7  9.60  25.0  32.0 -1.41   11.0
##  8 12.5   33.0  35.0  0.331  12.2
##  9 13.5   35.0  38.0  0.810  12.7
## 10 13.9   40.0  40.0  0.475  13.4
## 11 15.1   45.0  45.0  0.629  14.5
## 12 13.9   47.0  49.0 -1.20   15.1</code></pre>
<ol start="6" style="list-style-type: decimal">
<li>利用 R 的矩陣計算重現迴歸模型的計算結果</li>
</ol>
<ul>
<li>計算因變量和兩個預測變量各自的和</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sumy &lt;-<span class="st"> </span><span class="kw">sum</span>(haem<span class="op">$</span>hb)
sumx1 &lt;-<span class="st"> </span><span class="kw">sum</span>(haem<span class="op">$</span>pcv)
sumx2 &lt;-<span class="st"> </span><span class="kw">sum</span>(haem<span class="op">$</span>age)</code></pre></div>
<ul>
<li>計算因變量和兩個預測變量各自的平方和</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sumy2 &lt;-<span class="st"> </span><span class="kw">sum</span>((haem<span class="op">$</span>hb)<span class="op">^</span><span class="dv">2</span>)
sumx1y &lt;-<span class="st"> </span><span class="kw">sum</span>(haem<span class="op">$</span>hb<span class="op">*</span>haem<span class="op">$</span>pcv)
sumx2y &lt;-<span class="st"> </span><span class="kw">sum</span>(haem<span class="op">$</span>hb<span class="op">*</span>haem<span class="op">$</span>age)
sumx12 &lt;-<span class="st"> </span><span class="kw">sum</span>((haem<span class="op">$</span>pcv)<span class="op">^</span><span class="dv">2</span>)
sumx22 &lt;-<span class="st"> </span><span class="kw">sum</span>((haem<span class="op">$</span>age)<span class="op">^</span><span class="dv">2</span>)
sumx1x2 &lt;-<span class="st"> </span><span class="kw">sum</span>(haem<span class="op">$</span>pcv<span class="op">*</span>haem<span class="op">$</span>age)</code></pre></div>
<ul>
<li>生成一個數值爲 1 的變量，名爲 <code>one</code></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">one &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span>,<span class="dv">12</span>)</code></pre></div>
<ul>
<li>用 <code>matrix()</code> 命令生成矩陣</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Rownames &lt;-<span class="st"> </span><span class="ot">NULL</span>
<span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">12</span>) {
  a &lt;-<span class="st"> </span><span class="kw">paste</span>(<span class="st">&quot;row&quot;</span>, i, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>)
  Rownames &lt;-<span class="st"> </span><span class="kw">c</span>(Rownames,a); <span class="kw">rm</span>(a)
  }

Y &lt;-<span class="st"> </span><span class="kw">matrix</span>(haem<span class="op">$</span>hb ,<span class="dt">dimnames =</span> <span class="kw">list</span>(Rownames, <span class="st">&quot;hb&quot;</span>))
Y</code></pre></div>
<pre><code>##         hb
## row1  11.1
## row2  10.7
## row3  12.4
## row4  14.0
## row5  13.1
## row6  10.5
## row7   9.6
## row8  12.5
## row9  13.5
## row10 13.9
## row11 15.1
## row12 13.9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(one, haem<span class="op">$</span>pcv, haem<span class="op">$</span>age), <span class="dt">nrow =</span> <span class="dv">12</span>, <span class="dt">dimnames =</span> <span class="kw">list</span>(Rownames, <span class="kw">c</span>(<span class="st">&quot;one&quot;</span>, <span class="st">&quot;pcv&quot;</span>, <span class="st">&quot;age&quot;</span>)))
X</code></pre></div>
<pre><code>##       one pcv age
## row1    1  35  20
## row2    1  45  22
## row3    1  47  25
## row4    1  50  28
## row5    1  31  28
## row6    1  30  31
## row7    1  25  32
## row8    1  33  35
## row9    1  35  38
## row10   1  40  40
## row11   1  45  45
## row12   1  47  49</code></pre>
<ul>
<li>用公式 <a href="section-30.html#eq:lm5-4">(30.4)</a> 計算估計 <span class="math inline">\(\mathbf{\hat\beta}\)</span> 矩陣</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">XX &lt;-<span class="st"> </span><span class="kw">t</span>(X) <span class="op">%*%</span><span class="st"> </span>X <span class="co"># these are the sum of squares of each variable and the sum of the cross products of the pairs of variables</span>
XX</code></pre></div>
<pre><code>##     one   pcv   age
## one  12   463   393
## pcv 463 18593 15276
## age 393 15276 13757</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(<span class="kw">data.frame</span>(sumx1,sumx12,sumx2,sumx22, sumx1x2))</code></pre></div>
<pre><code>##   sumx1 sumx12 sumx2 sumx22 sumx1x2
## 1   463  18593   393  13757   15276</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">XY &lt;-<span class="st"> </span><span class="kw">t</span>(X) <span class="op">%*%</span><span class="st"> </span>Y <span class="co"># this is the cross-product matrix of predictors against outcome</span>
XY</code></pre></div>
<pre><code>##         hb
## one  150.3
## pcv 5887.7
## age 5026.0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(<span class="kw">data.frame</span>(sumy, sumx1y, sumx2y))</code></pre></div>
<pre><code>##    sumy sumx1y sumx2y
## 1 150.3   5888   5026</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">betahat &lt;-<span class="st"> </span><span class="kw">solve</span>( <span class="kw">t</span>(X) <span class="op">%*%</span><span class="st"> </span>X ) <span class="op">%*%</span><span class="st"> </span><span class="kw">t</span>(X) <span class="op">%*%</span><span class="st"> </span>Y
betahat</code></pre></div>
<pre><code>##         hb
## one 5.0606
## pcv 0.1056
## age 0.1036</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">###or equivalently you can use
betahat &lt;-<span class="st"> </span><span class="kw">solve</span>( <span class="kw">crossprod</span>(X) ) <span class="op">%*%</span><span class="st"> </span><span class="kw">crossprod</span>( X, Y )
betahat</code></pre></div>
<pre><code>##         hb
## one 5.0606
## pcv 0.1056
## age 0.1036</code></pre>
<p>可以看到 <code>betahat</code> 的結果和多元迴歸模型輸出的迴歸係數估計是一致的。</p>
<ul>
<li>計算擬合值</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Fitted &lt;-<span class="st"> </span>X<span class="op">%*%</span>betahat
Fitted</code></pre></div>
<pre><code>##          hb
## row1  10.83
## row2  12.09
## row3  12.61
## row4  13.24
## row5  11.23
## row6  11.44
## row7  11.01
## row8  12.17
## row9  12.69
## row10 13.43
## row11 14.47
## row12 15.10</code></pre>
<ul>
<li>估計迴歸係數的方差協方差矩陣</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">e_hat &lt;-<span class="st"> </span>Y<span class="op">-</span>Fitted <span class="co"># residuals</span>
e_hat</code></pre></div>
<pre><code>##            hb
## row1   0.2736
## row2  -1.3892
## row3  -0.2110
## row4   0.7616
## row5   1.8674
## row6  -0.9377
## row7  -1.4134
## row8   0.3314
## row9   0.8096
## row10  0.4747
## row11  0.6291
## row12 -1.1962</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">SSres &lt;-<span class="st"> </span><span class="kw">t</span>(e_hat) <span class="op">%*%</span><span class="st"> </span>e_hat <span class="co"># residual sum of squares</span>
SSres</code></pre></div>
<pre><code>##       hb
## hb 11.81</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Sigma2 &lt;-<span class="st"> </span>SSres <span class="op">%*%</span><span class="st"> </span>(<span class="dv">1</span><span class="op">/</span>(<span class="dv">12</span><span class="op">-</span>(<span class="dv">2</span><span class="op">+</span><span class="dv">1</span>))) <span class="co"># residual variance</span>
Sigma2</code></pre></div>
<pre><code>##     [,1]
## hb 1.312</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># multiply the inverse of the cross-product matrix for the predictors</span>
<span class="co"># by the residual variance to get the variance-covariance matrix of</span>
<span class="co"># the coefficients</span>
V &lt;-<span class="st"> </span><span class="kw">solve</span>( <span class="kw">crossprod</span>(X) ) <span class="op">*</span><span class="st"> </span><span class="kw">as.numeric</span>(Sigma2)
V</code></pre></div>
<pre><code>##          one        pcv        age
## one  3.87296 -0.0632072 -0.0404537
## pcv -0.06321  0.0018365 -0.0002336
## age -0.04045 -0.0002336  0.0015105</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># the square root of the diagonal terms in the above matrix are the standard errors shown in the regression output</span>
<span class="kw">sqrt</span>(<span class="kw">diag</span>(V))</code></pre></div>
<pre><code>##     one     pcv     age 
## 1.96798 0.04285 0.03887</code></pre>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="-multivariable-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="section-31.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/winterwang/LSHTMlearningnote/edit/master/04-Linear-Regression.Rmd",
"text": "編輯"
},
"download": ["bookdown.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
