## Beta 二項分佈模型 beta-binomial model 

Beta 二項分佈模型其實是一系列的二項分佈模型的混合體 (a mixture of binomial distributions)。它假定的是每個二進制觀測值，都有自己的實際成功概率。該模型的目的是估計這些成功概率所構成的概率分佈 (estimate the distribution of probabilities of success)，而不是某一個特定的試驗的成功概率。

我們使用大學錄取率這個數據來解釋這個模型。這個數據本身如果我們不知道每個學院之間的錄取率相差很大，也就是當數據本身如果不含有學院 (`dept`) 信息時，我們可能會誤認爲整所大學的錄取率都是一樣的。我們之前是通過在邏輯回歸模型種增加學院 `dept` 這一個變量來獲得正確的男女申請人錄取率之差的比較的。這裏我們轉換一個思路，使用beta二項分佈模型，並且不把學院當作已知變量，看這個模型的神奇之處。它的靈活性在於，該模型會初始默認每一行觀測值，都其實有自己的錄取（成功）概率，而不是統一的錄取概率。這些不同的錄取概率本身構成了一個分佈，它可以用 beta 分佈來描述。beta分佈有兩個參數，一個是平均成功概率 (average probability) $\bar{p}$，還有一個是描述概率分佈密度形狀的形狀參數 (shape parameter) $\theta$。$\theta$ 負責描述這些概率在 $[0, 1]$ 的範圍內的分佈有多寬泛 (how spread out the distribution is)。當 $\theta = 2$ 時，是一個平坦分佈，也就是從 0 到 1 之間的所有概率的概率是相同的 (every probability from 0 to 1 is equally likely)。當 $\theta > 2$，分佈變得越來越向中間的平均概率處集中 (more concentrated)，當 $\theta <  2$，分佈本身則越來越向兩邊的極端概率處靠攏 (dispersed that extreme probabilities near 0 and 1 are more likely than the mean)。它的概率密度分佈圖可以用下面的代碼來獲得：


```{r introBayes14-fig01, cache=TRUE, fig.width=6, fig.height=5,  fig.cap="", fig.align='center'}
curve( dbeta2(x, 0.5, 5), from = 0, to = 1, 
       xlab = "probability", ylab = "Density", 
       bty = "n", ylim = c(0, 4),
       main = "beta distributions with different parameters")
curve( dbeta2(x, 0.5, 1), from = 0, to = 1, 
       add =  TRUE, col = rangi2, lwd = 2)
curve( dbeta2(x, 0.5, 2), from = 0, to = 1, 
       add =  TRUE, col = "red")
text(0.5, 2, "beta(p = 0.5, theta = 5)")
text(0.5, 0.3, "beta(p = 0.5, theta = 1)", col = rangi2)
text(0.5, 1.2, "beta(p = 0.5, theta = 2)", col = "red")
```

